### ISSUE TITLE
Stage 1 - Multiple input files not processing correctly. 

### ISSUE THREAD

**Issue by AarynnCarter** [kevin218/Eureka#102]
Encountering some strange behaviour when running Stage 1 on the NIRCam simulated data. As this dataset is split across two files, it should end up producing two separate _rateints.fits files, but it instead only produces one. The confusing thing is that the code definitely runs on each file, and the .log file reflects this, but only the first segmented file appears. 

EDIT: The data is actually split over 21 files, but I've been testing on just two for speed. 

A little stumped, and was hoping @taylorbell57 / @evamariaa could clone the recent s1 branch and see if the same thing happens on your end? 

Cheers!

[S1_nirx_template.log](https://github.com/kevin218/Eureka/files/7980988/S1_nirx_template.log)
 
[S1_nirx_template.ecf.zip](https://github.com/kevin218/Eureka/files/7981017/S1_nirx_template.ecf.zip)

![image](https://user-images.githubusercontent.com/23636747/152027800-2248de1f-8434-4417-a5a1-2bd7165b2e73.png)

**Comment by AarynnCarter** [comment]
Also note that you need to add

`if __name__ == '__main__':`

prior to calling stage one if you want to use multiprocessing. This is a similar issue to #92, if it's not present then it will recursively start Stage 1, producing new run folders, but never actually reduces the data.

**Comment by taylorbell57** [comment]
Hi Aarynn, I'm fairly busy today/tomorrow but I'll take a look at this as soon as I can

**Comment by AarynnCarter** [comment]
No worries at all, thanks Taylor!

**Comment by taylorbell57** [comment]
Alright, I have just confirmed that at least the trapsfilled.fits, rate.fits, and rateints.fits files from subsequent files overwrite the original outputs from the first file. Not sure why the output filenames don't update, but I'll look into it more.

**Comment by taylorbell57** [comment]
Well, it's a bit hacky, but inserting a simple `self.__init__()` line immediately after the `for m in range(...` line helps by re-initializing all of the steps to make sure their output filenames are updated. There's likely something cleaner than this, but this is what I came up with for now.

**Comment by evamariaa** [comment]
Hi both, I just ran that and had a similar issue, but works now with Taylor's hack.
I'll take some more time to look more into the underlying code saving the data but I couldn't find a cleaner way than Taylor's suggestion so far.

**Comment by AarynnCarter** [comment]
Thanks both, glad to hear it's not just something happening on my machine. I'll incorporate Taylor's fix for now, but will keep the issue open in case we think of something better.

**Comment by taylorbell57** [comment]
Also, you will need to change the default for maximum_cores to be 'none' instead since ints are not allowed

**Comment by AarynnCarter** [comment]
Closing as this was resolved when I restructured the s1_process file.
