### ISSUE TITLE
test_lightcurve_fitting.py failing because of change to ExponentialModel name

### ISSUE THREAD

**Issue by cpiaulet** [kevin218/Eureka#110]
When I ran 
`pytest`

to test my Eureka! installation, I got the following error message:

`AttributeError: module 'eureka.S5_lightcurve_fitting.models' has no attribute 'ExponentialModel'`

(out of the 10 tests, it is the only one that failed).

**Comment by cpiaulet** [comment]
I found in models/ the `ExpRampModel` model that seems to do what we would expect of an exponential model (with the coefficients), and updated `test_exponentialmodel()` definition in test_lightcurve_fitting.py according to how the model is defined in models/.

When running `pytest` again, everything seems to run smoothly now!
I will submit a pull request for this small edit

**Comment by jbrande** [comment]
Thanks for catching this, Caroline, I think it's technically my responsibility! I just pulled down the most recent version and verified the issue exists, but I've got some other problem which makes the straight substitution fail. I'll bring this up in the meeting today.

**Comment by jbrande** [comment]
Thanks for catching this, @cpiaulet! I think it's technically my responsibility to fix the tests. I just pulled down the most recent version and verified the issue exists, but I've got some other problem which makes the straight substitution fail. I'll bring this up in the meeting today.

**Comment by jbrande** [comment]
Actually, this is fine and I see Kevin already approved the PR. That can go ahead and get merged!

**Comment by kevin218** [comment]
I'm going to merge the PR now and close this issue.
