### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#112]
Hi all, so @cpiaulet had some issues installing Eureka which made me think deeper about our installation instructions. We currently say that people should do `python setup.py install` which is an outdated and somewhat dangerous/complicated way of having people install a package. The recommended way to install things now is to do `pip install .` within the downloaded package folder which itself calls the setup.py file but does all the work of checking for dependencies. If we simply require that everyone does the pip install option, then we can clean out a lot of what is in the requirements.py file which is already incomplete and out of date since many of the version requirements are coming from other packages we're installing rather than any requirements of our code. With this option, we only put the packages we actually call with Eureka into the requirements.txt file which should be quite easy. However, down the road someone will likely try running `python setup.py install` out of habit and the command will fail. If we don't want to have that command fail then we'll need to do a lot of upkeep on the requirements.txt file, otherwise we can just have a note on the readthedocs FAQ page that tells people that they should try installing again with `pip install .`

What path do you recommend we take?

**Comment by taylorbell57** [comment]
The other advatage of the pip option is that it allows code to be uninstalled - the setup.py method doesn't allow for a clean way of uninstalling code

**Comment by afeinstein20** [comment]
I think we talked about `pip install` last week and the conclusion was that it would be hard to make it pip installable while using the `.ecf` files, since they would be installed in the same directory as `eureka`. I think the conclusion was we'd create 2 version: one with the `.ecf` files and one with class wrappers per each instrument/stage. This second version would be available on pip (possibly under `eureka-pipeline`, which is currently available). 

I don't think `python setup.py install` is necessarily dangerous, as long as we keep the `requirements.txt` file updated and maybe throw together better docs for how to do that, including "commonly encountered issues"

**Comment by taylorbell57** [comment]
The pip thing I'm talking about isn't about hosting Eureka on PyPy - I mean that we would still have users download the code from GitHub and then do `pip install .` rather than `python setup.py install`. The pip command is the recommended method of installing packages and directly calling setup.py is deprecated as of python 3.10 and maybe even blocked by 3.12 or at least not available without effort (e.g. [link1](https://stackoverflow.com/questions/15724093/difference-between-python-setup-py-install-and-pip-install), [link2](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html), [link3](https://www.python.org/dev/peps/pep-0632/))

**Comment by taylorbell57** [comment]
For some reason they haven't been advertising this deprecation, but it explains why things worked totally fine for me on python 3.9 but @cpiaulet couldn't install things properly with python 3.10 without having to separately install extension_helpers before calling setup.py. I tried adding extension_helpers to the requirements file, but the setup.py file doesn't listen to the ordering of the requirements file and still throws an error saying that extension_helpers isn't installed. So keeping the instructions to directly call the setup.py file will mean that we have to tell people to first do `pip install -r requirements.txt` and then call `python setup.py install` or at least do `pip install extension_helpers` and then `python setup.py install` which is a whole lot more complicated than just `pip install .` which takes care of all of those dependency issues regardless of python version

**Comment by afeinstein20** [comment]
to be fair, I also had problems installing on python 3.9.7, but I'd be interested to see if this fixes the issues all around

**Comment by kevin218** [comment]
I'm intrigued by a quick and clean install procedure (such as pip install) after people have downloaded the code from GitHub.  How much effort would this take to test/implement?  We're about to get a lot of users over the next couple of weeks as people start playing with the simulated data.

**Comment by taylorbell57** [comment]
No time at all, I can have a PR up in minutes (most of which will be editing the documentation). I've already tested that it works for me, and if one or two others can test it on their system then we should be pretty sure it works just fine. I can test it on my personal linux system and maybe even my windows system too if we wanted
