### ISSUE TITLE
Eureka flowchart 

### ISSUE THREAD

**Issue by afeinstein20** [kevin218/Eureka#113]
I think it would be useful to have some kind of flow chart or visual guide to all of the moving pieces in eureka, because there are a lot! It doesn't have to be super fancy, just something that outlines what's done in S1, S2, S3, and what tools are available in S4 and S5.

**Comment by afeinstein20** [comment]
Totally, thanks!! I was also thinking of something like these [stage processing flowcharts](https://jwst-docs.stsci.edu/jwst-science-calibration-pipeline-overview/stages-of-jwst-data-processing/calwebb_spec3) but ours would be by instrument, rather than observation type... I think

**Comment by taylorbell57** [comment]
Did PR #442 adequately resolve this issue? The new flowcharts are at https://eurekadocs.readthedocs.io/en/latest/stages.html

**Comment by taylorbell57** [comment]
Marking this as closed now given the above PR, but feel free to reopen if you feel there is still more work to be done here
