### ISSUE TITLE
Tiny error bars out of S4 when the S2 photom step is run

### ISSUE THREAD

**Issue by cpiaulet** [kevin218/Eureka#121]
If I run S3, then S4 of Eureka! from the S2 jwst pipeline products (I tried NIRCam and NIRSpec so far), I get very small error bars on the points in individual wavelength-dependent light curves. 

Is there some other unit conversion that needs to happen on the uncertainties to correct for this? @taylorbell57 tells me this does not occur if the photom step is skipped.

On a related note, do we have plans to add the single-point scatter as a free parameter in the S5 fit? It could be useful if errors are over- or underestimated in previous steps.

**Comment by cpiaulet** [comment]
Looking at it more closely, there seems to be something else at play other than the error bars themselves. When I run S3 and S4 again after running S2 myself without the phantom step, the background subtraction looks a lot different, as well as the light curves.
<img width="746" alt="fromS2jwst_S3output_Int10" src="https://user-images.githubusercontent.com/38121553/154551056-ccbd3783-8ddd-4585-9ed7-06c31b95f742.png">
<img width="740" alt="fromS2customnophotom_S3output_Int10" src="https://user-images.githubusercontent.com/38121553/154551061-d453db0a-7432-40d9-97b6-c34a91be7478.png">


<img width="991" alt="fromS2jwst_S4output_bandpass15" src="https://user-images.githubusercontent.com/38121553/154550822-83d2cf85-934c-452b-800c-4e5a91691e7c.png">
<img width="984" alt="fromS2customnophotom_S4output_bandpass15" src="https://user-images.githubusercontent.com/38121553/154550827-6bfa54f5-4b08-4902-bdd9-ce8297f23ed8.png">

**Comment by taylorbell57** [comment]
Are the first plots with photom and the second without photom?

**Comment by cpiaulet** [comment]
Yes

**Comment by cpiaulet** [comment]
This is for the NIRSpec PRISM data set for the 2022 data challenge

**Comment by taylorbell57** [comment]
Hmm, seems to me either the photom step is doing some irrecoverable damage or our attempts at converting units after the photom step are significantly flawed

**Comment by cpiaulet** [comment]
Sure! and I'd be happy to help with this as well :)

**Comment by kevin218** [comment]
The background subtraction is different between these two cases. I'm guessing the bad one uses median frame while the good one uses column-by-column.

**Comment by kevin218** [comment]
I just had a meeting with Erin May, who is reporting the same issue when `skip_photom = False`.  So, either the BG subtraction is failing badly when using MJy or, as Taylor suggested, there is a bug that is forcing the code to run median BG subtraction.  Erin also reported that BG subtraction worked for the tiny dataset when `skip_photom = False`, so that's another wrinkle.

**Comment by taylorbell57** [comment]
@kevin218 so you're saying Erin had no trouble getting proper background subtraction when skip_photom had been set to false, but she also saw error bars that were too small? My best guess would then be that Caroline had (potentially accidentally) changed the background subtraction between the two runs (explaining the differences in the background plots but not the error bars) and the unit conversion from MJy/sr to e-/s in Stage 3 is way off (explaining the error bars but not the background)

**Comment by kevin218** [comment]
@taylorbell57 Sorry, the issue I was referring to was that col-by-col BG subtraction is not working for the full dataset when `skip_photom = False`, but it does work when using the tiny dataset.  Erin and I didn't talk about the size of her error bars.

**Comment by taylorbell57** [comment]
@erinmmay, have you seen my potentially related Issue #99?

**Comment by erinmmay** [comment]
I did see that, it was helpful for the p3/5/7thresh parameters! What I'm finding for the full data set is if I set bg_hw any larger than 7 it doesn't do the column-by-column subtraction. I haven't had a chance to dig into the code but I'm wondering if there's some exception where if there aren't "enough" pixels it defaults to median frame subtraction? But weirdly I **can** get it to work with a larger bg_hw for the tiny data set. Unfortunately with a bg_hw of 7 it's still struggling around 2 micron to properly remove the background. ![fig3101-2D_LC](https://user-images.githubusercontent.com/30506947/156007557-0f64e395-cc93-4b9b-b256-1f87bcd82806.png)

**Comment by taylorbell57** [comment]
Yeah, I think you may get better results if you set the one large threshold even larger. There's very clearly something that's going wrong with NIRSpec though because that one threshold should be nowhere near that large, and for some reason such fragility or errors do not occur for other instruments. I'm getting pretty swamped these days, so I'm going to focus down on MIRI more and I'll unsub from this thread, but at me here if you want to get my attention

**Comment by taylorbell57** [comment]
I think this issue ended up being some subset of other issues that have already been addressed, and I don't think this issue still exists. I'm closing this issue for now, but if anyone objects to that, then we can reopen the issue
