### ISSUE TITLE
Add option to fit single point scatter in the light curves in S5

### ISSUE THREAD

**Issue by cpiaulet** [kevin218/Eureka#124]

**Comment by cpiaulet** [comment]
@taylorbell57 we discussed how it would be good to add this feature to the code - I don't know how far along you were on that but I had understood you did not implement it yet. I just submitted a pull request containing this as well as other minor fixes.

**Comment by taylorbell57** [comment]
Glad you got to this! I hadn't started at all and wouldn't have for some time
