### ISSUE TITLE
AttributeError: 'PolynomialModel' object has no attribute 'longparamlist'

### ISSUE THREAD

**Issue by jbrande** [kevin218/Eureka#129]
On a clean install of Eureka (48c0443), when running S5 with the polynomial model specified, the fitting steps fail because the PolynomialModel is missing the attribute 'longparamlist'. This attribute is present in TransitModel, but didn't make it over to the PolynomialModel yet.

**Comment by taylorbell57** [comment]
Can you explain more where this error is coming up? I can see that longparamlist isn't in the PolynomialModel, but I don't know why it would need to be or what would throw an error

**Comment by taylorbell57** [comment]
Never mind, I see how it could be an issue and it was an easy fix
