### ISSUE TITLE
change format of Parameters object

### ISSUE THREAD

**Issue by lkreidberg** [kevin218/Eureka#13]
currently, new parameters are added to the Parameters instance like this:

params.a = wasp107b_par['a/Rs'], 'free', 10., 25.

Then, in fitters.py, we access the atrributes like this:
if param[1] == 'free': ...

This is risky!! what happens if the attributes are entered out of order? I suggest reformatting this to make it more fool-proof

**Comment by kevin218** [comment]
I agree that the current implementation is risky.  Perhaps a dictionary would be better.

**Comment by taylorbell57** [comment]
@meganmansfield's most recent PR (#75) moves this to a eureka control file which is a solid step forward. Is it still worth making this import scheme more robust to human error? One fairly simple way forward could be to have assert statements, but a dictionary like Kevin mentioned might be an even cleaner way forward (although potentially more work to read in from the ecf, depending on how the readECF file is currently written)

**Comment by taylorbell57** [comment]
Is this something we still want to consider, or are we happy with the way things currently work in Stage 5?

**Comment by lkreidberg** [comment]
we are happy with Stage 5!
