### ISSUE TITLE
Bad Memory leak on MacOS in Stage 3 plotting

### ISSUE THREAD

**Issue by erinmmay** [kevin218/Eureka#142]
On MacOS (maybe other operating systems as well), explicitly calling plt.close() on a figure you've given a numerical identifier to does not release all memory. plt.close(#) does not work either. When the figure is regenerated for the next integration, it does not then grab that same memory because the plot is technically "closed". I was at 60GB of leaked memory when I noticed it!

The fix is unexpectedly to not close the plot, but let it be written over in the next iteration. It won't let me attach the modified .py file, but the solution is to remove the plt.close() line(s) and explicitly clear the figure as you call it:

<img width="829" alt="Screen Shot 2022-02-24 at 8 29 57 AM" src="https://user-images.githubusercontent.com/30506947/155533262-e054be4c-77ee-4ea3-bc4f-5811f48770c1.png">

**Comment by taylorbell57** [comment]
Memory leaks are a known and frustrating part of matplotlib it seems (e.g. [link](https://stackoverflow.com/questions/28757348/how-to-clear-memory-completely-of-all-matplotlib-plots)). I just ran some simple memory tests using the `process.memory_info().rss` command from that link, and for me simply adding a `plt.clf()` before the `plt.close()` without any other changes freed up almost all of the memory. Can you test that out and see if that works for you?

**Comment by erinmmay** [comment]
Yep, I did try that when I was running the tests. That frees up most of the memory, but not all, and it still builds up over the many thousands of plots. The option above has zero memory leak though.

**Comment by taylorbell57** [comment]
Strange, in my simple little test case (just plotting a straight line with 10,000 points 100 times over) I still find a memory leak with your method and find that it is twice as large as with the one I'd suggested

**Comment by taylorbell57** [comment]
Also, did you include that particular function just as an example? Because that function should only be called once and shouldn't itself be the issue, right?

**Comment by erinmmay** [comment]
That's just an example, I changed all of the stage 3 plotting, I just can't upload the file. What version of python and OS are you on?

**Comment by taylorbell57** [comment]
Python 3.9.7, macOS 11.6.4

**Comment by erinmmay** [comment]
Also Python 3.9.7, but macOS 10.15.7

Which is weird because that link you sent (which is what I was using yesterday) says plt.clf() doesn't work on Big Sur to fix the leaks.

**Comment by erinmmay** [comment]
Did you make the change to the plt.figure() call as well? When I run with this version of the plots_S3 it never uses more than 3.5 GB for the entire stage 3 run. Anything else it QUICKLY adds up when it generates plots.

**Comment by taylorbell57** [comment]
Well this is strange, I get a different amount of memory leakage depending on whether I'm using Jupyter notebooks or calling python on a .py file.... Looking into this more

**Comment by erinmmay** [comment]
Yeah, I'm pretty sure Jupyter handles plotting memory differently if you're displaying inline

**Comment by taylorbell57** [comment]
Hahaha well now I get that my method has twice as large a memory leak as yours and mine scales much worse than yours, but I do find that both leak and get worse with more plots. Do you want to make a PR related to this with those changes to the plotting functions?

**Comment by taylorbell57** [comment]
To be clear, for 100 plots your method gives me 25 MB of leak and for 1000 plots 44 MB of leak when calling from the command line. For my method I get 47 MB and 341 MB

**Comment by erinmmay** [comment]
Yeah, I can open a PR. Kevin had just asked me to open it as an issue, hence this.

And that's probably why I don't even notice it as a leak anymore when I'm tracking the memory usage over the run. It probably builds up more with the full imshow plots instead of just the lines you said you're testing on - explaining how I got to over 60 GB before the Image + Background plots even finished before!
