### ISSUE TITLE
New scatter_ppm parameter does not work with shared fits

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#151]
As of right now the new scatter_ppm parameter in Stage 5 introduced in PR #131 does not work properly for shared fits. Only the scatter_ppm parameter gets used for all wavelengths while the scatter_ppm_# parameters are ignored.

**Comment by cpiaulet** [comment]
Thanks for flagging this @taylorbell57 ! I just made the changes on my branch to fix this, I'll run proper testing and open a PR. Sorry for the inconvenience!
