### ISSUE TITLE
Have analyses print MAD value to terminal

### ISSUE THREAD

**Issue by iancrossfield** [kevin218/Eureka#154]
When optimizing the analysis parameters, it can be tedious to individually open the output figures for each analysis session to see how things worked out. To slightly streamline things: why not just print the MAD value to the terminal as each run concludes? E.g., something like:
> MAD for this run: 1234 ppm
> Total time (min): 0.04
> Saving results as astropy table
> Generating figure
> Saving Metadata

**Comment by kevin218** [comment]
While we're at it, we should also make the MAD calculation robust against NaNs. I hope this will address #155.
