### ISSUE TITLE
MAD Calculation Fails for some S3 Runs

### ISSUE THREAD

**Issue by jbrande** [kevin218/Eureka#155]
For some not quite predictable reasons, the MAD calculation for S3 will fail and give some obviously incorrect, massively negative value.

Compare these two S3 plots:
![nirspec_mad_reasonable](https://user-images.githubusercontent.com/5041139/156267852-4cc89b3e-61f0-40e5-a7d9-68a0f6470066.jpg)
![nirspec_mad](https://user-images.githubusercontent.com/5041139/156267862-8eaafc9d-f059-4dfa-96d5-a00669d0314c.jpg)

This doesn't seem to happen with the S4 MAD calculation that I've noticed. I can tell that the calculation in plots_s3.py and plots_s4.py are slightly different, but not whether this could be the cause of the issue.

**Comment by taylorbell57** [comment]
Well apparently this issue also happens sometimes in Stage 4 (see the plot below made using the code from tjb_current, aka the code as of commit 209e41fd1d5b44829d74b9dda22072df77e22ffa). Looking at the figure, it seems there's a line of NaNs (or more likely mased values) at very low integration numbers - these would have been clipped in Stage 4 as they were strong outliers. I guess we need to make sure we're using np.nanmedian or np.ma.median and functions like those in Stage 4 as well (@kevin218 do you do this in PR #199?).

![fig4102-2D_LC](https://user-images.githubusercontent.com/24514122/159540341-228111cd-776e-45ff-bc26-99676389164c.png)

**Comment by kevin218** [comment]
I did not use masked arrays, but we should.  After some discussions, I think the right path forward is to breakout the MAD calculation into a separate function in the lib directory.  The Stage 3/4 codes can then call the same subroutine.  Note, the results can be different between Stage 3/4 if the wavelength edges are provided.

**Comment by taylorbell57** [comment]
The recent PR #229 fixed my S4 MAD calculations, so I'm pretty confident this was an issue with NaN masking which is now handled, so I'm closing this issue now
