### ISSUE TITLE
Always make figure 4101

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#161]
Figure 4101 is a really helpful figure even when no drift correction has been made as it shows where wavelength bins have been placed. I think ideally this figure should always be made, but it currently is only made if drift correction is performed.

**Comment by kevin218** [comment]
Agreed. I'll take this on tomorrow or Friday.

**Comment by taylorbell57** [comment]
I already have a tweak made in my draft PR #160 - I'll likely submit that for review fairly early tomorrow
