### ISSUE TITLE
SRCYPOS Estimated Incorrectly (jwst==1.4.2)

### ISSUE THREAD

**Issue by AarynnCarter** [kevin218/Eureka#165]
Okay I've spent the better part of the day looking at the error I had on Tuesday and I'm a little stumped, but have made some progress. 

```
  File "/Users/acarter/Documents/TRANSITS/EUREKA/DC_NIRSPEC/../Eureka_dev/eureka/S3_data_reduction/background.py", line 171, in fitbg
    print(np.where(mask[j,xvals]))

IndexError: index 30 is out of bounds for axis 1 with size 30 
```

The crash occurs during the background subtraction, and I've realised this is because a dodgy SRCYPOS value of ~221 is being used to create the xvals array, when it should probably be in the range of 0-31. The weird thing is that I cannot find out where this value is being set. I've grepped the string in both Eureka and my site-packages folders and I can only find instances where it's called.

When I made the Stage 2 data for the data challenge, I used the default pipeline process and the SRCXPOS/SRCYPOS values are *not* in the SCI header. So we're probably doing something in Eureka slightly differently? That or my .ecf file isn't set up right. 

@taylorbell57 I would greatly appreciate if you could quickly run Stage 2/3 with the .ecf files I've attached and let me know whether you get a similar error / the SRCYPOS value ends up in the header of your calints file. 

I'm going to reach out to Erin and see if she'll share her Stage 2 .ecf file with me too.  

[ecfs.zip](https://github.com/kevin218/Eureka/files/8182201/ecfs.zip)

**Comment by taylorbell57** [comment]
Huh, so you're saying that eureka's S2 pipeline is making a SRCYPOS value in the FITS header that your separate jwst stage 2 pipeline attempts did not add? Have you looked at the actual output S2 FITS files to confirm that SRCYPOS is actually in there and not something that is going wrong with the methods we wrote to get the source position in Stage 3? I definitely didn't intentionally change anything in the S2 code that would determine the SRCYPOS, but I suppose it's possible that something went wrong. Or perhaps it is related to the slit_y_high, slit_y_low, etc. parameters that you wrote code to edit?

**Comment by AarynnCarter** [comment]
Okay, sorry to leave this for so untouched for so long. I ran things with the slit_y / wavelength parameters set to the default (None) and still get this issue...

@taylorbell57 or @erinmmay, could you send over a copy of your anaconda environment? Maybe it's an issue with my package versions(conda env export > environment.yml). Thanks!

**Comment by taylorbell57** [comment]
As requested, here is my environment (needed to zip for GitHub): [environment.yml.zip](https://github.com/kevin218/Eureka/files/8269876/environment.yml.zip)

**Comment by AarynnCarter** [comment]
Success! Looks like I mistakenly updated my jwst version to 1.4.2 instead of keeping it at 1.3.3. Given we can't stay on jwst 1.3.3 forever, I'm not going to close the issue. 

Separately, it's going to take some serious digging to find out a) where this is happening, and b) whether it will actually be an issue for the real data. I've already grepped my conda environment directory and there's nowhere obvious where SRCXPOS/SRCYPOS are being set.

**Comment by taylorbell57** [comment]
The main reason we couldn't update the `jwst` version before is that newer versions of the `jwst` pipeline broke for the NIRSpec simulations. I found that this could be quickly resolved by allowing the value in the FITS header to be overridden using the `source_pos` function which already exists (PR #373). Previously, if the FITS header had a SRCYPOS value, you had to use it, but now that behaviour is only the case if `meta.source_pos_type='header'`. Moving forward, I think if we want to use the SRCYPOS value with subarray observations it's possible we might need to account for the subarray offset, but I'm not sure if that's the case or if this is just an artifact from the simulated data. I've noted this here for now, and if we don't see this SRCYPOS issue with `meta.source_pos_type='header'` for real data then we can close this issue, or if we do still see this issue then we can look into things like subarray offsets.
