### ISSUE TITLE
Old warning about EXOCTK_DATA environment variable

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#177]
Currently there is a warning message that displays every time I run a stage in Eureka which warns that the EXOCTK_DATA environment variable is not set but notes that this is only important for Stage 5. As of right now, there is nothing at all in Stage 5 that needs anything from ExoCTK - @kevin218 is there something we want to be adding from ExoCTK, or can we remove this warning?

**Comment by kevin218** [comment]
Let's remove the warning
