### ISSUE TITLE
Emcee results should report both mean and standard deviation

### ISSUE THREAD

**Issue by jbrande** [kevin218/Eureka#178]
Currently S5 only logs the fitted mean values for the transit and systematics parameters when running emcee (and also probably dynesty but I haven't checked yet). It should also log the std. dev. 

Here's the current behavior:
`
        emcee results:
	rp: 0.14153307433801648
	per: 4.049990032564156
	t0: 0.5243916471451695
	inc: 90.97563466956603
	a: 11.451196053652133
	u1: 0.9949196696050903
	u2: 0.0008263510695110388
	c0: 1.0145641651118378
	c1: 0.002567429765036567
`

And it should probably be something like:
`
        emcee results:
	rp: 0.14153307433801648 +/ X.XXXX
	per: 4.049990032564156 +/ X.XXXX
	t0: 0.5243916471451695 +/ X.XXXX
`

**Comment by taylorbell57** [comment]
Relatedly, it'd be beneficial to add those details to the fitparams csv. I'd go with the 16th and 84th percentiles rather than the standard deviation though as the distributions can be quite skewed
