### ISSUE TITLE
S4 wave_min and wave_max option for using full S3 extracted region

### ISSUE THREAD

**Issue by meganmansfield** [kevin218/Eureka#182]
It would be nice if instead of defining specific wave_min and wave_max in the S4 .ecf file you could say something like 'full' and then wave_min/wave_max would just be set to the minimum/maximum wavelength value for the subarray region defined in S3.

**Comment by taylorbell57** [comment]
One of my PRs already warns users that their wave_min and wave_max are outside of the wavelength range of the data, so once that's merged in it should be easy to implement this idea

**Comment by meganmansfield** [comment]
Perfect!

**Comment by kevin218** [comment]
This could be the default behavior when wave_min and max are not given
