### ISSUE TITLE
Add explanation on CRDS variables for Macbooks

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#195]
Any current description about CRDS is a bit limited and would be better if we made things more explicitly clear for Mac users (e.g. mention .zshrc etc.)

**Comment by taylorbell57** [comment]
@jbrande In addition to the change you made about .zshrc, we should also explain what the CRDS_PATH should be. Several people have been confused as to where they are supposed to find this path, not realizing that this is a folder they should make somewhere useful to them to store the outputs. Since this same variable/folder is used by both HST and JWST, I recommend putting it somewhere in your home directory (e.g. /Users/tbell1/crds_cache for me on Mac, /home/tbell1/crds_cache for me on Ubuntu)

**Comment by jbrande** [comment]
Got it. I'll make another update there.
