### ISSUE TITLE
Astropy Version Mismatch

### ISSUE THREAD

**Issue by riobanerjee** [kevin218/Eureka#197]
I cloned the repository and used pip install . with a fresh conda environment (Python version: 3.10.0). Upon doing it, near the end of the installation process, this error was thrown:
```
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of asdf to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of eureka to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install Eureka and eureka==0.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    eureka 0.0.1 depends on astropy<5.0.0
    jwst 1.3.3 depends on astropy>=4.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by taylorbell57** [comment]
Well that's strange - those two requirements are not in contradiction since astropy==4.1 would be >=4.1 and <5.0.0...

**Comment by riobanerjee** [comment]
Yes exactly. I don't know why it thinks that's an error. Anyway, installing an astropy version within these bounds separately (after removing the astropy line from requirements.txt) resolved it.

**Comment by taylorbell57** [comment]
I'm honestly not sure why we have the <5.0.0 in there - I'll try looking into this to see if that still needs to be there

**Comment by taylorbell57** [comment]
@afeinstein20 I see that it was you that added the requirement for astropy<5.0.0 - can you clarify why you added that restriction? Is this something we can remove now?

**Comment by taylorbell57** [comment]
Interesting, so this isn't even an issue with anything Eureka related - astropy==4.3.1 just does not behave with python==3.10.0... Talking with Adina though it seems that the <5.0.0 requirement isn't valid anymore so we should be fine to remove it. I'll make a PR to do so now
