### ISSUE TITLE
lsq does not output txt result

### ISSUE THREAD

**Issue by cpiaulet** [kevin218/Eureka#198]
Laura Flagg made me realize that when running lsq there is no txt file output in the results directory

**Comment by lauraflagg** [comment]
I only get Meta_Save.dat for stage 4 (plus the .log and .ecf).  I'm honestly not sure what I'm supposed to get.  I would think I'd get something along the lines of flux versus time and wavelength that I could plot, but I don't.  For stage_5, I'm now getting fitparams_shared.csv, so I can pull the rp/rs from that, but Caroline seemed to have a file with just that.

**Comment by taylorbell57** [comment]
Ah yes, that is something I added to my currently under-review pull request (https://github.com/kevin218/Eureka/pull/190). The needed data is saved in the Meta_Save.dat file, but with my new PR it'll also be saved as a csv you can plot.
