### ISSUE TITLE
Documentation!!!

### ISSUE THREAD

**Issue by kevin218** [kevin218/Eureka#2]
Get ReadTheDocs running

**Comment by sebastian-zieba** [comment]
Hi Kevin,
I believe for the automatic updates of the documentation to work, you have to go to the Eureka! repository **Settings** on GitHub.  Then: "**Webhooks**" and "**add webhook**". Use the following settings then:

- Payload URL: readthedocs.org/api/v2/webhook/eurekadocs/156602/
- Content type: application/json
- Leave the Secrets field blank
- Select Let me select individual events
- The following will determine which actions will update the ReadTheDocs. The ReadTheDocs documentation recommends: marking Branch or tag creation, Branch or tag deletion and Pushes events
- Ensure Active is enabled; it is by default
- Finish by clicking Add webhook. You may be prompted to enter your GitHub password to confirm your action.

**Comment by kevin218** [comment]
Ok, I followed your instructions.  Let's hope that works.

**Comment by sebastian-zieba** [comment]
Do you have any documentation on the optimal extraction parameters (like p5thresh, p7thresh, ...) by any chance? I would like to have more about them in the docs (https://eurekadocs.readthedocs.io/en/latest/ecf.html#p5thresh). Right now I am just referencing the function (optspex.optimize) but that one also doesn't really introduce the parameters.

**Comment by kevin218** [comment]
These are sigma thresholds or cutoffs, using the optimal spectrum extraction algorithm by Horne (1986).

**Comment by kevin218** [comment]
'fittype' defines the method for determining the weighting profile. optspex.py lists the available options (smooth, meddata, wavelet, gauss, polynomial).  
Other parameters are used within specific weighting routines.  'window_len' is the smoothing length scale.

**Comment by taylorbell57** [comment]
Hi all, I was thinking that setting up an automated API like I did [here](https://bell-ebm.readthedocs.io/en/v1.3/Bell_EBM.html) might be a nice way of ensuring the Python files are well documented and that the same documentation is also present on the readthedocs website. There is an automated program which makes these docs called [Sphinx](https://www.sphinx-doc.org/en/master/) (along with many others, but I'm familiar with Sphinx). This won't cover the documentation for everything (especially the ecf files which Sphinx won't be able to handle), but it does save a lot of duplicated effort and maintenance work. What are your thoughts?

**Comment by kevin218** [comment]
The plan is to integrate WFC3 data reduction into Eureka. I'm getting some HST money to do just that, but haven't started yet.

**Comment by kevin218** [comment]
Let's add Adina to the list.  We will likely have additional contributors down the road, so we'll have to remember to update the list periodically.  

As for the order, we could sort by a number of different options: alphabetically, # of commits, net lines contributed, etc.  It should be up to the team to decide.

**Comment by taylorbell57** [comment]
Okay, I've added Adina now. For the time being, perhaps I'll sort alphabetically by first name and we can discuss the ordering at our next meeting in two weeks?

**Comment by AarynnCarter** [comment]
@kevin218 This issue is pretty stale now, shall we close it and move towards splitting up specific documentation bugs / enhancements with Megan's new template?

**Comment by kevin218** [comment]
Yeah, let's do that
