### ISSUE TITLE
Sinusoid phase curve model is not checking for 0 eccentricity appropriately

### ISSUE THREAD

**Issue by lcmayor** [kevin218/Eureka#202]
`self.parameters.dict['ecc']` is a list in which the first item is the actually eccentricity.

Thus line should read: `if self.parameters.dict['ecc'][0] == 0.:` instead of:
https://github.com/kevin218/Eureka/blob/ed7ebabd76d4b45d56046b75dcac42c8094c556c/eureka/S5_lightcurve_fitting/models/SinusoidPhaseCurve.py#L96

**Comment by lcmayor** [comment]
This is also true for period in this section:

https://github.com/kevin218/Eureka/blob/ed7ebabd76d4b45d56046b75dcac42c8094c556c/eureka/S5_lightcurve_fitting/models/SinusoidPhaseCurve.py#L99

**Comment by taylorbell57** [comment]
Would you like me to make these tweaks, or do you want to open your own pull request for this?

**Comment by lcmayor** [comment]
I don't think I have PR permissions so go ahead.

**Comment by taylorbell57** [comment]
Sure, will do - in the future though, you can fork the repo and then submit a PR from your repo into kevin218:main
