### ISSUE TITLE
When fitting sinusoidphase curve the 2nt-nth channels do not change parameters.

### ISSUE THREAD

**Issue by lcmayor** [kevin218/Eureka#206]
The sinusoid phase curve model is bugged in that the first model adjusts the ampcos/ampsin parameters, but the 2nd channel onwards are all stuck at the same value.

**Comment by lcmayor** [comment]
The issue arises from here: https://github.com/kevin218/Eureka/blob/a09ad02a1d6233db52fa2b2848bb6255957fd0d1/eureka/S5_lightcurve_fitting/models/SinusoidPhaseCurve.py#L80

The first channel is sent as AmpCos1, AmpSin1, etc. The following channels are AmpCos1_1, AmpSin1_1 and so they aren't in the pc_params.keys(). Possible solution is to check if the item.split('_')[0] is in pc_params.keys()?

**Comment by taylorbell57** [comment]
Changing that if item line to the following fixes the bug. I can open a PR with this tweak soon.

`if np.any([key in item for key in pc_params.keys()]):`
