### ISSUE TITLE
Stage 5 using SinusoidPhaseCurve leads to AttributeError: 'NoneType' object has no attribute 'get_true_anomaly'

### ISSUE THREAD

**Issue by sebastian-zieba** [kevin218/Eureka#207]
When running Stage 5 and including a sinusoid phase curve, I and others encountered the following error message coming from line 107 in **eureka/S5_lightcurve_fitting/models/SinusoidPhaseCurve.py**: 
_AttributeError: 'NoneType' object has no attribute 'get_true_anomaly'_

It looks like m_transit is None when I am running the fit which leads to this error.

I changed the "if m_transit is not None:" in line 102 to "if m_transit is None:" and it works.
Is this just a typo or am I missing something?

**Comment by kevin218** [comment]
Do you include the BATMAN eclipse model in your ecf?

**Comment by sebastian-zieba** [comment]
Yes, 

my run_myfuncs is:  [batman_tr,sinusoid_pc,batman_ecl,expramp,polynomial] 

And my fit values from the fit_par file are:

#BATMAN TRANSIT
rp			0.18			'free'		0.15		0.2				U
per			0.7668944		'free'			0.76		    0.78		    U
t0   		        0.525	    'free'			0.4		0.6		U
time_offset	0				'independent'
inc  		        80.109	 		'free'			75.			85			U
a    		4.45			'free'			4.447			0.13			N
ecc  		0.0	 			'fixed' 		0 				1				U
w    		90.				'fixed' 		0 				180				U
limb_dark	'quadratic' 	'independent'
u1			0.3				'free'			-1				1				U
u2			0.1				'free'			-1				1				U
transittype	'primary'	 	'independent'

#CONSTANT
c0			1.009			'free'			0.95			1.05			U

#BATMAN ECLIPSE
fp          0.01           'free'			0.			    1			U
t_secondary 0.1        'free'			0			0.2			U

#EXPRAMP
r0          -1        'free'			-10			-0.1			U
r1          6        'free'			0.			20			U
r2          -4.5        'free'			-8			0			U
r3          0        'fixed'			0			0.2			U
r4          0        'fixed'			0			0.2			U
r5          0        'fixed'			0			0.2			U

#SINCOS
AmpSin1     1e-2  'free'			0			1			U
AmpCos1     1e-2  'free'			0			1.			U
AmpCos2     0  'fixed'			0			0			U
AmpSin2     0  'fixed'			0			0.			U

**Comment by sebastian-zieba** [comment]
Oh, if one does a transit and an eclipse, do they actually need
_transittype 'primary' 'independent'_
AND
_transittype 'secondary' 'independent'_?

**Comment by lcmayor** [comment]
This issue arises because of https://github.com/kevin218/Eureka/issues/202.
It's not doing the eccentricity check correctly so it jumps down to do the elliptical orbit check.
