### ISSUE TITLE
Add a list of models and parameters to the documentation

### ISSUE THREAD

**Issue by sebastian-zieba** [kevin218/Eureka#209]
Having a list of currently available models and the respective free parameters in the documentation would make it easier for new users to get started with Stage 5.
I have something similar like this for PACMAN (an HST pipeline). See here: https://pacmandocs.readthedocs.io/en/latest/models.html

**Comment by jbrande** [comment]
Yeah, we still don't have anything on Stage 5 at all, so I'll start working on that.
