### ISSUE TITLE
mask data points in S5 fitting

### ISSUE THREAD

**Issue by lkreidberg** [kevin218/Eureka#219]
It would be great to add a parameter to the Stage 5 ecf file that lists a range of points that should be masked in the fit.

The format could be something like ``mask_points = [[a,b], [x,y]]`` (to mask points on the ranges a- b  and x-y)

This would be particularly helpful for masking the very steep ramp at the beginning of the observations, for example

**Comment by kevin218** [comment]
POET has a good implementation for this using preclip, postclip, and interactive. Making this general, as Laura suggests, would be good.

**Comment by taylorbell57** [comment]
This is now implemented in Stage 5 with PRs #420 and #449 with the addition of `manual_clip` to the S5 ECF.
