### ISSUE TITLE
add explanations for diagnostic plots to documentation

### ISSUE THREAD

**Issue by lkreidberg** [kevin218/Eureka#220]
We should document what all the different diagnostic plots are!

**Comment by taylorbell57** [comment]
Do you mean something like what Yoni added for Stage 5 in the ECF documentation webpage? Or something more than that?

**Comment by lkreidberg** [comment]
oh I didn't even see that! yeah this is basically what I had in mind.

I think it could be a useful to add a new *rst to the docs on outputs from each stage, to make it easier to find - any thoughts on that?

**Comment by taylorbell57** [comment]
That seems very reasonable and would help to reduce the amount of text in that ecf rst file

**Comment by jbrande** [comment]
@taylorbell57 @lkreidberg I'm in and out of other meetings today but I can handle that.
