### ISSUE TITLE
Stage 3 ASDF attribute error loading S2 files

### ISSUE THREAD

**Issue by evamariaa** [kevin218/Eureka#221]
Running Stage 3 on the JWST Data Challenge NIRCam Stage 2 data I get the following error:

> File "/storage/astro2/phrgmk/Eureka pipeline/run_eureka_S3.py", line 9, in <module>
>     s3_meta = s3.reduceJWST(eventlabel)
>   File "/home/astro/phrgmk/.local/lib/python3.9/site-packages/Eureka-0.0.1-py3.9-linux-x86_64.egg/eureka/S3_data_reduction/s3_reduce.py", line 221, in reduceJWST
>   File "/home/astro/phrgmk/.local/lib/python3.9/site-packages/Eureka-0.0.1-py3.9-linux-x86_64.egg/eureka/S3_data_reduction/bright2flux.py", line 198, in convert_to_e
>   File "/home/astro/phrgmk/.local/lib/python3.9/site-packages/Eureka-0.0.1-py3.9-linux-x86_64.egg/eureka/S3_data_reduction/bright2flux.py", line 241, in retrieve_ancil
>   File "/home/astro/phrgmk/.local/lib/python3.9/site-packages/jwst/datamodels/util.py", line 198, in open
>     model = new_class(init, **kwargs)
>   File "/home/astro/phrgmk/.local/lib/python3.9/site-packages/jwst/datamodels/slit.py", line 160, in __init__
>     super(SlitModel, self).__init__(init=init, **kwargs)
>   File "/home/astro/phrgmk/.conda/envs/ers-transit/lib/python3.9/site-packages/stdatamodels/model_base.py", line 215, in __init__
>     asdffile = fits_support.from_fits(init, self._schema, self._ctx,
>   File "/home/astro/phrgmk/.conda/envs/ers-transit/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 604, in from_fits
>     raise exc.__class__("ERROR loading embedded ASDF: " + str(exc)) from exc
> AttributeError: ERROR loading embedded ASDF: 'TaggedDict' object has no attribute 'frame'

I get a similar error when just running datamodels.open('*calints.fits').

**Comment by taylorbell57** [comment]
Well that is very disturbing and strange... Did you run the Stage 2 yourself, or are you using the files uploaded to the Box? Did you not get this with an older version of Eureka and just started getting this?

**Comment by evamariaa** [comment]
I've been using Stage 2 by the Box and yes, I starting getting that error after cloning the most recent Eureka version. I also made a whole new conda environment which only has Eureka installed to check whether there wasn't another package or sth that caused it.

**Comment by evamariaa** [comment]
Stage 1 didn't work either BUT I found the solution to my issue:
Seems like the new conda environment still accessed eureka from my previous conda environment (see ers-transit env in error message), wasn't aware that this could happend. I assume that there were some requirements/packages problems in that conda environment as the eureka installation is the equivalent but the environment isn't. 
In the end removing the other environment and installing eureka from scratch solved this issue!
Thank you Kevin for mentioning something like that in the DC Eureka Q&A session just now that gave me the idea to check this!

**Comment by taylorbell57** [comment]
Huh, that is very strange - I wonder if that is related to the issues that some others had with batman vs batman-package. Either way, seems more like a conda/pip issue than a Eureka issue
