### ISSUE TITLE
No uncertainties in the Stage 5 outputs

### ISSUE THREAD

**Issue by Saugata500** [kevin218/Eureka#222]
After running Stage 5, i notice that the best fit parameter for each spectroscopic channel is printed out in the .csv files, however the uncertainties on these parameters are not. I amusing the 'lsq' method. As a result the spectral visualization also does not have errorbars on the transmission spectrum.
![fig6301](https://user-images.githubusercontent.com/75619404/159695317-9e251eb9-cc25-40c4-b6a6-f93f49a14ff7.png)

**Comment by taylorbell57** [comment]
Yes, this is a known flaw. Least squares fitters do not give a good estimate of the uncertainty, so you should use emcee or dynesty to get uncertainties
