### ISSUE TITLE
add a eureka-lite install option

### ISSUE THREAD

**Issue by lkreidberg** [kevin218/Eureka#237]
This would be an optional install that works for S4 - S6 (so that users aren't completely stuck if they fail to install the jwst pipeline)

**Comment by taylorbell57** [comment]
I'll try to make a `pip install . [nojwst]` command work to allow no jwst installation if desired/needed

**Comment by taylorbell57** [comment]
Ahh, so it seems like there are quite a few people on the internet who want a command like `pip install .[nojwst]` to work, but as of right now there is no way to have optional dependencies that are installed by default. In other words, the only way we can make jwst optional is by having `pip install .` install Eureka _without_ jwst and `pip install .[jwst]` install Eureka _with_ jwst. It's possible I could hack something together to make jwst something that is opt-out, but if we ever publish our code on PyPI then optional packages like jwst need to be opt-in instead. My worry with leaving jwst as opt-in is that people would just do `pip install .` (or `pip install eureka-pipeline` once we're hosted on PyPI) without reading the documentation to know to add `[jwst]`and then get confused/frustrated as to why Stages 1 and 2 don't work. What do you all think (e.g. @lkreidberg, @kevin218)?

**Comment by taylorbell57** [comment]
One other option (and the one that seems to be recommended at this time to have opt-out dependencies) is to make 2 packages that would look something like:
1. eureka (this is an empty repo with just a setup.py file which requires eureka-lite and jwst on install)
2. eureka-lite (this is the repo where all of our code resides)
One can then do `pip install eureka` or `pip install eureka-lite` depending on what they want. This would work okay if we were hosting our code on PyPI but would be a pain if people are downloading code from GitHub.

The only other option would be:
1. eureka (installation requires eureka-lite, eureka-core, and jwst; this is the repo where S1-2 code resides)
2. eureka-lite (installation requires eureka-core; this is the repo where all of our S3-6 code resides)
3. eureka-core (this is the repo where all the shared files in the lib folder are stored)
This would be the way we'd have to do things if we really must break eureka into separate repos for Stages 1-2 and Stages 3-6 but still want to avoid having two copies of the lib folders to maintain.

Frankly, I don't like any of these options (including the ones in my previous comment), but I think the best solution might be to make `jwst` and opt-in feature (`pip install .[jwst]`) for the time being if we want to allow eureka to not have jwst as a mandatory requirement. Other options are going to be a real headache imo

**Comment by kevin218** [comment]
The opt-in solution, while not perfect, appears to be th easiest solution for now. Let's go with that route
