### ISSUE TITLE
improve documentation for ecf files

### ISSUE THREAD

**Issue by lkreidberg** [kevin218/Eureka#238]
explain more clearly in the docs what each parameter does, and add a link to the docs at the beginning of each ecf file

**Comment by taylorbell57** [comment]
This was partially addressed with PR #213 which added many of the missing ECF parameters and will be partially addressed by PR #255 which adds a link to the relevant part of the docs to each ECF template. Once those are both merged, we should do a careful read through to make sure that all parameters are explained. I know the settings in the EPF files are currently not explained, but I don't know what others might be missing
