### ISSUE TITLE
explore options to make installation easier

### ISSUE THREAD

**Issue by lkreidberg** [kevin218/Eureka#241]
we discussed docker containers, conda environments, pip environments. others? 

let's make the user experience as painless as possible :)

**Comment by taylorbell57** [comment]
I spent a bit of time yesterday and today investigating how hard/easy it will be to build a conda package for Eureka, and it seems like it will be no simple feat. You can't have any pip-only dependencies which means we'd first need to build conda packages for crds, jwst, myst-parser, sphinx-rtd-theme, stcal, stdatamodels, and svo_filters (and any of their dependencies that are pip-only like pysynphot). While that is doable, it is far from simple and not worthwhile at this point in my opinion. Hosting on pip should be super simple though once we start having releases/tags on GitHub

**Comment by taylorbell57** [comment]
There is also a very annoying bug with conda-build right now (https://github.com/conda/conda-build/issues/4354) that breaks attempts to build things with python > 3.6, so even if we do want to pursue building a conda package we should wait a bit until that gets patched

**Comment by kevin218** [comment]
I'm fine with closing
