### ISSUE TITLE
streamline documentation for installation and quickstart

### ISSUE THREAD

**Issue by lkreidberg** [kevin218/Eureka#242]
These were written with expert users in mind -let's go through these instructions very carefully and make sure that a new user who may be less experienced with github, working on the command line, etc.

**Comment by taylorbell57** [comment]
Installation is hopefully well documented now, but quickstart indeed needs a significant overhaul

**Comment by AarynnCarter** [comment]
@taylorbell57, @lkreidberg I can try to rewrite the quickstart this week if you haven't already started?

**Comment by taylorbell57** [comment]
That'd be awesome - I haven't doing anything there yet
