### ISSUE TITLE
Unused eureka.lib.plots.set_rc() function

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#251]
Related to Issue #250, we made a new function `eureka.lib.plots.set_rc()` a while back, but it never gets called and we don't have any ways specified for users to enter in settings. The best way to do this might be to add a bit of code in the run_eureka.py file since that would then apply to all stages rather than requiring users to copy-paste the same settings to all their ecf files.

**Comment by kevin218** [comment]
This sounds like a straightforward solution.
