### ISSUE TITLE
Renaming of main S1-5 functions

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#256]
As of right now, the main functions of S1-5 have names that end in JWST, but Stages 3-6 are all compatible with HST/WFC3. I suggest we rename the main S1-5 functions to be more general. Suggestions are below

s1.rampfitJWST -> s1.rampfit
s2.calibrateJWST -> s2.calibrate
s3.reduceJWST -> s3.reduce
s4.lcJWST -> s4.getlc
s5.fitJWST -> s5.fit

**Comment by AarynnCarter** [comment]
Looks good to me, my only suggestion would be:

s5.fitJWST -> s5.lcfit

This would keep things explicit so people don't (somehow) assume it's for ramp fitting.

**Comment by kevin218** [comment]
Agreed with Aarynn
