### ISSUE TITLE
Trying to run stage 6

### ISSUE THREAD

**Issue by jovian-explorer** [kevin218/Eureka#263]
keshav@dev:~/Downloads/JWST_Sim/NIRSpec/Stage6$ python3 run_eureka.py 
2022-04-06 00:43:05,650 - stpipe - INFO - Loading KWallet
2022-04-06 00:43:05,653 - stpipe - INFO - Loading SecretService
2022-04-06 00:43:05,657 - stpipe - INFO - Loading Windows
2022-04-06 00:43:05,658 - stpipe - INFO - Loading chainer
2022-04-06 00:43:05,658 - stpipe - INFO - Loading macOS

Starting Stage 6: Light Curve Fitting

WARNING: There are multiple metadata save files in your inputdir: 
"/home/keshav/Downloads/JWST_Sim/NIRSpec/Stage5/"
Using the metadata file: 
/home/keshav/Downloads/JWST_Sim/NIRSpec/Stage5/S5_2022-04-05_wasp39b_ap6_bg7_run1/S5_wasp39b_Meta_Save.dat
and will consider aperture ranges listed there. If this metadata file is not a part
of the run you intended, please provide a more precise folder for the metadata file.
Input directory: /home/keshav/Downloads/JWST_Sim/NIRSpec/Stage5/S5_2022-04-05_wasp39b_ap6_bg7_run1/
Output directory: /home/keshav/Downloads/JWST_Sim/NIRSpec/Stage6/S6_2022-04-06_wasp39b_ap6_bg7_run3/
Copying S6 control file
Traceback (most recent call last):
  File "run_eureka.py", line 28, in <module>
    s6_meta = s6.plot_spectra(eventlabel, ecf_path=ecf_path)
  File "/home/keshav/.local/lib/python3.8/site-packages/eureka/S6_planet_spectra/s6_spectra.py", line 143, in plot_spectra
    median, err = parse_s5_saves(meta, fit_methods, y_param, f'ch{channel}')
  File "/home/keshav/.local/lib/python3.8/site-packages/eureka/S6_planet_spectra/s6_spectra.py", line 261, in parse_s5_saves
    fitted_values = pd.read_csv(meta.inputdir+fname, escapechar='#', skipinitialspace=True)
  File "/home/keshav/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/keshav/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/keshav/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/keshav/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/keshav/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/keshav/.local/lib/python3.8/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/keshav/Downloads/JWST_Sim/NIRSpec/Stage5/S5_2022-04-05_wasp39b_ap6_bg7_run1/S5_dynesty_fitparams_ch5.csv'

**Comment by taylorbell57** [comment]
Can you tell me what are all the filenames in the folder /home/keshav/Downloads/JWST_Sim/NIRSpec/Stage5/S5_2022-04-05_wasp39b_ap6_bg7_run1/

Can you also copy-paste the contents of the Stage 5 ECF that was copied to that folder?

**Comment by jovian-explorer** [comment]
keshav@dev:~/Downloads/JWST_Sim/NIRSpec/Stage5/S5_2022-04-05_wasp39b_ap6_bg7_run1$ ls
figs                          S5_dynesty_samples_ch4.h5
S5_dynesty_fitparams_ch0.csv  S5_fit_par_template.ecf
S5_dynesty_fitparams_ch1.csv  S5_wasp39b_ap6_bg7_Table_Save_ch0.txt
S5_dynesty_fitparams_ch2.csv  S5_wasp39b_ap6_bg7_Table_Save_ch1.txt
S5_dynesty_fitparams_ch3.csv  S5_wasp39b_ap6_bg7_Table_Save_ch2.txt
S5_dynesty_fitparams_ch4.csv  S5_wasp39b_ap6_bg7_Table_Save_ch3.txt
S5_dynesty_samples_ch0.h5     S5_wasp39b_ap6_bg7_Table_Save_ch4.txt
S5_dynesty_samples_ch1.h5     S5_wasp39b.ecf
S5_dynesty_samples_ch2.h5     S5_wasp39b.log
S5_dynesty_samples_ch3.h5     S5_wasp39b_Meta_Save.dat

**Comment by jovian-explorer** [comment]
#Name        Value         Free?          PriorPar1    PriorPar2    PriorType
#PriorType can be U (Uniform), LU (Log Uniform), or N (Normal). If U/LU, PriorPar1 and PriorPar2 represent upper and lower limits of the parameter/log(the parameter). If N, PriorPar1 is the mean and PriorPar2 is the standard deviation of a Gaussian prior.
rp           0.16          'free'         0.05         0.3          U
per          0.813473978   'free'         0.813473978  0.000000035  N
t0           55528.353027  'free'         55528.34     55528.36     U
time_offset  0             'independent'
inc          82.109        'free'         82.109       0.088        N
a            4.97          'free'         4.97         0.14         N
ecc          0.0           'fixed'        0            1            U
w            90.           'fixed'        0            180          U
limb_dark    'kipping2013'   'independent'
u1           0.3           'free'         0            1            U
u2           0.1           'free'         0            1            U
c0           1             'free'         0.95         1.05         U

**Comment by jovian-explorer** [comment]
`#Name        Value         Free?          PriorPar1    PriorPar2    PriorType
#PriorType can be U (Uniform), LU (Log Uniform), or N (Normal). If U/LU, PriorPar1 and PriorPar2 represent upper and lower limits of the parameter/log(the parameter). If N, PriorPar1 is the mean and PriorPar2 is the standard deviation of a Gaussian prior.
rp           0.16          'free'         0.05         0.3          U
per          0.813473978   'free'         0.813473978  0.000000035  N
t0           55528.353027  'free'         55528.34     55528.36     U
time_offset  0             'independent'
inc          82.109        'free'         82.109       0.088        N
a            4.97          'free'         4.97         0.14         N
ecc          0.0           'fixed'        0            1            U
w            90.           'fixed'        0            180          U
limb_dark    'kipping2013'   'independent'
u1           0.3           'free'         0            1            U
u2           0.1           'free'         0            1            U
c0           1             'free'         0.95         1.05         U`

**Comment by jovian-explorer** [comment]
# Eureka! Control File for Stage 5: Lightcurve Fitting

ncpu            1 # The number of CPU threads to use when running emcee or dynesty in parallel

allapers        True                    # Run S5 on all of the apertures considered in S4? Otherwise will use newest output in the inputdir
rescale_err     False                   # Rescale uncertainties to have reduced chi-squared of unity
fit_par         ./S5_fit_par_template.ecf   # What fitting ecf do you want to use?
verbose         True                    # If True, more details will be printed about steps
fit_method      [dynesty]               #options are: lsq, emcee, dynesty (can list multiple types separated by commas)
run_myfuncs     [batman_tr,polynomial]  #options are: batman_tr, batman_ecl, sinusoid_pc, expramp, and polynomial (can list multiple types separated by commas)

# Limb darkening controls (not yet implemented)
#fix_ld          False #use limb darkening file?
#ld_file         /path/to/limbdarkening/ld_outputfile.txt  #location of limb darkening file

#lsq
lsq_method      'Nelder-Mead' # The scipy.optimize.minimize optimization method to use
lsq_tol         1e-6    # The tolerance for the scipy.optimize.minimize optimization method

#mcmc
old_chain       None    # Output folder relative to topdir that contains an old emcee chain to resume where you left off (set to None to start from scratch)
lsq_first       True    # Initialize with an initial lsq call (can help shorten burn-in, but turn off if lsq fails). Only used if old_chain is None
run_nsteps      4000
run_nwalkers    50
run_nburn       2000

#dynesty
run_nlive       1024    # Must be > ndim * (ndim + 1) // 2
run_bound       'multi'
run_sample      'unif'
run_tol         0.1

# Plotting controls
interp          False   # Should astrophysical model be interpolated (useful for uneven sampling like that from HST)

# Diagnostics
isplots_S5      5       # Generate few (1), some (3), or many (5) figures (Options: 1 - 5)
testing_S5      False   # Boolean, set True to only use the first spectral channel
testing_model   False   # Boolean, set True to only inject a model source of systematics
hide_plots      False   # If True, plots will automatically be closed rather than popping up

# Project directory
topdir                  /home/keshav/Downloads/JWST_Sim/NIRSpec

# Directories relative to project dir
inputdir		Stage4/S4_2022-04-01_wasp39b_ap6_bg7_run3/	
outputdir               /Stage5

**Comment by taylorbell57** [comment]
Can you copy-paste the contents of the ECF that was copied to the folder /home/keshav/Downloads/JWST_Sim/NIRSpec/Stage4/S4_2022-04-01_wasp39b_ap6_bg7_run3/

Also, if you downloaded Eureka with git can you tell me the output of `git log -1`

**Comment by taylorbell57** [comment]
Or rather copy-paste the filenames in that folder like you did before

**Comment by jovian-explorer** [comment]
keshav@dev:~/Downloads/JWST_Sim/NIRSpec/Stage4/S4_2022-04-01_wasp39b_ap6_bg7_run3$ ls
figs                               S4_wasp39b.ecf  S4_wasp39b_Meta_Save.dat
S4_wasp39b_ap6_bg7_Table_Save.txt  S4_wasp39b.log

**Comment by jovian-explorer** [comment]
keshav@dev:~/Downloads/JWST_Sim/NIRSpec/Stage6$ git log -1
fatal: not a git repository (or any of the parent directories): .git

**Comment by taylorbell57** [comment]
Can you copy-paste the contents of the ECF file /home/keshav/Downloads/JWST_Sim/NIRSpec/Stage4/S4_2022-04-01_wasp39b_ap6_bg7_run3/S4_wasp39b.ecf

And what instructions did you follow to install Eureka? I'm trying to figure out how old the code version is that you're using

**Comment by jovian-explorer** [comment]
# Eureka! Control File for Stage 4: Generate Lightcurves 

# Number of spectroscopic channels spread evenly over given wavelength range
nspecchan       20          # Number of spectroscopic channels
wave_min        1.0         # Minimum wavelength. Set to None to use the shortest extracted wavelength from Stage 3.
wave_max        5.0         # Maximum wavelength. Set to None to use the longest extracted wavelength from Stage 3.
allapers        True        # Run S4 on all of the apertures considered in S3? Otherwise will use newest output in the inputdir

# Parameters for drift correction of 1D spectra
correctDrift    False   # Set True to correct drift/jitter in 1D spectra (not recommended for simulated data)
drift_preclip   0       # Ignore first drift_preclip points of spectrum
drift_postclip  100     # Ignore last drift_postclip points of spectrum, None = no clipping
drift_range     11      # Trim spectra by +/-X pixels to compute valid region of cross correlation
drift_hw        5       # Half-width in pixels used when fitting Gaussian, must be smaller than drift_range
drift_iref      -1      # Index of reference spectrum used for cross correlation, -1 = last spectrum
sub_mean        True    # Set True to subtract spectrum mean during cross correlation
sub_continuum   True    # Set True to subtract the continuum from the spectra using a highpass filter
highpassWidth   10      # The integer width of the highpass filter when subtracting the continuum

# Parameters for sigma clipping
sigma_clip      False   # Whether or not sigma clipping should be performed on the 1D time series
sigma           10      # The number of sigmas a point must be from the rolling median to be considered an outlier
box_width       10      # The width of the box-car filter (used to calculated the rolling median) in units of number of data points
maxiters        5       # The number of iterations of sigma clipping that should be performed.
fill_value      mask    # Either the string 'mask' to mask the outlier values (recommended), 'boxcar' to replace data with the mean from the box-car filter, or a constant float-type fill value.

# Diagnostics
isplots_S4      3       # Generate few (1), some (3), or many (5) figures (Options: 1 - 5)
hide_plots      False   # If True, plots will automatically be closed rather than popping up
verbose         False   # If True, more details will be printed about steps

# Project directory
topdir          /home/User

# Project directory
topdir                  /home/keshav/Downloads/JWST_Sim/NIRSpec

# Directories relative to project dir
inputdir		//home/keshav/Downloads/JWST_Sim/NIRSpec/Stage3/S3_2022-04-01_wasp39b_ap6_bg7_run2/	
outputdir               /Stage4

**Comment by jovian-explorer** [comment]
I had installed it downloading a zip from the github, around a couple weeks or so

**Comment by taylorbell57** [comment]
Alright, well it seems certain to me that your Stage 5 run was interrupted as it should contain 20 spectral channels but only has 5, and Stage 6 knows that it should have 20 and tries to find them all and breaks when it hits ch5. Either the Stage 5 run crashed or you interrupted it. You can see how far it got by reading the contents of /home/keshav/Downloads/JWST_Sim/NIRSpec/Stage5/S5_2022-04-05_wasp39b_ap6_bg7_run1/S5_wasp39b.log

Either way, this is the expected behaviour given an incomplete Stage 5 run, so I'll now close this issue
