### ISSUE TITLE
[Bug:] Issue setting the correct PATH

### ISSUE THREAD

**Issue by jlibby-roberts** [kevin218/Eureka#266]
### Contact Details

jer5346@psu.edu

### Instrument

NIRSpec (Stages 1-3)

### What happened?

Hi! I was able to successfully install and run Eureka during the ERS hackathon a few weeks ago. However, my undergraduate is running into the error: CRDS - ERROR - (FATAL) CRDS server connection and cache load FAILED. Cannot continue.  See https://hst-crds.stsci.edu/docs/cmdline_bestrefs/ or https://jwst-crds.stsci.edu/docs/cmdline_bestrefs/  for more information on configuring CRDS, particularly CRDS_PATH and CRDS_SERVER_URL. : [Errno 2] No such file or directory: '/grp/crds/cache/config/jwst/server_config'. We have checked that her PATH is set correctly and that everything mirrors my own set-up. I am not sure if this is a bug or if we have missed a step, but we are stuck at this point. Thanks for the help!

### Error traceback output

stpipe.EurekaSpec2Pipeline - INFO - Prefetching reference files for dataset: 'jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_rateints.fits' reftypes = ['apcorr', 'camera', 'collimator', 'disperser', 'distortion', 'drizpars', 'extract1d', 'filteroffset', 'fore', 'fpa', 'ifufore', 'ifupost', 'ifuslicer', 'msa', 'ote', 'pathloss', 'regions', 'specwcs', 'wavecorr', 'wavelengthrange', 'wfssbkg']
2022-04-07 11:27:14,344 - CRDS - ERROR - (FATAL) CRDS server connection and cache load FAILED. Cannot continue.
 See https://hst-crds.stsci.edu/docs/cmdline_bestrefs/ or https://jwst-crds.stsci.edu/docs/cmdline_bestrefs/
 for more information on configuring CRDS, particularly CRDS_PATH and CRDS_SERVER_URL. : [Errno 2] No such file or directory: '/grp/crds/cache/config/jwst/server_config'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
If so, then it's likely just that your student needs to close and reopen the terminal as those edits don't take effect until you open a new terminal or do `source ~/.bashrc` or similar (e.g. `source ~/.zshrc` if you're using zsh on macOS). We should add that clarification to the documentation

**Comment by jlibby-roberts** [comment]
Yes we did try those steps but still receiving this error. I should note that she has to sudo run eureka on her laptop due to permission issues.

**Comment by jlibby-roberts** [comment]
Actually turns out that was the problem. You can't sudo run Eureka. Sorry about that, everything works perfectly now.

**Comment by taylorbell57** [comment]
Ahh well using sudo is almost certainly causing the issue then. For one, using sudo results in a different "user" (root) running the code which almost certainly does not have the environment variables set. There should be no reason to use sudo to run any of the code. It should be run like `python run_eureka.py` which should require no sudo privileges. Also, you should also not be using `sudo python` as that is a different python than just `python` - if you think you need to do `sudo python`, your python setup is almost certainly setup incorrectly.
