### ISSUE TITLE
[Bug]: computeRMS fails to calculate stderr when masked arrays are given.

### ISSUE THREAD

**Issue by jbrande** [kevin218/Eureka#276]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Light curve fitting (Stages 4-6)

### What happened?

After masking outliers in S4, computeRMS in S5 will return an invalid result from np.ma.std(data). This means the stderr returned from computeRMS will also be a masked array of invalid values, and will cause the Allan plot made in S5 to be blank. @taylorbell57 suggests this only happens when all values are masked for a certain bin, but I've only been working with single-bin lightcurves and not all the values have been masked (I did a 10-sigma clipping step in S4, and there was good data there).

Here's a look at a bad Allan plot:
![fig520_allanplot_lsq](https://user-images.githubusercontent.com/5041139/163231822-ed55d664-ffb7-4c6f-badd-8e75a55c6269.png)

And here's a look at a working Allan plot: 
![fig520_allanplot_lsq](https://user-images.githubusercontent.com/5041139/163231915-8a4d341f-fa6f-4fc9-8854-a0e95c282488.png)

The only difference is whether I ran the sigma clipping step in S4. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
What simulated dataset is this for, and what branch is your code up-to-date with?

**Comment by jbrande** [comment]
This was the full NIRSpec dataset, and my code is up to date with main as of this morning.

**Comment by taylorbell57** [comment]
Can you send me your S4's Meta_Save.dat file and S5's .ecf and .epf files by email so I can reproduce the error locally?

**Comment by jbrande** [comment]
Yep. I'll send those when I get out of some meetings.

**Comment by kevin218** [comment]
I encountered a related problem in S5 when flagging outliers in S4. I managed to fix it, but I think we'll continue to see problems like this unless we take the more drastic step of moving away from masked arrays in S5. It should be simple to, at the start of S5, copy all good data points into a new array. At that point, there's no point to keeping the masked data.
