### ISSUE TITLE
[Bug]: Incorrect connecting of directory when passing meta files between stages with different topdir

### ISSUE THREAD

**Issue by AarynnCarter** [kevin218/Eureka#277]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Other (any stage)

### What happened?

If I set up some .ecfs as follows:

**Stage 3:**
```
# Project directory
topdir         /Users/acarter/Documents/TRANSITS/EUREKA

# Directories relative to project dir
inputdir       /QUICKSTART_DATA/Stage2   # The folder containing the outputs from Eureka!'s S2 or JWST's S2 pipeline (will be overwritten if calling S2 and S3 sequentially)
outputdir      /QUICKSTART/Stage3
```

**Stage 4:** 
```
# Project directory
topdir          /Users/acarter/Documents/TRANSITS/EUREKA/QUICKSTART/

# Directories relative to project dir
inputdir        /Stage3    # The folder containing the outputs from Eureka!'s S3 or JWST's S3 pipeline (will be overwritten if calling S3 and S4 sequentially)
outputdir       /Stage4
```

Then when Stage 4 attempts to load in the meta save file it will only look in: `"/Users/acarter/Documents/TRANSITS/EUREKA/QUICKSTART/QUICKSTART/Stage3/S3_2022-04-14_wasp39b_ap8_bg8_run4/"!`

Notice the double QUICKSTART directory (which doesn't exist). This can be fixed quite easily by ensuring topdir is the same between the .ecfs, but maybe we could develop a workaround for this restriction?

### Error traceback output

```
Traceback (most recent call last):
  File "/Users/acarter/Documents/TRANSITS/EUREKA/QUICKSTART/run_eureka.py", line 24, in <module>
    s4_meta = s4.lcJWST(eventlabel, ecf_path=ecf_path, s3_meta=s3_meta)
  File "/Users/acarter/Documents/TRANSITS/EUREKA/QUICKSTART/../Eureka_dev/eureka/S4_generate_lightcurves/s4_genLC.py", line 97, in lcJWST
    meta = load_specific_s3_meta_info(old_meta, ecf_path, run_i, spec_hw_val, bg_hw_val)
  File "/Users/acarter/Documents/TRANSITS/EUREKA/QUICKSTART/../Eureka_dev/eureka/S4_generate_lightcurves/s4_genLC.py", line 305, in load_specific_s3_meta_info
    new_meta = read_s3_meta(meta)
  File "/Users/acarter/Documents/TRANSITS/EUREKA/QUICKSTART/../Eureka_dev/eureka/S4_generate_lightcurves/s4_genLC.py", line 254, in read_s3_meta
    raise AssertionError('Unable to find an output metadata file from Eureka!\'s S3 step '
AssertionError: Unable to find an output metadata file from Eureka!'s S3 step in the inputdir: 
"/Users/acarter/Documents/TRANSITS/EUREKA/QUICKSTART/QUICKSTART/Stage3/S3_2022-04-14_wasp39b_ap8_bg8_run4/"!

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Ahh yes, I encountered this before in Stage 5 - I have some code there that should fix this circumstance. In general, these functions I wrote are convenient under very specific circumstances but if anything changes like that then they're a real pain. We probably want to change how we save outputs and/or read inputs to avoid these headaches. But for now, the quickest and easiest fix is to change

https://github.com/kevin218/Eureka/blob/7c2db84310bf11e68517c6271f3ca1768c1897b4/eureka/S3_data_reduction/s3_reduce.py#L442

and 

https://github.com/kevin218/Eureka/blob/7c2db84310bf11e68517c6271f3ca1768c1897b4/eureka/S4_generate_lightcurves/s4_genLC.py#L272

to use meta.topdir like

https://github.com/kevin218/Eureka/blob/7c2db84310bf11e68517c6271f3ca1768c1897b4/eureka/S5_lightcurve_fitting/s5_fit.py#L315

**Comment by AarynnCarter** [comment]
Okay great! I've adjusted those now, so hopefully that can get merged in with the update to the quickstart guide.
