### ISSUE TITLE
[Bug]: installing eureka failing due to extras_require

### ISSUE THREAD

**Issue by sebastian-zieba** [kevin218/Eureka#292]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Other (any stage)

### What happened?

I freshly installed Eureka! about a week ago in a new conda environment just like explained in the docs (https://eurekadocs.readthedocs.io/en/latest/installation.html#installation-methods). I now wanted to update my local Eureka! installation with the new changes which were uploaded to _main_. Running `git pull` and `conda env update --file environment.yml --prune` worked without a problem. Doing `pip install --no-deps --upgrade .` failed however. 

It clearly failed due to `'extras_require'` in `setup.py ` looking at the error traceback: _error in Eureka setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers._

After playing around with `extras_require` it seems like the line 

`'hst': ["git+https://github.com/keflavich/image_registration.git"]`

is not following [PEP 508](https://peps.python.org/pep-0508/) syntax. After changing it to :

`   'hst': ["image_registration @ git+https://github.com/keflavich/image_registration.git"]`

I was able to successfully install Eureka!.

### Error traceback output

(eureka) zieba@lnx-n-0028:~/Desktop/Projects/tmp_clones/Eureka$ pip install --no-deps --upgrade .
Processing /home/zieba/Desktop/Projects/tmp_clones/Eureka
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in Eureka setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### What operating system are you using?

Ubuntu 18.04

### What version of Python are you running?

Python 3.9.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebastian-zieba** [comment]
@taylorbell57 I can do a quick pull request for this one if that's fine.

**Comment by taylorbell57** [comment]
Sorry about that, please do!
