### ISSUE TITLE
GetTravisCI working

### ISSUE THREAD

**Issue by kevin218** [kevin218/Eureka#3]

**Comment by kevin218** [comment]
Need to update requirements.txt to include pandas and possibly more

**Comment by kevin218** [comment]
Travis-ci works for linux, but not osx.  This is a known issue for python programs with no fix.

**Comment by taylorbell57** [comment]
My understanding is that we have fully abandoned Travis-ci, can we now close this issue?

**Comment by kevin218** [comment]
So long Travis, and thanks for nothing
