### ISSUE TITLE
mkdocs.yml points to a url we don't own

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#300]
@kevin218, I'm not sure if we still need the mkdocs.yml file, but if we do we should definitely edit it as it points to a url that we don't own (it's a vacuum website I believe)

https://github.com/kevin218/Eureka/blob/15adaa22160bfb3bbd966bc205bd9595483d8a01/mkdocs.yml#L2

**Comment by kevin218** [comment]
Maybe this file was auto-generated? I don't think we need it
