### ISSUE TITLE
[Enhancement]: Add per-integration centroid and PSF-width to S3 outputs

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#346]
### What happened?

As discussed during our meeting today, we want to be able to get the centroid and PSF width out of Stage 3 for every integration (not just per segment or anything) so that they could be decorrelated against in Stage 5 if need be. I'm unable to assign you @cpiaulet, but I believe you said you wanted to tackle this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpiaulet** [comment]
Perfect (I don't know how to assign myself on GitHub, but I'll work on that!)

**Comment by taylorbell57** [comment]
I think it might be that you aren't a contributor on the main repo at present, so you can't be assigned things. If you feel you should be added, just reach out to Kevin and ask to be added

**Comment by cpiaulet** [comment]
Quick update: I added the recording of the width of the drift ccf in Stage 4 as a potential "x_width" to decorrelate against (and an option to record the drift even if one does not want to correct for it). Now I'm working on the "y drift & width" recording in Stage 3. PR to come soon!
