### ISSUE TITLE
[Bug]: Stage 3 data.attrs values are not saved

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#352]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Other (any stage)

### What happened?

Eureka currently loads some potentially useful values into data.attrs during Stage 3, but these values are not saved when data is saved. For JWST, this currently includes data.attrs['intstart'] and data.attrs['intend'], and for the edits I've just made to WFC3 this includes data.attrs['nreads']. Instead, only the attrs of values inside the dataset are saved (e.g. data.flux.attrs still contains {'flux_units': 'ELECTRONS', 'time_units': 'BJD_TDB'} after saving). Not sure if this is a bug with Eureka, Astraeus, or xarray. Thoughts @kevin218?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin218** [comment]
Might be an Astraeus bug, but not sure, so I'll look into it.

**Comment by kevin218** [comment]
I've tracked down the problem in Astraeus and tests confirm that I can now save (and load) Dataset attributes.  I'll push changes on Monday.

**Comment by kevin218** [comment]
The redefined Dataset class wouldn't allow attributes to be saved correctly, so I've had to revert back to the original Xarray Dataset.  Also, I haven't tested for backwards compatibility in trying to load older HDF5 files.
