### ISSUE TITLE
[Bug]: `pip install -e .[jwst]` fails on MacOS Monterey `zsh`

### ISSUE THREAD

**Issue by zkbt** [kevin218/Eureka#356]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Other (any stage)

### What happened?

The [installation instructions](https://github.com/kevin218/Eureka/blob/main/docs/source/installation.rst) offer
```
git clone https://github.com/kevin218/Eureka.git
cd Eureka
pip install -e .[jwst]
```
as the first way to install Eureka!. Just a heads up, on my MacOS Monterey 12.0.1, which uses `zsh` by default, this fails, saying
```
zsh: no matches found: .[jwst]
```
Might I suggest changing that line (and other installs with options) to
```
pip install -e '.[jwst]'
```
That works for me! Thanks!

### Error traceback output

(see above)

### What operating system are you using?

MacOS Monterey 12.0.1

### What version of Python are you running?

Python 3.9.7 (after I got the install command to work in a clean environment)

### What Python packages do you have installed?

Oodles.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
I can confirm that this is an issue specifically for zsh, and your proposed solution works well on both bash and zsh. Thanks for pointing this out!
