### ISSUE TITLE
Installing on M1 Mac "(mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))"

### ISSUE THREAD

**Issue by thommevans** [kevin218/Eureka#367]
### What happened?

I'm trying to run Eureka on a relatively new Macbook Pro with an M1 chip, rather than Intel chip.

I followed all of the installation steps and got everything set up for the "Quickstart Tutorial". Then when I ran "python run_eureka.py" I got the following error:

ImportError: dlopen(/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stsci/image/_combine.cpython-39-darwin.so, 0x0002): tried: '/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stsci/image/_combine.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

I guess this means that the STScI binaries are only available for the Macbook Intel architectures (i.e. x68_64)? Does anyone know if it's possible to run Eureka on an M1 architecture (i.e. arm64)? Is this a question I should ask STScI instead?

### Error traceback output

python run_eureka.py

Traceback (most recent call last):
  File "/home/myFirstEureka/demos/run_eureka.py", line 4, in <module>
    import eureka.lib.plots
  File "/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/__init__.py", line 15, in <module>
    from . import S1_detector_processing
  File "/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S1_detector_processing/__init__.py", line 2, in <module>
    from . import s1_process
  File "/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S1_detector_processing/s1_process.py", line 6, in <module>
    from jwst.pipeline.calwebb_detector1 import Detector1Pipeline
  File "/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jwst/pipeline/__init__.py", line 2, in <module>
    from .calwebb_coron3 import Coron3Pipeline
  File "/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jwst/pipeline/calwebb_coron3.py", line 12, in <module>
    from ..outlier_detection import outlier_detection_step
  File "/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jwst/outlier_detection/__init__.py", line 1, in <module>
    from .outlier_detection_step import OutlierDetectionStep
  File "/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jwst/outlier_detection/outlier_detection_step.py", line 9, in <module>
    from jwst.outlier_detection import outlier_detection_ifu
  File "/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jwst/outlier_detection/outlier_detection_ifu.py", line 6, in <module>
    from stsci.image import median
  File "/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stsci/image/__init__.py", line 9, in <module>
    from .combine import *
  File "/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stsci/image/combine.py", line 5, in <module>
    from ._combine import combine as _combine
ImportError: dlopen(/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stsci/image/_combine.cpython-39-darwin.so, 0x0002): tried: '/home/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stsci/image/_combine.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

### What operating system are you using?

Mac OS Monterey 12.4

### What version of Python are you running?

Python 3.9

### What Python packages do you have installed?

# packages in environment at /home/opt/anaconda3/envs/eureka:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
aom                       3.3.0                h96cf925_1    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
arviz                     0.11.2             pyhd8ed1ab_0    conda-forge
asdf                      2.10.1             pyhd8ed1ab_1    conda-forge
asdf-standard             1.0.2              pyhd8ed1ab_0    conda-forge
asdf-transform-schemas    0.2.2              pyhd8ed1ab_0    conda-forge
asteval                   0.9.27             pyhd8ed1ab_0    conda-forge
astraeus                  0.2                      pypi_0    pypi
astropy                   5.1              py39h15b18c7_0    conda-forge
astropy-healpix           0.6              py39hc89836e_1    conda-forge
astroquery                0.4.6                    pypi_0    pypi
astroscrappy              1.1.0            py39h15b18c7_0    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
babel                     2.10.3             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
batman-package            2.4.9            py39h15b18c7_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               h97e831e_3    conda-forge
bokeh                     2.4.3            py39h6e9494a_0    conda-forge
bottleneck                1.3.4            py39h86b5767_1    conda-forge
brotli                    1.0.9                h5eb16cf_7    conda-forge
brotli-bin                1.0.9                h5eb16cf_7    conda-forge
brotlipy                  0.7.0           py39h63b48b0_1004    conda-forge
brunsli                   0.1                  h046ec9c_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
c-blosc2                  2.1.1                h2699725_2    conda-forge
ca-certificates           2022.6.15            h033912b_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
ccdproc                   2.3.1              pyhd8ed1ab_0    conda-forge
celerite                  0.4.2            py39hbd61c47_2    conda-forge
certifi                   2022.6.15        py39h6e9494a_0    conda-forge
cffi                      1.15.0           py39he338e87_0    conda-forge
cfitsio                   4.1.0                h2c97ad1_0    conda-forge
cftime                    1.6.0            py39h86b5767_1    conda-forge
charls                    2.3.4                he49afe7_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.1.3            py39h6e9494a_0    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
commonmark                0.9.1                      py_0    conda-forge
corner                    2.2.1              pyhd8ed1ab_0    conda-forge
coverage                  6.4.1            py39h701faf5_0    conda-forge
crds                      11.16.5                  pypi_0    pypi
cryptography              37.0.2           py39h9c2a9ce_0    conda-forge
curl                      7.83.1               h372c54d_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.30          py39hd408605_0    conda-forge
cytoolz                   0.11.2           py39h63b48b0_2    conda-forge
dask-core                 2022.6.1           pyhd8ed1ab_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docutils                  0.17.1                   pypi_0    pypi
drizzle                   1.13.4                   pypi_0    pypi
dynesty                   1.2.3              pyhd8ed1ab_0    conda-forge
emcee                     3.1.2              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
eureka                    0.0.1                    pypi_0    pypi
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
filelock                  3.7.1                    pypi_0    pypi
fonttools                 4.33.3           py39h701faf5_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fsspec                    2022.5.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39h6e9494a_5    conda-forge
george                    0.4.0            py39hf72b562_2    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
gwcs                      0.17.1             pyhd8ed1ab_0    conda-forge
h5netcdf                  1.0.1                    pypi_0    pypi
h5py                      3.1.0           nompi_py39hdc2b67d_100    conda-forge
hdf4                      4.2.15               hefd3b78_3    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
html5lib                  1.1                      pypi_0    pypi
hypothesis                6.47.1             pyhd8ed1ab_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
image-registration        0.2.6.dev7+g335a5bd          pypi_0    pypi
imagecodecs               2022.2.22        py39h7c839d0_6    conda-forge
imageio                   2.19.3             pyhcf75d05_0    conda-forge
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py39h6e9494a_0    conda-forge
importlib-resources       5.8.0              pyhd8ed1ab_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipython                   8.4.0            py39h6e9494a_0    conda-forge
jedi                      0.18.1           py39h6e9494a_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h5eb16cf_1    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.10.0           py39h6e9494a_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jwst                      1.3.3                    pypi_0    pypi
jxrlib                    1.1                  h35c211d_2    conda-forge
keyring                   23.6.0                   pypi_0    pypi
kiwisolver                1.4.3            py39h7c694c3_0    conda-forge
krb5                      1.19.3               hb49756b_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libaec                    1.0.6                he49afe7_0    conda-forge
libavif                   0.10.1               h5eb16cf_0    conda-forge
libblas                   3.9.0           15_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h5eb16cf_7    conda-forge
libbrotlidec              1.0.9                h5eb16cf_7    conda-forge
libbrotlienc              1.0.9                h5eb16cf_7    conda-forge
libcblas                  3.9.0           15_osx64_openblas    conda-forge
libcurl                   7.83.1               h372c54d_0    conda-forge
libcxx                    14.0.6               hce7ea42_0    conda-forge
libdeflate                1.12                 hac89ed1_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           15_osx64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_hb4d10b0_100    conda-forge
libnghttp2                1.47.0               h942079c_0    conda-forge
libopenblas               0.3.20          openmp_hb3cd9ec_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.4.0                h9847915_1    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libzip                    1.8.0                h8b0c345_1    conda-forge
libzlib                   1.2.12               hfe4f2af_1    conda-forge
libzopfli                 1.0.3                h046ec9c_0    conda-forge
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
lmfit                     1.0.3              pyhd8ed1ab_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.9.0                    pypi_0    pypi
lz4-c                     1.9.3                he49afe7_1    conda-forge
markdown-it-py            2.1.0                    pypi_0    pypi
markupsafe                2.1.1            py39h63b48b0_1    conda-forge
matplotlib                3.5.2            py39h6e9494a_0    conda-forge
matplotlib-base           3.5.2            py39h64a0072_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mdit-py-plugins           0.3.0                    pypi_0    pypi
mdurl                     0.1.1                    pypi_0    pypi
mistune                   0.8.4           py39h89e85a6_1005    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
myst-parser               0.18.0                   pypi_0    pypi
nbclient                  0.6.4              pyhd8ed1ab_1    conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
nbsphinx                  0.8.9              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.7           nompi_py39h8cf34ae_101    conda-forge
networkx                  2.8.4              pyhd8ed1ab_0    conda-forge
numpy                     1.23.0           py39hda39a74_0    conda-forge
numpydoc                  1.4.0                    pypi_0    pypi
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   1.1.1p               hfe4f2af_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3            py39hf72b562_0    conda-forge
pandoc                    2.18                 h694c41f_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parsley                   1.3                      pypi_0    pypi
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
photutils                 1.1.0                    pypi_0    pypi
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.1.1            py39h579eac4_1    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py39h6e9494a_3    conda-forge
poppy                     1.0.2                    pypi_0    pypi
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
psutil                    5.9.1            py39h701faf5_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyerfa                    2.0.0.1          py39h86b5767_2    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1           py39h63b48b0_1    conda-forge
pysocks                   1.7.1            py39h6e9494a_5    conda-forge
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    7.1.2            py39h6e9494a_0    conda-forge
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.10.0             pyhd8ed1ab_0    conda-forge
pytest-astropy-header     0.1.2                      py_0    conda-forge
pytest-cov                3.0.0              pyhd8ed1ab_0    conda-forge
pytest-doctestplus        0.12.0             pyhd8ed1ab_0    conda-forge
pytest-filter-subpackage  0.1.1                      py_0    conda-forge
pytest-mock               3.8.1              pyhd8ed1ab_0    conda-forge
pytest-openfiles          0.5.0                      py_0    conda-forge
pytest-remotedata         0.3.3              pyhd8ed1ab_0    conda-forge
python                    3.9.7           h1248fe1_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.15.3             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyvo                      1.3                      pypi_0    pypi
pywavelets                1.3.0            py39h86b5767_1    conda-forge
pyyaml                    6.0              py39h63b48b0_4    conda-forge
pyzmq                     23.2.0           py39hd639792_0    conda-forge
readline                  8.1.2                h3899abd_0    conda-forge
recommonmark              0.7.1              pyhd8ed1ab_0    conda-forge
reproject                 0.8              py39hc89836e_2    conda-forge
requests                  2.28.0             pyhd8ed1ab_1    conda-forge
scikit-image              0.19.3           py39hf72b562_0    conda-forge
scikit-learn              1.1.1            py39hafe9688_0    conda-forge
scipy                     1.8.1            py39hfa1a3ab_0    conda-forge
semantic_version          2.10.0             pyhd8ed1ab_0    conda-forge
setuptools                62.6.0           py39h6e9494a_0    conda-forge
setuptools-scm            7.0.2              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h6e38e02_1    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
spherical-geometry        1.2.22                   pypi_0    pypi
sphinx                    5.0.2              pyh6c4a22f_0    conda-forge
sphinx-rtd-theme          1.0.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
sqlite                    3.39.0               hd9f0692_0    conda-forge
stack_data                0.3.0              pyhd8ed1ab_0    conda-forge
stcal                     1.0.0                    pypi_0    pypi
stdatamodels              0.2.4                    pypi_0    pypi
stpipe                    0.3.3                    pypi_0    pypi
stsci-image               2.3.5                    pypi_0    pypi
stsci-imagestats          1.6.3                    pypi_0    pypi
stsci-stimage             0.2.5                    pypi_0    pypi
svo-filters               0.4.3                    pypi_0    pypi
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2022.5.4           pyhd8ed1ab_0    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39h63b48b0_3    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
tweakwcs                  0.7.4                    pypi_0    pypi
typing-extensions         4.2.0                hd8ed1ab_1    conda-forge
typing_extensions         4.2.0              pyha770c72_1    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
uncertainties             3.1.7              pyhd8ed1ab_0    conda-forge
unicodedata2              14.0.0           py39h63b48b0_1    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xarray                    2022.3.0           pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zfp                       0.5.5                h4a89273_8    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               hfe4f2af_1    conda-forge
zlib-ng                   2.0.6                hac89ed1_0    conda-forge
zstd                      1.5.2                ha9df2e0_1    conda-forge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Hey Tom, I have to say it does seem like at least that version of the `jwst` package and/or its dependencies don't yet support M1 processors. Some first debugging things I'd recommend are:

1. Make sure you started with a new conda environment when installing Eureka
2. Try installing the newest version of `jwst` (1.5.3 I believe) and see if that ends up fixing things for you. The problem with that is that `jwst>1.3.3` is known to not work for the NIRSpec simulated data (in Eureka!'s Stage 3 you'll get an error related to centroid positions), so you'll have to try one of the other simulated data sets - I believe the MIRI simulations work with `jwst==1.5.3`.
3. If you can't get Stage 1 to work, for the time being you could try downloading the Stage 1 outputs instead of the Uncalibrated files from the Box folder and seeing if it's just Stage 1 that has an issue.

If # 1-2 didn't fix the issue for you, I'd be sure to reach out to STScI as I believe there's nothing we can do to resolve this on our end. Do let us know here if/how you end up getting things to work so we can add that to our FAQ page

**Comment by taylorbell57** [comment]
Ooh, actually the very first thing I'd try is following a different installation method instead of the conda environment.yml method I believe you used. If you read our current installation instructions, I'd try option a after making a new conda environment.

**Comment by taylorbell57** [comment]
@thommevans, were you ever able to resolve this issue?
