### ISSUE TITLE
Working with large dataset, facing some issues.

### ISSUE THREAD

**Issue by jovian-explorer** [kevin218/Eureka#368]
### Instrument

NIRSpec 

### What happened?

Initially, my system only had 8GB RAM. I just added 8GB more today, and tried to run the large dataset on my system. The code ran for a couple of hours, and then got stuck at some point.

### Error traceback output

    2022-07-04 14:57:42,796 - stpipe.EurekaSpec2Pipeline.extract_1d - WARNING - The photom step has not been run.
    2022-07-04 14:57:42,796 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Processing spectral order 0
    2022-07-04 14:57:42,796 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Beginning loop over 8192 integrations ...
    2022-07-04 14:57:42,872 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Using extraction limits: 
    2022-07-04 14:57:42,872 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - xstart=0, xstop=483, ystart=12.5, ystop=18.5
    .
    .
    .
    2022-07-04 16:37:51,063 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
    2022-07-04 16:37:51,783 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
    2022-07-04 16:37:52,400 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - All 8192 integrations done
    2022-07-04 16:37:52,400 - stpipe.EurekaSpec2Pipeline.extract_1d - WARNING - INTSTART not found; assuming a value of 1.
    2022-07-04 16:37:52,400 - stpipe.EurekaSpec2Pipeline.extract_1d - WARNING - INTEND not found; assuming a value of 8192.
    2022-07-04 16:37:52,400 - stpipe.EurekaSpec2Pipeline.extract_1d - WARNING - There is no INT_TIMES table in the input file.  

### What operating system are you using?

linux ubuntu 20.04

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

    (eureka) keshav@dev:~$ conda list
    # packages in environment at /home/keshav/anaconda3/envs/eureka:
    #
    # Name                    Version                   Build  Channel
    _libgcc_mutex             0.1                 conda_forge    conda-forge
    _openmp_mutex             4.5                       2_gnu    conda-forge
    alabaster                 0.7.12                   pypi_0    pypi
    asdf                      2.10.1                   pypi_0    pypi
    asdf-astropy              0.2.1                    pypi_0    pypi
    asdf-coordinates-schemas  0.1.0                    pypi_0    pypi
    asdf-standard             1.0.2                    pypi_0    pypi
    asdf-transform-schemas    0.2.2                    pypi_0    pypi
    asdf-wcs-schemas          0.1.1                    pypi_0    pypi
    asteval                   0.9.27                   pypi_0    pypi
    astraeus                  0.2                      pypi_0    pypi
    astropy                   5.1                      pypi_0    pypi
    astropy-healpix           0.6                      pypi_0    pypi
    astroquery                0.4.6                    pypi_0    pypi
    astroscrappy              1.1.0                    pypi_0    pypi
    asttokens                 2.0.5                    pypi_0    pypi
    attrs                     21.4.0                   pypi_0    pypi
    babel                     2.10.3                   pypi_0    pypi
    backcall                  0.2.0                    pypi_0    pypi
    batman-package            2.4.9                    pypi_0    pypi
    beautifulsoup4            4.11.1                   pypi_0    pypi
    bokeh                     2.4.3                    pypi_0    pypi
    bottleneck                1.3.4                    pypi_0    pypi
    ca-certificates           2022.6.15            ha878542_0    conda-forge
    ccdproc                   2.3.1                    pypi_0    pypi
    celerite                  0.4.2                    pypi_0    pypi
    certifi                   2022.6.15                pypi_0    pypi
    cffi                      1.15.0                   pypi_0    pypi
    cftime                    1.6.0                    pypi_0    pypi
    charset-normalizer        2.0.12                   pypi_0    pypi
    cloudpickle               2.1.0                    pypi_0    pypi
    corner                    2.2.1                    pypi_0    pypi
    crds                      11.16.4                  pypi_0    pypi
    cryptography              37.0.2                   pypi_0    pypi
    cycler                    0.11.0                   pypi_0    pypi
    cython                    0.29.30                  pypi_0    pypi
    dask                      2022.6.0                 pypi_0    pypi
    decorator                 5.1.1                    pypi_0    pypi
    docutils                  0.18.1                   pypi_0    pypi
    drizzle                   1.13.4                   pypi_0    pypi
    dynesty                   1.2.3                    pypi_0    pypi
    emcee                     3.1.2                    pypi_0    pypi
    eureka                    0.0.1                     dev_0    <develop>
    executing                 0.8.3                    pypi_0    pypi
    filelock                  3.7.1                    pypi_0    pypi
    fonttools                 4.33.3                   pypi_0    pypi
    fsspec                    2022.5.0                 pypi_0    pypi
    future                    0.18.2                   pypi_0    pypi
    george                    0.4.0                    pypi_0    pypi
    gwcs                      0.18.1                   pypi_0    pypi
    h5netcdf                  1.0.0                    pypi_0    pypi
    h5py                      3.1.0                    pypi_0    pypi
    html5lib                  1.1                      pypi_0    pypi
    idna                      3.3                      pypi_0    pypi
    imageio                   2.19.3                   pypi_0    pypi
    imagesize                 1.3.0                    pypi_0    pypi
    importlib-metadata        4.11.4                   pypi_0    pypi
    iniconfig                 1.1.1                    pypi_0    pypi
    ipython                   8.4.0                    pypi_0    pypi
    jedi                      0.18.1                   pypi_0    pypi
    jeepney                   0.8.0                    pypi_0    pypi
    jinja2                    3.1.2                    pypi_0    pypi
    jmespath                  1.0.1                    pypi_0    pypi
    jsonschema                3.2.0                    pypi_0    pypi
    jwst                      1.3.3                    pypi_0    pypi
    keyring                   23.6.0                   pypi_0    pypi
    kiwisolver                1.4.3                    pypi_0    pypi
    ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
    libffi                    3.4.2                h7f98852_5    conda-forge
    libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
    libgomp                   12.1.0              h8d9b700_16    conda-forge
    libzlib                   1.2.12               h166bdaf_1    conda-forge
    lmfit                     1.0.3                    pypi_0    pypi
    locket                    1.0.0                    pypi_0    pypi
    lxml                      4.9.0                    pypi_0    pypi
    markupsafe                2.1.1                    pypi_0    pypi
    matplotlib                3.5.2                    pypi_0    pypi
    matplotlib-inline         0.1.3                    pypi_0    pypi
    ncurses                   6.3                  h27087fc_1    conda-forge
    netcdf4                   1.5.8                    pypi_0    pypi
    networkx                  2.8.4                    pypi_0    pypi
    numpy                     1.23.0                   pypi_0    pypi
    numpydoc                  1.4.0                    pypi_0    pypi
    openssl                   3.0.4                h166bdaf_0    conda-forge
    packaging                 21.3                     pypi_0    pypi
    pandas                    1.4.3                    pypi_0    pypi
    parsley                   1.3                      pypi_0    pypi
    parso                     0.8.3                    pypi_0    pypi
    partd                     1.2.0                    pypi_0    pypi
    pexpect                   4.8.0                    pypi_0    pypi
    photutils                 1.1.0                    pypi_0    pypi
    pickleshare               0.7.5                    pypi_0    pypi
    pillow                    9.1.1                    pypi_0    pypi
    pip                       22.1.2             pyhd8ed1ab_0    conda-forge
    pluggy                    1.0.0                    pypi_0    pypi
    poppy                     1.0.2                    pypi_0    pypi
    prompt-toolkit            3.0.29                   pypi_0    pypi
    psutil                    5.9.1                    pypi_0    pypi
    ptyprocess                0.7.0                    pypi_0    pypi
    pure-eval                 0.2.2                    pypi_0    pypi
    py                        1.11.0                   pypi_0    pypi
    pycparser                 2.21                     pypi_0    pypi
    pyerfa                    2.0.0.1                  pypi_0    pypi
    pygments                  2.12.0                   pypi_0    pypi
    pyparsing                 3.0.9                    pypi_0    pypi
    pyrsistent                0.18.1                   pypi_0    pypi
    pysynphot                 2.0.0                    pypi_0    pypi
    pytest                    7.1.2                    pypi_0    pypi
    python                    3.9.7           hf930737_3_cpython    conda-forge
    python-dateutil           2.8.2                    pypi_0    pypi
    python_abi                3.9                      2_cp39    conda-forge
    pytz                      2022.1                   pypi_0    pypi
    pyvo                      1.3                      pypi_0    pypi
    pywavelets                1.3.0                    pypi_0    pypi
    pyyaml                    6.0                      pypi_0    pypi
    readline                  8.1.2                h0f457ee_0    conda-forge
    reproject                 0.8                      pypi_0    pypi
    requests                  2.28.0                   pypi_0    pypi
    scikit-image              0.19.3                   pypi_0    pypi
    scipy                     1.8.1                    pypi_0    pypi
    secretstorage             3.3.2                    pypi_0    pypi
    semantic-version          2.10.0                   pypi_0    pypi
    setuptools                62.6.0           py39hf3d152e_0    conda-forge
    six                       1.16.0                   pypi_0    pypi
    snowballstemmer           2.2.0                    pypi_0    pypi
    soupsieve                 2.3.2.post1              pypi_0    pypi
    spherical-geometry        1.2.22                   pypi_0    pypi
    sphinx                    5.0.2                    pypi_0    pypi
    sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
    sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
    sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
    sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
    sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
    sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
    sqlite                    3.38.5               h4ff8645_0    conda-forge
    stack-data                0.3.0                    pypi_0    pypi
    stcal                     0.7.3                    pypi_0    pypi
    stdatamodels              0.2.4                    pypi_0    pypi
    stpipe                    0.3.3                    pypi_0    pypi
    stsci-image               2.3.5                    pypi_0    pypi
    stsci-imagestats          1.6.3                    pypi_0    pypi
    stsci-stimage             0.2.5                    pypi_0    pypi
    svo-filters               0.4.3                    pypi_0    pypi
    tifffile                  2022.5.4                 pypi_0    pypi
    tk                        8.6.12               h27826a3_0    conda-forge
    tomli                     2.0.1                    pypi_0    pypi
    toolz                     0.11.2                   pypi_0    pypi
    tornado                   6.1                      pypi_0    pypi
    tqdm                      4.64.0                   pypi_0    pypi
    traitlets                 5.3.0                    pypi_0    pypi
    tweakwcs                  0.7.4                    pypi_0    pypi
    typing-extensions         4.2.0                    pypi_0    pypi
    tzdata                    2022a                h191b570_0    conda-forge
    uncertainties             3.1.7                    pypi_0    pypi
    urllib3                   1.26.9                   pypi_0    pypi
    wcwidth                   0.2.5                    pypi_0    pypi
    webencodings              0.5.1                    pypi_0    pypi
    wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
    xarray                    2022.3.0                 pypi_0    pypi
    xz                        5.2.5                h516909a_1    conda-forge
    zipp                      3.8.0                    pypi_0    pypi
    zlib                      1.2.12               h166bdaf_1    conda-forge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AarynnCarter** [comment]
Hi @jovian-explorer, are you sure it got stuck? The extract_1d step is very time consuming. Here are two possible paths forward:

1) Run things again, but wait longer (it takes a few hours on my Mac).

2) Skip the extract_1d step in the corresponding .ecf file. Eureka doesn't actually need these 1D extracted spectra, and will instead perform the extraction itself using the extract_2d products (*.calints.fits). So if you don't need them, there's not too much benefit in running this step. 

Cheers!

**Comment by jovian-explorer** [comment]
Okay let me try this and get back to you!!

**Comment by jovian-explorer** [comment]
Okay so I did what you suggested, and the 2nd option worked. Now, I am stuck in the stage 5 for some reason. I did face this exact similar issue in issue #326  as well, but the epf has been updated as Taylor had suggested in that thread. I am copy pasting the traceback error, as well as the epf file I have for stage 5. This issue is a bit different from #326  as it runs for channel 1 for around 15 minutes or so, then gives - 

    Summary
    =======
    nlive: 1024
    niter: 61324
    ncall: 1778086
    eff(%):  3.506
    logz: 21330.060 +/-  0.296
    
    Number of posterior samples is 62348
    Ending lnprob: 21367.517662105212
    Reduced Chi-squared: 6.206928884276193
    
    DYNESTY RESULTS:
    rp: 0.1486763560658408 (+6.615866188219854e-11, -4.166225475721319e-09)
    per: 4.055260100708521 (+1.085354028873553e-11, -7.638334409421077e-14)
    t0: 57394.52207314224 (+3.92901711165905e-10, -1.4551915228366852e-11)
    inc: 87.765255814397 (+3.2802063287817873e-09, -9.242832277323032e-08)
    a: 11.233599454480833 (+1.5673025544060692e-08, -4.970156108896617e-07)
    u1: 0.5245098625788 (+3.1776331566035765e-09, -1.7836583987573817e-08)
    u2: 0.7020875274357845 (+1.5072408010574634e-07, -3.296185768775217e-09)
    c0: 1.0141109513670816 (+2.4431567879901195e-12, -2.0086599050728182e-10)
    c1: -0.003329850934854349 (+2.1083747781501516e-09, -2.0384462347255994e-11)
    scatter_ppm: 1320.9536151601387 (+0.0, -0.0)

and then this traceback after the above - 

    Traceback (most recent call last):
      File "/home/keshav/Data/JWST-Sim/NIRSpec/run_eureka.py", line 32, in <module>
        s5_meta = s5.fitlc(eventlabel, ecf_path=ecf_path, s4_meta=s4_meta)
      File "/home/keshav/Eureka/src/eureka/S5_lightcurve_fitting/s5_fit.py", line 192, in fitlc
        meta = fit_channel(meta, time, flux, channel, flux_err,
      File "/home/keshav/Eureka/src/eureka/S5_lightcurve_fitting/s5_fit.py", line 348, in fit_channel
        lc_model.fit(model, meta, log, fitter='dynesty')
      File "/home/keshav/Eureka/src/eureka/S5_lightcurve_fitting/lightcurve.py", line 146, in fit
        fit_model = self.fitter_func(self, model, meta, log, **kwargs)
      File "/home/keshav/Eureka/src/eureka/S5_lightcurve_fitting/fitters.py", line 910, in dynestyfitter
        plots.plot_corner(samples, lc, meta, freenames, fitter='dynesty')
      File "/home/keshav/Eureka/src/eureka/S5_lightcurve_fitting/plots_s5.py", line 203, in plot_corner
        fig = corner.corner(samples, fig=fig, quantiles=[0.16, 0.5, 0.84],
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/corner/corner.py", line 226, in corner
        return corner_impl(
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/corner/core.py", line 121, in corner_impl
        raise ValueError(
    ValueError: It looks like the parameter(s) in column(s) 9 have no dynamic range. Please provide a `range` argument.

I am also copy pasting my S5 parameter file as well, to make sure I give you as much information as I can think of - 

    # Stage 5 Fit Parameters Documentation: https://eurekadocs.readthedocs.io/en/latest/ecf.html#stage-5-fit-parameters
    
    
    #Name        Value         Free?          PriorPar1    PriorPar2    PriorType
    # PriorType can be U (Uniform), LU (Log Uniform), or N (Normal).
    # If U/LU, PriorPar1 and PriorPar2 represent upper and lower limits of the parameter/log(the parameter).
    # If N, PriorPar1 is the mean and PriorPar2 is the standard deviation of a Gaussian prior.
    #-------------------------------------------------------------------------------------------------------
    #
    # ------------------
    # ** Transit/eclipse parameters **
    # ------------------
    rp           0.148          'free'         0.15         0.1          N
    #fp           0.008          'free'         0           0.5          U
    # ----------------------
    # ** Phase curve parameters **
    # ----------------------
    #AmpCos1      0.4           'free'         0            1            U
    #AmpSin1      0.01          'free'         -1           1            U
    #AmpCos2      0.01          'free'         -1           1            U
    #AmpSin2      0.01          'free'         -1           1            U
    # ------------------
    # ** Orbital parameters **
    # ------------------
    per          4.055259       'free'         4.055259     1e-5         N
    t0           57394.524      'free'         57394.524    0.05         N
    time_offset  0              'independent'
    inc          87.83          'free'         87.83        0.25         N
    a            10.9           'free'         10.9         1            N  # An incorrect a/R* seems to have been used in the simulations
    ecc          0.0            'fixed'        0            1            U
    w            90.            'fixed'        0            180          U
    # -------------------------
    # ** Limb darkening parameters **
    # Choose limb_dark from ['uniform', 'linear', 'quadratic', 'kipping2013', 'square-root', 'logarithmic', 'exponential', '4-parameter']
    # -------------------------
    limb_dark    'kipping2013'  'independent'
    u1           0.59           'free'         0            1            U
    u2           0.84           'free'         0            1            U
    # --------------------
    # ** Systematic variables **
    # polynomial model variables (c0--c9 for 0th--3rd order polynomials in time); Fitting at least c0 is very strongly recommended!
    # expramp model variables (r0--r2 for one exponential ramp, r3--r5 for a second exponential ramp)
    # GP model parameters (A, WN, m1, m2) in log scale
    # --------------------
    c0           1.015          'free'         1            0.05         N
    c1           0              'free'         0            0.01          N
    #A            -5             'free'         -20.         -5.          U
    #WN           -15            'free'         -20.         -10.         U
    #m1           -5             'free'         -10.         0.           U
    # -----------
    # ** White noise **
    # Use scatter_mult to fit a multiplier to the expected noise level from Stage 3 (recommended)
    # Use scatter_ppm to fit the noise level in ppm
    # Use WN parameter in GP model parameters to account for white noise in the GP model
    # -----------
    #scatter_mult 1.1            'free'         1            0.1          N
    scatter_ppm  500            'free'         500          100          N

**Comment by jovian-explorer** [comment]
For now things seem to be going perfectly. I think I messed up somewhere. I am closing this issue as the original issue has been rectified. Thanks!!

**Comment by jovian-explorer** [comment]
This issue is again repeating. Just like above, I am facing the above issue all over again. With the same conditions. Although it resolved itself last time, this time it's still stuck here, even after going through stage 5 epf thoroughly. 
Just for clarity on what went wrong, I am copy pasting the EPF here. 

    # Stage 5 Fit Parameters Documentation: https://eurekadocs.readthedocs.io/en/latest/ecf.html#stage-5-fit-parameters
    
    
    # Name       Value         Free?          PriorPar1    PriorPar2    PriorType
    # "Free?" can be free, fixed, white_free, white_fixed, shared, or independent
    # PriorType can be U (Uniform), LU (Log Uniform), or N (Normal).
    # If U/LU, PriorPar1 and PriorPar2 represent upper and lower limits of the parameter/log(the parameter).
    # If N, PriorPar1 is the mean and PriorPar2 is the standard deviation of a Gaussian prior.
    #-------------------------------------------------------------------------------------------------------
    #
    # ------------------
    # ** Transit/eclipse parameters **
    # ------------------
    rp           0.148          'free'         0.15         0.1          N
    #fp           0.008          'free'         0           0.5          U
    # ----------------------
    # ** Phase curve parameters **
    # ----------------------
    #AmpCos1      0.4           'free'         0            1            U
    #AmpSin1      0.01          'free'         -1           1            U
    #AmpCos2      0.01          'free'         -1           1            U
    #AmpSin2      0.01          'free'         -1           1            U
    # ------------------
    # ** Orbital parameters **
    # ------------------
    per          4.055259       'free'         4.055259     1e-5         N
    t0    57394.52    'free'    57394.5    57394.55    U
    time_offset  0              'independent'
    inc          87.83          'free'         87.83        0.25         N
    a            10.9           'free'         10.9         1            N  # An incorrect a/R* seems to have been used in the simulations
    ecc          0.0            'fixed'        0            1            U
    w            90.            'fixed'        0            180          U
    # -------------------------
    # ** Limb darkening parameters **
    # Choose limb_dark from ['uniform', 'linear', 'quadratic', 'kipping2013', 'square-root', 'logarithmic', 'exponential','3-parameter', '4-parameter']
    # When using generated limb-darkening coefficients from exotic-ld choose from ['linear', 'quadratic', '3-parameter', '4-parameter']
    # -------------------------
    limb_dark    'kipping2013'  'independent'
    u1           0.59           'free'         0            1            U
    u2           0.84           'free'         0            1            U
    # --------------------
    # ** Systematic variables **
    # polynomial model variables (c0--c9 for 0th--3rd order polynomials in time); Fitting at least c0 is very strongly recommended!
    # expramp model variables (r0--r2 for one exponential ramp, r3--r5 for a second exponential ramp)
    # GP model parameters (A, WN, m1, m2) in log scale
    # step-function model variables (step# and steptime# for step-function model #; e.g. step0 and steptime0)
    # --------------------
    c0           1.015          'free'         1            0.05         N
    c1           0              'free'         0            0.01          N
    #A            -5             'free'         -20.         -5.          U
    #WN           -15            'free'         -20.         -10.         U
    #m1           -5             'free'         -10.         0.           U
    # -----------
    # ** White noise **
    # Use scatter_mult to fit a multiplier to the expected noise level from Stage 3 (recommended)
    # Use scatter_ppm to fit the noise level in ppm
    # Use WN parameter in GP model parameters to account for white noise in the GP model
    # -----------
    #scatter_mult 1.1            'free'         1            0.1          N
    scatter_ppm  500            'free'         500          100          N


Also, I am copy pasting the log files generated before the code crashes - 
    
    
    Starting Stage 2 Reduction
    Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage1/
    Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage2/S2_2022-07-17_wasp39b_run6/
    Copying S2 control file
    
    Found 1 data file(s) ending in rateints.fits
    Starting file 1 of 1
    Editing (in place) the waverange in the input file
    Running the Spec2Pipeline
    
    
    Generating x1dints figure
    Saving Metadata
    
    Total time (min): 0.63
    
    Starting Stage 3 Reduction
    
    Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage2/S2_2022-07-17_wasp39b_run6/
    Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage3/S3_2022-07-17_wasp39b_run6/ap6_bg7/
    Using ap=6, bg=7
    Copying S3 control file
    
    Found 1 data file(s) ending in calints.fits
    WARNING: Are you using real JWST data? If so, you should edit the flag_bg() function in nirspec.py and look at Issue #193 on Github!
    Starting file 1 of 1
      Locating source position...
        Source position on detector is row 13.
      Automatically getting reference files to convert units to electrons...
      Converting from data numbers per second (DN/s) to electrons...
      Masking NaNs in data arrays...
      Performing background outlier rejection...
      Performing background subtraction...
      Creating figures for background subtraction...
      Extracting aperture region...
      Performing optimal spectral extraction...
      Creating figures for optimal spectral extraction
    Stage 3 MAD = 7528 ppm
    Generating figure
    Saving Metadata
    
    Total time (min): 1.14
    
    Starting Stage 4: Generate Light Curves
    
    Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage3/S3_2022-07-17_wasp39b_run6/ap6_bg7/
    Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage4/S4_2022-07-17_wasp39b_run6/ap6_bg7/
    Copying S4 control file
    Loading S3 save file:
    /home/keshav/Data/JWST-Sim/NIRSpec/Stage3/S3_2022-07-17_wasp39b_run6/ap6_bg7/S3_wasp39b_ap6_bg7_SpecData.h5
    Stage 4 MAD = 6822.64 ppm
    Generating light curves
      Bandpass 0 = 1.000 - 1.200
        MAD = 10232 ppm
      Bandpass 1 = 1.200 - 1.400
        MAD = 7291 ppm
      Bandpass 2 = 1.400 - 1.600
        MAD = 3439 ppm
      Bandpass 3 = 1.600 - 1.800
        MAD = 2920 ppm
      Bandpass 4 = 1.800 - 2.000
        MAD = 3035 ppm
      Bandpass 5 = 2.000 - 2.200
        MAD = 2216 ppm
      Bandpass 6 = 2.200 - 2.400
        MAD = 2077 ppm
      Bandpass 7 = 2.400 - 2.600
        MAD = 1931 ppm
      Bandpass 8 = 2.600 - 2.800
        MAD = 2249 ppm
      Bandpass 9 = 2.800 - 3.000
        MAD = 2682 ppm
      Bandpass 10 = 3.000 - 3.200
        MAD = 2423 ppm
      Bandpass 11 = 3.200 - 3.400
        MAD = 1742 ppm
      Bandpass 12 = 3.400 - 3.600
        MAD = 2111 ppm
      Bandpass 13 = 3.600 - 3.800
        MAD = 2157 ppm
      Bandpass 14 = 3.800 - 4.000
        MAD = 2075 ppm
      Bandpass 15 = 4.000 - 4.200
        MAD = 1772 ppm
      Bandpass 16 = 4.200 - 4.400
        MAD = 2283 ppm
      Bandpass 17 = 4.400 - 4.600
        MAD = 1735 ppm
      Bandpass 18 = 4.600 - 4.800
        MAD = 3114 ppm
      Bandpass 19 = 4.800 - 5.000
        MAD = 7806 ppm
    Saving results...
    
    Total time (min): 0.24
    Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage4/S4_2022-07-17_wasp39b_run6/ap6_bg7/
    Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage5/S5_2022-07-17_wasp39b_run6/ap6_bg7/
    Copying S5 control file
    Copying S5 parameter control file
    
    Starting Channel 1 of 20
    
    =========================
    Starting dynesty fit.
    Starting lnprob: -8542.314163469147
    Running dynesty...
    
    Summary
    =======
    nlive: 256
    niter: 13736
    ncall: 397922
    eff(%):  3.516
    logz: -802.205 +/-  0.535
    
    Number of posterior samples is 13992
    Ending lnprob: -779.5456582410036
    Reduced Chi-squared: 84.88549187201104
    
    DYNESTY RESULTS:
    rp: 0.1269144485537322 (+2.4013568911129823e-12, -5.387884582930269e-12)
    per: 4.055232323174846 (+3.552713678800501e-15, -5.542233338928781e-13)
    t0: 57394.52811650725 (+7.275957614183426e-12, -0.0)
    inc: 88.34708030384174 (+2.6958844046021113e-09, -1.1021938917110674e-10)
    a: 11.264065406679205 (+5.667324387559347e-10, -1.1658229936983844e-10)
    u1: 0.026975892027329595 (+3.5129878173112417e-11, -2.3677904775754044e-10)
    u2: 0.33419752006800146 (+4.075634274514073e-11, -1.563113527502935e-10)
    c0: 1.010095433821618 (+2.4358293160275934e-13, -2.687627898012579e-12)
    c1: 0.012619350745121887 (+2.336100063393687e-12, -8.103203871789866e-12)
    scatter_ppm: 1320.9536151601387 (+0.0, -0.0)


This error, to be honest looks more like a **bug** to me. Idk why it even repeats even when I run the same dataset again without making any changes to my Eureka! installation.
Right now, my Eureka! installation is up to date, and the EPF and log files are as I just pasted above.

**Comment by AarynnCarter** [comment]
Hi Keshav, this issue was initially related to NIRSpec Stage 1-3 and is separate from this most recent bug. If you open a new bug report then the correct person will be assigned to take a look at this in more detail, my expertise lies more in Stages 1-3.

**Comment by jovian-explorer** [comment]
Okay. Thanks.
