### ISSUE TITLE
Eurekadocs Doesn't Exist

### ISSUE THREAD

**Issue by kevin218** [kevin218/Eureka#37]
Link in README is broken ([https://eurekadocs.readthedocs.io/en/](https://eurekadocs.readthedocs.io/en/))

**Comment by sebastian-zieba** [comment]
True! It's actually https://eurekadocs.readthedocs.io . I fixed that and it will be changed after the current Pull Request goes through.

**Comment by sebastian-zieba** [comment]
Works again now :)
