### ISSUE TITLE
Getting started with MIRI

### ISSUE THREAD

**Issue by jovian-explorer** [kevin218/Eureka#377]
### Instrument

MIRI (Stages 1-3)

### What happened?

I have tried to run MIRI now, after being able to run NIRSpec. I am sharing the log files, and outputs for you to look at it and verify if I have managed to do so correctly.

### Log file - 

    
    Starting Stage 2 Reduction
    Input directory: /home/keshav/Data/JWST-Sim/MIRI/Stage1/
    Output directory: /home/keshav/Data/JWST-Sim/MIRI/Stage2/S2_2022-07-13_wasp39b_run1/
    Copying S2 control file
    
    Found 1 data file(s) ending in rateints.fits
    Starting file 1 of 1
    Running the Spec2Pipeline
    
    
    Generating x1dints figure
    
    Total time (min): 0.43
    Saving Metadata
    
    Starting Stage 3 Reduction
    
    Input directory: /home/keshav/Data/JWST-Sim/MIRI/Stage2/S2_2022-07-13_wasp39b_run1/
    Output directory: /home/keshav/Data/JWST-Sim/MIRI/Stage3/S3_2022-07-13_wasp39b_run1/ap4_bg8/
    Using ap=4, bg=8
    Copying S3 control file
    
    Found 1 data file(s) ending in calints.fits
    Starting file 1 of 1
      WARNING: The wavelength for the simulated MIRI data are currently hardcoded
    because they are not in the .fits files themselves
      WARNING: The timestamps for the simulated MIRI data are currently hardcoded
    because they are not in the .fits files themselves
      Locating source position...
        Source position on detector is row 31.
      Automatically getting reference files to convert units to electrons
      Converting from data numbers per second (DN/s) to electrons
      Performing background outlier rejection...
      Performing background subtraction...
      Creating figures for background subtraction
      Extracting aperture region...
      Performing optimal spectral extraction...
      Creating figures for optimal spectral extraction
    Stage 3 MAD = 19549 ppm
    Generating figure
    Saving Metadata
    
    Total time (min): 1.3

### What operating system are you using?

linux ubuntu 20.04

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

    (eureka) keshav@dev:~$ conda list
    # packages in environment at /home/keshav/anaconda3/envs/eureka:
    #
    # Name                    Version                   Build  Channel
    _libgcc_mutex             0.1                 conda_forge    conda-forge
    _openmp_mutex             4.5                       2_gnu    conda-forge
    alabaster                 0.7.12                   pypi_0    pypi
    asdf                      2.10.1                   pypi_0    pypi
    asdf-astropy              0.2.1                    pypi_0    pypi
    asdf-coordinates-schemas  0.1.0                    pypi_0    pypi
    asdf-standard             1.0.2                    pypi_0    pypi
    asdf-transform-schemas    0.2.2                    pypi_0    pypi
    asdf-wcs-schemas          0.1.1                    pypi_0    pypi
    asteval                   0.9.27                   pypi_0    pypi
    astraeus                  0.2                      pypi_0    pypi
    astropy                   5.1                      pypi_0    pypi
    astropy-healpix           0.6                      pypi_0    pypi
    astroquery                0.4.6                    pypi_0    pypi
    astroscrappy              1.1.0                    pypi_0    pypi
    asttokens                 2.0.5                    pypi_0    pypi
    attrs                     21.4.0                   pypi_0    pypi
    babel                     2.10.3                   pypi_0    pypi
    backcall                  0.2.0                    pypi_0    pypi
    batman-package            2.4.9                    pypi_0    pypi
    beautifulsoup4            4.11.1                   pypi_0    pypi
    bokeh                     2.4.3                    pypi_0    pypi
    bottleneck                1.3.4                    pypi_0    pypi
    ca-certificates           2022.6.15            ha878542_0    conda-forge
    ccdproc                   2.3.1                    pypi_0    pypi
    celerite                  0.4.2                    pypi_0    pypi
    certifi                   2022.6.15                pypi_0    pypi
    cffi                      1.15.0                   pypi_0    pypi
    cftime                    1.6.0                    pypi_0    pypi
    charset-normalizer        2.0.12                   pypi_0    pypi
    cloudpickle               2.1.0                    pypi_0    pypi
    corner                    2.2.1                    pypi_0    pypi
    crds                      11.16.4                  pypi_0    pypi
    cryptography              37.0.2                   pypi_0    pypi
    cycler                    0.11.0                   pypi_0    pypi
    cython                    0.29.30                  pypi_0    pypi
    dask                      2022.6.0                 pypi_0    pypi
    decorator                 5.1.1                    pypi_0    pypi
    docutils                  0.18.1                   pypi_0    pypi
    drizzle                   1.13.4                   pypi_0    pypi
    dynesty                   1.2.3                    pypi_0    pypi
    emcee                     3.1.2                    pypi_0    pypi
    eureka                    0.0.1                     dev_0    <develop>
    executing                 0.8.3                    pypi_0    pypi
    filelock                  3.7.1                    pypi_0    pypi
    fonttools                 4.33.3                   pypi_0    pypi
    fsspec                    2022.5.0                 pypi_0    pypi
    future                    0.18.2                   pypi_0    pypi
    george                    0.4.0                    pypi_0    pypi
    gwcs                      0.18.1                   pypi_0    pypi
    h5netcdf                  1.0.0                    pypi_0    pypi
    h5py                      3.1.0                    pypi_0    pypi
    html5lib                  1.1                      pypi_0    pypi
    idna                      3.3                      pypi_0    pypi
    imageio                   2.19.3                   pypi_0    pypi
    imagesize                 1.3.0                    pypi_0    pypi
    importlib-metadata        4.11.4                   pypi_0    pypi
    iniconfig                 1.1.1                    pypi_0    pypi
    ipython                   8.4.0                    pypi_0    pypi
    jedi                      0.18.1                   pypi_0    pypi
    jeepney                   0.8.0                    pypi_0    pypi
    jinja2                    3.1.2                    pypi_0    pypi
    jmespath                  1.0.1                    pypi_0    pypi
    jsonschema                3.2.0                    pypi_0    pypi
    jwst                      1.3.3                    pypi_0    pypi
    keyring                   23.6.0                   pypi_0    pypi
    kiwisolver                1.4.3                    pypi_0    pypi
    ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
    libffi                    3.4.2                h7f98852_5    conda-forge
    libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
    libgomp                   12.1.0              h8d9b700_16    conda-forge
    libzlib                   1.2.12               h166bdaf_1    conda-forge
    lmfit                     1.0.3                    pypi_0    pypi
    locket                    1.0.0                    pypi_0    pypi
    lxml                      4.9.0                    pypi_0    pypi
    markupsafe                2.1.1                    pypi_0    pypi
    matplotlib                3.5.2                    pypi_0    pypi
    matplotlib-inline         0.1.3                    pypi_0    pypi
    ncurses                   6.3                  h27087fc_1    conda-forge
    netcdf4                   1.5.8                    pypi_0    pypi
    networkx                  2.8.4                    pypi_0    pypi
    numpy                     1.23.0                   pypi_0    pypi
    numpydoc                  1.4.0                    pypi_0    pypi
    openssl                   3.0.4                h166bdaf_0    conda-forge
    packaging                 21.3                     pypi_0    pypi
    pandas                    1.4.3                    pypi_0    pypi
    parsley                   1.3                      pypi_0    pypi
    parso                     0.8.3                    pypi_0    pypi
    partd                     1.2.0                    pypi_0    pypi
    pexpect                   4.8.0                    pypi_0    pypi
    photutils                 1.1.0                    pypi_0    pypi
    pickleshare               0.7.5                    pypi_0    pypi
    pillow                    9.1.1                    pypi_0    pypi
    pip                       22.1.2             pyhd8ed1ab_0    conda-forge
    pluggy                    1.0.0                    pypi_0    pypi
    poppy                     1.0.2                    pypi_0    pypi
    prompt-toolkit            3.0.29                   pypi_0    pypi
    psutil                    5.9.1                    pypi_0    pypi
    ptyprocess                0.7.0                    pypi_0    pypi
    pure-eval                 0.2.2                    pypi_0    pypi
    py                        1.11.0                   pypi_0    pypi
    pycparser                 2.21                     pypi_0    pypi
    pyerfa                    2.0.0.1                  pypi_0    pypi
    pygments                  2.12.0                   pypi_0    pypi
    pyparsing                 3.0.9                    pypi_0    pypi
    pyrsistent                0.18.1                   pypi_0    pypi
    pysynphot                 2.0.0                    pypi_0    pypi
    pytest                    7.1.2                    pypi_0    pypi
    python                    3.9.7           hf930737_3_cpython    conda-forge
    python-dateutil           2.8.2                    pypi_0    pypi
    python_abi                3.9                      2_cp39    conda-forge
    pytz                      2022.1                   pypi_0    pypi
    pyvo                      1.3                      pypi_0    pypi
    pywavelets                1.3.0                    pypi_0    pypi
    pyyaml                    6.0                      pypi_0    pypi
    readline                  8.1.2                h0f457ee_0    conda-forge
    reproject                 0.8                      pypi_0    pypi
    requests                  2.28.0                   pypi_0    pypi
    scikit-image              0.19.3                   pypi_0    pypi
    scipy                     1.8.1                    pypi_0    pypi
    secretstorage             3.3.2                    pypi_0    pypi
    semantic-version          2.10.0                   pypi_0    pypi
    setuptools                62.6.0           py39hf3d152e_0    conda-forge
    six                       1.16.0                   pypi_0    pypi
    snowballstemmer           2.2.0                    pypi_0    pypi
    soupsieve                 2.3.2.post1              pypi_0    pypi
    spherical-geometry        1.2.22                   pypi_0    pypi
    sphinx                    5.0.2                    pypi_0    pypi
    sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
    sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
    sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
    sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
    sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
    sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
    sqlite                    3.38.5               h4ff8645_0    conda-forge
    stack-data                0.3.0                    pypi_0    pypi
    stcal                     0.7.3                    pypi_0    pypi
    stdatamodels              0.2.4                    pypi_0    pypi
    stpipe                    0.3.3                    pypi_0    pypi
    stsci-image               2.3.5                    pypi_0    pypi
    stsci-imagestats          1.6.3                    pypi_0    pypi
    stsci-stimage             0.2.5                    pypi_0    pypi
    svo-filters               0.4.3                    pypi_0    pypi
    tifffile                  2022.5.4                 pypi_0    pypi
    tk                        8.6.12               h27826a3_0    conda-forge
    tomli                     2.0.1                    pypi_0    pypi
    toolz                     0.11.2                   pypi_0    pypi
    tornado                   6.1                      pypi_0    pypi
    tqdm                      4.64.0                   pypi_0    pypi
    traitlets                 5.3.0                    pypi_0    pypi
    tweakwcs                  0.7.4                    pypi_0    pypi
    typing-extensions         4.2.0                    pypi_0    pypi
    tzdata                    2022a                h191b570_0    conda-forge
    uncertainties             3.1.7                    pypi_0    pypi
    urllib3                   1.26.9                   pypi_0    pypi
    wcwidth                   0.2.5                    pypi_0    pypi
    webencodings              0.5.1                    pypi_0    pypi
    wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
    xarray                    2022.3.0                 pypi_0    pypi
    xz                        5.2.5                h516909a_1    conda-forge
    zipp                      3.8.0                    pypi_0    pypi
    zlib                      1.2.12               h166bdaf_1    conda-forge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jovian-explorer** [comment]
Output from stage 2 - 

![fig2101_file1_x1dints](https://user-images.githubusercontent.com/98839532/178661195-124e913a-da7b-4d5f-be4d-f1b8851a7a9f.png)

**Comment by jovian-explorer** [comment]
Outputs from Stage 3 -
![fig3101-2D_LC](https://user-images.githubusercontent.com/98839532/178661363-00cd5feb-66a0-4e73-9d9f-b8d0cf8d9855.png)
![fig3301_file0_int00_ImageAndBackground](https://user-images.githubusercontent.com/98839532/178661368-27609238-9a29-4092-a11c-9a026e21ded5.png)
![fig3302_file0_int00_Spectrum](https://user-images.githubusercontent.com/98839532/178661369-7d9296ce-e94e-4cd2-a1c0-9ab36bb516c7.png)
![fig3303_file0_source_pos](https://user-images.githubusercontent.com/98839532/178661371-e3506913-1bb3-4106-9ddd-70934f6f05d2.png)
![fig3304_file0_int00_Profile](https://user-images.githubusercontent.com/98839532/178661374-6d26e714-3551-4260-bcfd-3b28d7891d13.png)

**Comment by jovian-explorer** [comment]
I understand. Thanks for your help!!

**Comment by jovian-explorer** [comment]
Just a heads up, there is something wrong going on with the GitHub bot I think, because it assigned NIRSpec tag to my issue, even when clearly there was not.

**Comment by taylorbell57** [comment]
Yeah, that's semi-intended behavior since you said NIRSpec in your first message
