### ISSUE TITLE
NIRSpec Stage 3 showing issue

### ISSUE THREAD

**Issue by jovian-explorer** [kevin218/Eureka#388]
### Instrument

NIRSpec (Stages 1-3)

### What happened?

Stage 3 NIRSpec giving error after the latest update tomorrow. Was working fine before that. I had updated Eureka! last night after the meet yesterday. Before that, it was working perfectly fine.

### Error traceback output

    Starting Stage 3 Reduction
    
    Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage2/S2_2022-07-15_wasp39b_run2/
    Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage3/S3_2022-07-15_wasp39b_run3/ap6_bg7/
    Using ap=6, bg=7
    Copying S3 control file
    Traceback (most recent call last):
      File "/home/keshav/Data/JWST-Sim/NIRSpec/run_eureka.py", line 27, in <module>
        s3_spec, s3_meta = s3.reduce(eventlabel, ecf_path=ecf_path,s2_meta=s2_meta)
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py", line 156, in reduce
        meta = util.readfiles(meta)
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/lib/util.py", line 43, in readfiles
        with fits.open(meta.segment_list[-1]) as hdulist:
    IndexError: list index out of range

### What operating system are you using?

linux ubuntu 20.04

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

    (eureka) keshav@dev:~/Data/JWST-Sim/NIRSpec$ conda list
    # packages in environment at /home/keshav/anaconda3/envs/eureka:
    #
    # Name                    Version                   Build  Channel
    _libgcc_mutex             0.1                 conda_forge    conda-forge
    _openmp_mutex             4.5                       2_gnu    conda-forge
    alabaster                 0.7.12                   pypi_0    pypi
    asdf                      2.12.0                   pypi_0    pypi
    asdf-astropy              0.2.1                    pypi_0    pypi
    asdf-coordinates-schemas  0.1.0                    pypi_0    pypi
    asdf-standard             1.0.2                    pypi_0    pypi
    asdf-transform-schemas    0.2.2                    pypi_0    pypi
    asdf-wcs-schemas          0.1.1                    pypi_0    pypi
    asteval                   0.9.27                   pypi_0    pypi
    astraeus                  0.2                      pypi_0    pypi
    astropy                   5.1                      pypi_0    pypi
    astropy-healpix           0.6                      pypi_0    pypi
    astroquery                0.4.6                    pypi_0    pypi
    astroscrappy              1.1.0                    pypi_0    pypi
    asttokens                 2.0.5                    pypi_0    pypi
    attrs                     21.4.0                   pypi_0    pypi
    babel                     2.10.3                   pypi_0    pypi
    backcall                  0.2.0                    pypi_0    pypi
    batman-package            2.4.9                    pypi_0    pypi
    bayesicfitting            3.0.1                    pypi_0    pypi
    beautifulsoup4            4.11.1                   pypi_0    pypi
    bokeh                     2.4.3                    pypi_0    pypi
    bottleneck                1.3.4                    pypi_0    pypi
    ca-certificates           2022.6.15            ha878542_0    conda-forge
    ccdproc                   2.3.1                    pypi_0    pypi
    celerite                  0.4.2                    pypi_0    pypi
    certifi                   2022.6.15                pypi_0    pypi
    cffi                      1.15.0                   pypi_0    pypi
    cftime                    1.6.0                    pypi_0    pypi
    charset-normalizer        2.0.12                   pypi_0    pypi
    cloudpickle               2.1.0                    pypi_0    pypi
    corner                    2.2.1                    pypi_0    pypi
    crds                      11.16.5                  pypi_0    pypi
    cryptography              37.0.2                   pypi_0    pypi
    cycler                    0.11.0                   pypi_0    pypi
    cython                    0.29.30                  pypi_0    pypi
    dask                      2022.6.0                 pypi_0    pypi
    decorator                 5.1.1                    pypi_0    pypi
    docutils                  0.18.1                   pypi_0    pypi
    drizzle                   1.13.4                   pypi_0    pypi
    dynesty                   1.2.3                    pypi_0    pypi
    emcee                     3.1.2                    pypi_0    pypi
    eureka                    0.2                      pypi_0    pypi
    executing                 0.8.3                    pypi_0    pypi
    exotic-ld                 2.0.0                    pypi_0    pypi
    filelock                  3.7.1                    pypi_0    pypi
    fonttools                 4.33.3                   pypi_0    pypi
    fsspec                    2022.5.0                 pypi_0    pypi
    future                    0.18.2                   pypi_0    pypi
    george                    0.4.0                    pypi_0    pypi
    gwcs                      0.18.1                   pypi_0    pypi
    h5netcdf                  1.0.0                    pypi_0    pypi
    h5py                      3.1.0                    pypi_0    pypi
    html5lib                  1.1                      pypi_0    pypi
    idna                      3.3                      pypi_0    pypi
    imageio                   2.19.3                   pypi_0    pypi
    imagesize                 1.3.0                    pypi_0    pypi
    importlib-metadata        4.11.4                   pypi_0    pypi
    iniconfig                 1.1.1                    pypi_0    pypi
    ipython                   8.4.0                    pypi_0    pypi
    jedi                      0.18.1                   pypi_0    pypi
    jeepney                   0.8.0                    pypi_0    pypi
    jinja2                    3.1.2                    pypi_0    pypi
    jmespath                  1.0.1                    pypi_0    pypi
    jsonschema                4.7.2                    pypi_0    pypi
    jwst                      1.6.0                    pypi_0    pypi
    keyring                   23.6.0                   pypi_0    pypi
    kiwisolver                1.4.3                    pypi_0    pypi
    ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
    libffi                    3.4.2                h7f98852_5    conda-forge
    libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
    libgomp                   12.1.0              h8d9b700_16    conda-forge
    libzlib                   1.2.12               h166bdaf_1    conda-forge
    lmfit                     1.0.3                    pypi_0    pypi
    locket                    1.0.0                    pypi_0    pypi
    lxml                      4.9.0                    pypi_0    pypi
    markupsafe                2.1.1                    pypi_0    pypi
    matplotlib                3.5.2                    pypi_0    pypi
    matplotlib-inline         0.1.3                    pypi_0    pypi
    ncurses                   6.3                  h27087fc_1    conda-forge
    netcdf4                   1.5.8                    pypi_0    pypi
    networkx                  2.8.4                    pypi_0    pypi
    numpy                     1.23.0                   pypi_0    pypi
    numpydoc                  1.4.0                    pypi_0    pypi
    openssl                   3.0.4                h166bdaf_0    conda-forge
    packaging                 21.3                     pypi_0    pypi
    pandas                    1.4.3                    pypi_0    pypi
    parsley                   1.3                      pypi_0    pypi
    parso                     0.8.3                    pypi_0    pypi
    partd                     1.2.0                    pypi_0    pypi
    pexpect                   4.8.0                    pypi_0    pypi
    photutils                 1.5.0                    pypi_0    pypi
    pickleshare               0.7.5                    pypi_0    pypi
    pillow                    9.1.1                    pypi_0    pypi
    pip                       22.1.2             pyhd8ed1ab_0    conda-forge
    pluggy                    1.0.0                    pypi_0    pypi
    poppy                     1.0.2                    pypi_0    pypi
    prompt-toolkit            3.0.29                   pypi_0    pypi
    psutil                    5.9.1                    pypi_0    pypi
    ptyprocess                0.7.0                    pypi_0    pypi
    pure-eval                 0.2.2                    pypi_0    pypi
    py                        1.11.0                   pypi_0    pypi
    pycparser                 2.21                     pypi_0    pypi
    pyerfa                    2.0.0.1                  pypi_0    pypi
    pygments                  2.12.0                   pypi_0    pypi
    pyparsing                 3.0.9                    pypi_0    pypi
    pyrsistent                0.18.1                   pypi_0    pypi
    pysynphot                 2.0.0                    pypi_0    pypi
    pytest                    7.1.2                    pypi_0    pypi
    python                    3.9.7           hf930737_3_cpython    conda-forge
    python-dateutil           2.8.2                    pypi_0    pypi
    python_abi                3.9                      2_cp39    conda-forge
    pytz                      2022.1                   pypi_0    pypi
    pyvo                      1.3                      pypi_0    pypi
    pywavelets                1.3.0                    pypi_0    pypi
    pyyaml                    6.0                      pypi_0    pypi
    readline                  8.1.2                h0f457ee_0    conda-forge
    reproject                 0.8                      pypi_0    pypi
    requests                  2.28.0                   pypi_0    pypi
    scikit-image              0.19.3                   pypi_0    pypi
    scipy                     1.8.1                    pypi_0    pypi
    secretstorage             3.3.2                    pypi_0    pypi
    semantic-version          2.10.0                   pypi_0    pypi
    setuptools                62.6.0           py39hf3d152e_0    conda-forge
    six                       1.16.0                   pypi_0    pypi
    snowballstemmer           2.2.0                    pypi_0    pypi
    soupsieve                 2.3.2.post1              pypi_0    pypi
    spherical-geometry        1.2.22                   pypi_0    pypi
    sphinx                    5.0.2                    pypi_0    pypi
    sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
    sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
    sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
    sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
    sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
    sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
    sqlite                    3.38.5               h4ff8645_0    conda-forge
    stack-data                0.3.0                    pypi_0    pypi
    stcal                     1.0.0                    pypi_0    pypi
    stdatamodels              0.4.3                    pypi_0    pypi
    stpipe                    0.4.0                    pypi_0    pypi
    stsci-image               2.3.5                    pypi_0    pypi
    stsci-imagestats          1.6.3                    pypi_0    pypi
    stsci-stimage             0.2.5                    pypi_0    pypi
    svo-filters               0.4.3                    pypi_0    pypi
    tifffile                  2022.5.4                 pypi_0    pypi
    tk                        8.6.12               h27826a3_0    conda-forge
    tomli                     2.0.1                    pypi_0    pypi
    toolz                     0.11.2                   pypi_0    pypi
    tornado                   6.1                      pypi_0    pypi
    tqdm                      4.64.0                   pypi_0    pypi
    traitlets                 5.3.0                    pypi_0    pypi
    tweakwcs                  0.7.4                    pypi_0    pypi
    typing-extensions         4.2.0                    pypi_0    pypi
    tzdata                    2022a                h191b570_0    conda-forge
    uncertainties             3.1.7                    pypi_0    pypi
    urllib3                   1.26.9                   pypi_0    pypi
    wcwidth                   0.2.5                    pypi_0    pypi
    webencodings              0.5.1                    pypi_0    pypi
    wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
    wiimatch                  0.2.1                    pypi_0    pypi
    xarray                    2022.3.0                 pypi_0    pypi
    xz                        5.2.5                h516909a_1    conda-forge
    zipp                      3.8.0                    pypi_0    pypi
    zlib                      1.2.12               h166bdaf_1    conda-forge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Hmm, I think that could only happen if there are no FITS files found in the Stage2 input folder. There is a bug here since a better error message should be output if there are no files found, but the ultimate bug seems to be that it didn't find any FITS files with the suffix you entered in the ECF

**Comment by jovian-explorer** [comment]
Actually, I am giving it input as rateints file (One of the tiny datasets from simulations), but something still is not working properly.

**Comment by jovian-explorer** [comment]
This is my stage 2 ECF - 

    # Eureka! Control File for Stage 2: Data Reduction
    
    # Stage 2 Documentation: https://eurekadocs.readthedocs.io/en/latest/ecf.html#stage-2
    
    suffix                  rateints    # Data file suffix
    
    # Controls the cross-dispersion extraction
    slit_y_low              -1      # Use None to rely on the default parameters
    slit_y_high             50      # Use None to rely on the default parameters
    
    # Modify the existing file to change the dispersion extraction - FIX: DOES NOT WORK CURRENTLY
    waverange_start         6e-08   # Use None to rely on the default parameters
    waverange_end           6e-06   # Use None to rely on the default parameters
    
    # Note: different instruments and modes will use different steps by default
    skip_bkg_subtract       False    # Not run for TSO observations
    skip_imprint_subtract   True    # Not run for NIRSpec Fixed Slit
    skip_msa_flagging       True    # Not run for NIRSpec Fixed Slit
    skip_extract_2d         False
    skip_srctype            False
    skip_master_background  True    # Not run for NIRSpec Fixed Slit
    skip_wavecorr           False
    skip_flat_field         True    # ***NOTE*** At the time the NIRSpec ERS Hackathon simulated data was created, this step did not work correctly and is by default turned off.
    skip_straylight         True    # Not run for NIRSpec Fixed Slit
    skip_fringe             True    # Not run for NIRSpec Fixed Slit
    skip_pathloss           True    # Not run for TSO observations
    skip_barshadow          True    # Not run for NIRSpec Fixed Slit
    skip_photom             True	# Recommended to skip to get better uncertainties out of Stage 3.
    skip_resample           True    # Not run for TSO observations
    skip_cube_build         True    # Not run for NIRSpec Fixed Slit
    skip_extract_1d         True
    
    # Diagnostics
    testing_S2              True
    hide_plots              False   # If True, plots will automatically be closed rather than popping up
    # Project directory
    topdir                  /home/keshav/Data/JWST-Sim/NIRSpec
    
    # Directories relative to topdir
    inputdir                /Stage1
    outputdir               /Stage2

**Comment by jovian-explorer** [comment]
As I understand, Stage 2 will take FITS file with a rateints suffix as an input and give out a FITS file with calints prefix for stage 3. Stage 2 is generating the required calints.FITS but stage 3 is not accepting it for some reason.

**Comment by jovian-explorer** [comment]
![Uploading Screenshot from 2022-07-15 23-36-02.png…]()

**Comment by taylorbell57** [comment]
Yeah, the fact that the S2 output filename is just _calints.fits is almost certainly to be an issue. No idea how that could have happened

**Comment by jovian-explorer** [comment]
Oh..  I ran the pipeline again just now, but a new error some how. 
    
    Starting Stage 3 Reduction
    
    Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage2/S2_2022-07-15_wasp39b_run5/
    Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage3/S3_2022-07-15_wasp39b_run6/ap6_bg7/
    Using ap=6, bg=7
    Copying S3 control file
    
    Found 1 data file(s) ending in calints.fits
    WARNING: Are you using real JWST data? If so, you should edit the flag_bg() function in nirspec.py and look at Issue #193 on Github!
    Starting file 1 of 1
      WARNING: The timestamps for the simulated NIRSpec data are currently
               hardcoded because they are not in the .fits files themselves
    Traceback (most recent call last):
      File "/home/keshav/Data/JWST-Sim/NIRSpec/run_eureka.py", line 27, in <module>
        s3_spec, s3_meta = s3.reduce(eventlabel, ecf_path=ecf_path,s2_meta=s2_meta)
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py", line 249, in reduce
        if meta.record_ypos:
    AttributeError: 'MetaClass' object has no attribute 'record_ypos'

**Comment by taylorbell57** [comment]
If you're using the newer version of the pipeline, you'll need to update your ECF to include the new settings that were added (record_ypos in stage3 and recordDrift in S4, potentially also compute_ld and related parameters in S4)

**Comment by jovian-explorer** [comment]
Ohh so that's where I messed up. Sorry for this. Let me work with the changes. If it works out, I'll close the issue.
Thanks!!

**Comment by jovian-explorer** [comment]
Traceback (most recent call last):
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/exotic_ld/ld_computation.py", line 195, in _match_3d_stellar_model
        sav = readsav(os.path.join(stellar_data_path, load_file))
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/scipy/io/_idl.py", line 738, in readsav
        f = open(file_name, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/home/User/exotic-ld_data/3DGrid/mmu_t60g40m00v05.flx'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/keshav/Data/JWST-Sim/NIRSpec/run_eureka.py", line 29, in <module>
        s4_spec, s4_lc, s4_meta = s4.genlc(eventlabel, ecf_path=ecf_path,
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S4_generate_lightcurves/s4_genLC.py", line 411, in genlc
        generate_LD.exotic_ld(meta, spec)
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S4_generate_lightcurves/generate_LD.py", line 50, in exotic_ld
        sld = StellarLimbDarkening(meta.metallicity, meta.teff, meta.logg,
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/exotic_ld/ld_computation.py", line 74, in __init__
        self._match_3d_stellar_model()
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/exotic_ld/ld_computation.py", line 197, in _match_3d_stellar_model
        raise FileNotFoundError(
    FileNotFoundError: File mmu_t60g40m00v05.flx, corresponding to M_H=0.0, Teff=6000, and logg=4.0 does not exist in the stellar models. 
     Please try a different combination of stellar parameters.
