### ISSUE TITLE
[Bug]: Issue with dynesty in stage 5

### ISSUE THREAD

**Issue by jovian-explorer** [kevin218/Eureka#401]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Other (any stage)

### What happened?

Stage 5 - Dynesty fit for NIRSpec works perfectly for only 1 channel. It crashes just when starting channel 2. This error, to be honest looks more like a bug to me. Idk why it even repeats even when I run the same dataset again without making any changes to my Eureka! installation.
Right now, my Eureka! installation is up to date.
Also, I thought I should mention this that the pipeline works perfectly well for lsq, as well as for emcee.
I just ran it for 2 channels in stage 4, and it ran perfectly. But as soon as I ran it again for 20, it crashed just like before. 

### Error traceback output

    Traceback (most recent call last):
      File "/home/keshav/Data/JWST-Sim/NIRSpec/run_eureka.py", line 32, in <module>
        s5_meta = s5.fitlc(eventlabel, ecf_path=ecf_path, s4_meta=s4_meta)
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S5_lightcurve_fitting/s5_fit.py", line 240, in fitlc
        meta, params = fit_channel(meta, time, flux, channel,
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S5_lightcurve_fitting/s5_fit.py", line 402, in fit_channel
        lc_model.fit(model, meta, log, fitter='dynesty')
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S5_lightcurve_fitting/lightcurve.py", line 148, in fit
        fit_model = self.fitter_func(self, model, meta, log, **kwargs)
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S5_lightcurve_fitting/fitters.py", line 919, in dynestyfitter
        plots.plot_corner(samples, lc, meta, freenames, fitter='dynesty')
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S5_lightcurve_fitting/plots_s5.py", line 211, in plot_corner
        fig = corner.corner(samples, fig=fig, quantiles=[0.16, 0.5, 0.84],
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/corner/corner.py", line 226, in corner
        return corner_impl(
      File "/home/keshav/anaconda3/envs/eureka/lib/python3.9/site-packages/corner/core.py", line 121, in corner_impl
        raise ValueError(
    ValueError: It looks like the parameter(s) in column(s) 9 have no dynamic range. Please provide a `range` argument.

### What operating system are you using?

linux ubuntu 20.04

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

    (eureka) keshav@dev:~/Data/JWST-Sim/NIRSpec$ conda list
    # packages in environment at /home/keshav/anaconda3/envs/eureka:
    #
    # Name                    Version                   Build  Channel
    _libgcc_mutex             0.1                 conda_forge    conda-forge
    _openmp_mutex             4.5                       2_gnu    conda-forge
    alabaster                 0.7.12                   pypi_0    pypi
    asdf                      2.12.0                   pypi_0    pypi
    asdf-astropy              0.2.1                    pypi_0    pypi
    asdf-coordinates-schemas  0.1.0                    pypi_0    pypi
    asdf-standard             1.0.2                    pypi_0    pypi
    asdf-transform-schemas    0.2.2                    pypi_0    pypi
    asdf-wcs-schemas          0.1.1                    pypi_0    pypi
    asteval                   0.9.27                   pypi_0    pypi
    astraeus                  0.2                      pypi_0    pypi
    astropy                   5.1                      pypi_0    pypi
    astropy-healpix           0.6                      pypi_0    pypi
    astroquery                0.4.6                    pypi_0    pypi
    astroscrappy              1.1.0                    pypi_0    pypi
    asttokens                 2.0.5                    pypi_0    pypi
    attrs                     21.4.0                   pypi_0    pypi
    babel                     2.10.3                   pypi_0    pypi
    backcall                  0.2.0                    pypi_0    pypi
    batman-package            2.4.9                    pypi_0    pypi
    bayesicfitting            3.0.1                    pypi_0    pypi
    beautifulsoup4            4.11.1                   pypi_0    pypi
    bokeh                     2.4.3                    pypi_0    pypi
    bottleneck                1.3.4                    pypi_0    pypi
    ca-certificates           2022.6.15            ha878542_0    conda-forge
    ccdproc                   2.3.1                    pypi_0    pypi
    celerite                  0.4.2                    pypi_0    pypi
    certifi                   2022.6.15                pypi_0    pypi
    cffi                      1.15.0                   pypi_0    pypi
    cftime                    1.6.0                    pypi_0    pypi
    charset-normalizer        2.0.12                   pypi_0    pypi
    cloudpickle               2.1.0                    pypi_0    pypi
    corner                    2.2.1                    pypi_0    pypi
    crds                      11.16.5                  pypi_0    pypi
    cryptography              37.0.2                   pypi_0    pypi
    cycler                    0.11.0                   pypi_0    pypi
    cython                    0.29.30                  pypi_0    pypi
    dask                      2022.6.0                 pypi_0    pypi
    decorator                 5.1.1                    pypi_0    pypi
    docutils                  0.18.1                   pypi_0    pypi
    drizzle                   1.13.4                   pypi_0    pypi
    dynesty                   1.2.3                    pypi_0    pypi
    emcee                     3.1.2                    pypi_0    pypi
    eureka                    0.2                      pypi_0    pypi
    executing                 0.8.3                    pypi_0    pypi
    exotic-ld                 2.0.0                    pypi_0    pypi
    filelock                  3.7.1                    pypi_0    pypi
    fonttools                 4.33.3                   pypi_0    pypi
    fsspec                    2022.5.0                 pypi_0    pypi
    future                    0.18.2                   pypi_0    pypi
    george                    0.4.0                    pypi_0    pypi
    gwcs                      0.18.1                   pypi_0    pypi
    h5netcdf                  1.0.0                    pypi_0    pypi
    h5py                      3.1.0                    pypi_0    pypi
    html5lib                  1.1                      pypi_0    pypi
    idna                      3.3                      pypi_0    pypi
    imageio                   2.19.3                   pypi_0    pypi
    imagesize                 1.3.0                    pypi_0    pypi
    importlib-metadata        4.11.4                   pypi_0    pypi
    iniconfig                 1.1.1                    pypi_0    pypi
    ipython                   8.4.0                    pypi_0    pypi
    jedi                      0.18.1                   pypi_0    pypi
    jeepney                   0.8.0                    pypi_0    pypi
    jinja2                    3.1.2                    pypi_0    pypi
    jmespath                  1.0.1                    pypi_0    pypi
    jsonschema                4.7.2                    pypi_0    pypi
    jwst                      1.6.0                    pypi_0    pypi
    keyring                   23.6.0                   pypi_0    pypi
    kiwisolver                1.4.3                    pypi_0    pypi
    ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
    libffi                    3.4.2                h7f98852_5    conda-forge
    libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
    libgomp                   12.1.0              h8d9b700_16    conda-forge
    libzlib                   1.2.12               h166bdaf_1    conda-forge
    lmfit                     1.0.3                    pypi_0    pypi
    locket                    1.0.0                    pypi_0    pypi
    lxml                      4.9.0                    pypi_0    pypi
    markupsafe                2.1.1                    pypi_0    pypi
    matplotlib                3.5.2                    pypi_0    pypi
    matplotlib-inline         0.1.3                    pypi_0    pypi
    ncurses                   6.3                  h27087fc_1    conda-forge
    netcdf4                   1.5.8                    pypi_0    pypi
    networkx                  2.8.4                    pypi_0    pypi
    numpy                     1.23.0                   pypi_0    pypi
    numpydoc                  1.4.0                    pypi_0    pypi
    openssl                   3.0.4                h166bdaf_0    conda-forge
    packaging                 21.3                     pypi_0    pypi
    pandas                    1.4.3                    pypi_0    pypi
    parsley                   1.3                      pypi_0    pypi
    parso                     0.8.3                    pypi_0    pypi
    partd                     1.2.0                    pypi_0    pypi
    pexpect                   4.8.0                    pypi_0    pypi
    photutils                 1.5.0                    pypi_0    pypi
    pickleshare               0.7.5                    pypi_0    pypi
    pillow                    9.1.1                    pypi_0    pypi
    pip                       22.1.2             pyhd8ed1ab_0    conda-forge
    pluggy                    1.0.0                    pypi_0    pypi
    poppy                     1.0.2                    pypi_0    pypi
    prompt-toolkit            3.0.29                   pypi_0    pypi
    psutil                    5.9.1                    pypi_0    pypi
    ptyprocess                0.7.0                    pypi_0    pypi
    pure-eval                 0.2.2                    pypi_0    pypi
    py                        1.11.0                   pypi_0    pypi
    pycparser                 2.21                     pypi_0    pypi
    pyerfa                    2.0.0.1                  pypi_0    pypi
    pygments                  2.12.0                   pypi_0    pypi
    pyparsing                 3.0.9                    pypi_0    pypi
    pyrsistent                0.18.1                   pypi_0    pypi
    pysynphot                 2.0.0                    pypi_0    pypi
    pytest                    7.1.2                    pypi_0    pypi
    python                    3.9.7           hf930737_3_cpython    conda-forge
    python-dateutil           2.8.2                    pypi_0    pypi
    python_abi                3.9                      2_cp39    conda-forge
    pytz                      2022.1                   pypi_0    pypi
    pyvo                      1.3                      pypi_0    pypi
    pywavelets                1.3.0                    pypi_0    pypi
    pyyaml                    6.0                      pypi_0    pypi
    readline                  8.1.2                h0f457ee_0    conda-forge
    reproject                 0.8                      pypi_0    pypi
    requests                  2.28.0                   pypi_0    pypi
    scikit-image              0.19.3                   pypi_0    pypi
    scipy                     1.8.1                    pypi_0    pypi
    secretstorage             3.3.2                    pypi_0    pypi
    semantic-version          2.10.0                   pypi_0    pypi
    setuptools                62.6.0           py39hf3d152e_0    conda-forge
    six                       1.16.0                   pypi_0    pypi
    snowballstemmer           2.2.0                    pypi_0    pypi
    soupsieve                 2.3.2.post1              pypi_0    pypi
    spherical-geometry        1.2.22                   pypi_0    pypi
    sphinx                    5.0.2                    pypi_0    pypi
    sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
    sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
    sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
    sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
    sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
    sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
    sqlite                    3.38.5               h4ff8645_0    conda-forge
    stack-data                0.3.0                    pypi_0    pypi
    stcal                     1.0.0                    pypi_0    pypi
    stdatamodels              0.4.3                    pypi_0    pypi
    stpipe                    0.4.0                    pypi_0    pypi
    stsci-image               2.3.5                    pypi_0    pypi
    stsci-imagestats          1.6.3                    pypi_0    pypi
    stsci-stimage             0.2.5                    pypi_0    pypi
    svo-filters               0.4.3                    pypi_0    pypi
    tifffile                  2022.5.4                 pypi_0    pypi
    tk                        8.6.12               h27826a3_0    conda-forge
    tomli                     2.0.1                    pypi_0    pypi
    toolz                     0.11.2                   pypi_0    pypi
    tornado                   6.1                      pypi_0    pypi
    tqdm                      4.64.0                   pypi_0    pypi
    traitlets                 5.3.0                    pypi_0    pypi
    tweakwcs                  0.7.4                    pypi_0    pypi
    typing-extensions         4.2.0                    pypi_0    pypi
    tzdata                    2022a                h191b570_0    conda-forge
    uncertainties             3.1.7                    pypi_0    pypi
    urllib3                   1.26.9                   pypi_0    pypi
    wcwidth                   0.2.5                    pypi_0    pypi
    webencodings              0.5.1                    pypi_0    pypi
    wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
    wiimatch                  0.2.1                    pypi_0    pypi
    xarray                    2022.3.0                 pypi_0    pypi
    xz                        5.2.5                h516909a_1    conda-forge
    zipp                      3.8.0                    pypi_0    pypi
    zlib                      1.2.12               h166bdaf_1    conda-forge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Can you please look at the log and the figures output for the channel that did work and for the channel that didn't? If you can't figure out what might have gone wrong using those, can you please copy those figures and logs here so that I have more to work with (as of right now I have nothing to go off of to try to understand why this might have happened)

**Comment by jovian-explorer** [comment]
See, what happens is if I set `nspecchan       2` in stage 4 ECF, the pipeline runs perfectly. Essentially, doing the dynesty fit for both channels.
This is my log file for when I had set the number of channels to 2 - 

    
    Starting Stage 2 Reduction
    Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage1/
    Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage2/S2_2022-07-18_wasp39b_run1/
    Copying S2 control file
    
    Found 1 data file(s) ending in rateints.fits
    Starting file 1 of 1
    Editing (in place) the waverange in the input file
    Running the Spec2Pipeline
    
    
    Generating x1dints figure
    Saving Metadata
    
    Total time (min): 0.59
    
    Starting Stage 3 Reduction
    
    Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage2/S2_2022-07-18_wasp39b_run1/
    Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage3/S3_2022-07-18_wasp39b_run1/ap6_bg7/
    Using ap=6, bg=7
    Copying S3 control file
    
    Found 1 data file(s) ending in calints.fits
    WARNING: Are you using real JWST data? If so, you should edit the flag_bg() function in nirspec.py and look at Issue #193 on Github!
    Starting file 1 of 1
      Locating source position...
        Source position on detector is row 13.
      Automatically getting reference files to convert units to electrons...
      Converting from data numbers per second (DN/s) to electrons...
      Masking NaNs in data arrays...
      Performing background outlier rejection...
      Performing background subtraction...
      Creating figures for background subtraction...
      Extracting aperture region...
      Performing optimal spectral extraction...
      Creating figures for optimal spectral extraction
    Stage 3 MAD = 7528 ppm
    Generating figure
    Saving Metadata
    
    Total time (min): 1.19
    
    Starting Stage 4: Generate Light Curves
    
    Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage3/S3_2022-07-18_wasp39b_run1/ap6_bg7/
    Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage4/S4_2022-07-18_wasp39b_run1/ap6_bg7/
    Copying S4 control file
    Loading S3 save file:
    /home/keshav/Data/JWST-Sim/NIRSpec/Stage3/S3_2022-07-18_wasp39b_run1/ap6_bg7/S3_wasp39b_ap6_bg7_SpecData.h5
    Stage 4 MAD = 6822.64 ppm
    Generating light curves
      Bandpass 0 = 1.000 - 3.000
        MAD = 1975 ppm
      Bandpass 1 = 3.000 - 5.000
        MAD = 1309 ppm
    Saving results...
    
    Total time (min): 0.05
    Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage4/S4_2022-07-18_wasp39b_run1/ap6_bg7/
    Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage5/S5_2022-07-18_wasp39b_run1/ap6_bg7/
    Copying S5 control file
    Copying S5 parameter control file
    
    Starting Channel 1 of 2
    
    =========================
    Starting dynesty fit.
    Starting lnprob: -138.63172693859514
    Running dynesty...
    
    Summary
    =======
    nlive: 256
    niter: 6803
    ncall: 189914
    eff(%):  3.717
    logz: 167.572 +/-  0.335
    
    Number of posterior samples is 7059
    Ending lnprob: 202.31911990493
    Reduced Chi-squared: 1.4656571760087815
    
    DYNESTY RESULTS:
    rp: 0.14760409218408815 (+0.002235553378843791, -0.002611723057948573)
    per: 4.055259569450104 (+9.179344645282583e-06, -8.991813940539828e-06)
    t0: 57394.52445762667 (+0.0002655407370184548, -0.0002563394155004062)
    inc: 87.95057089943018 (+0.22947401161214032, -0.21321850009783816)
    a: 10.90574880052681 (+0.18411480296399851, -0.18786047633996006)
    u1: 0.5933700127301313 (+0.18387797812063655, -0.09174928855894848)
    u2: 0.8499078289951327 (+0.10481153226249951, -0.12944645084277007)
    c0: 1.0145809078128256 (+0.00018633558517877624, -0.00020364968169594988)
    c1: 0.0005411222212428411 (+0.002369653706229081, -0.0024273373791259155)
    scatter_ppm: 610.2525732413305 (+62.70887488652636, -51.34586213096179)
    
    Completed dynesty fit.
    -------------------------
    =========================
    Saving results
    
    Starting Channel 2 of 2
    
    =========================
    Starting dynesty fit.
    Starting lnprob: 202.66864928895313
    Running dynesty...
    
    Summary
    =======
    nlive: 256
    niter: 7344
    ncall: 206168
    eff(%):  3.686
    logz: 181.370 +/-  0.340
    
    Number of posterior samples is 7600
    Ending lnprob: 218.00659777940348
    Reduced Chi-squared: 0.960393113234776
    
    DYNESTY RESULTS:
    rp: 0.1504525088479322 (+0.00201107105133963, -0.002114943099100486)
    per: 4.055259744469044 (+9.48729987015895e-06, -9.895846267760078e-06)
    t0: 57394.52428475957 (+0.00017225973715540022, -0.00018172030831919983)
    inc: 87.923436448259 (+0.20374099875716922, -0.2027191600056426)
    a: 11.072356657350205 (+0.16674553490235766, -0.1742011775391905)
    u1: 0.5956559151597773 (+0.17122977022136743, -0.13907316030051087)
    u2: 0.6546229718350703 (+0.13624222733731395, -0.11603047571986969)
    c0: 1.0146316956649988 (+0.0001484504247479812, -0.00014575687710549623)
    c1: 0.0029893744691343324 (+0.0018437735860440518, -0.001725258771509054)
    scatter_ppm: 451.3386919616654 (+56.20171553555622, -55.83074844743561)
    
    Completed dynesty fit.
    -------------------------
    =========================
    Saving results
    
    Total time (min): 2.99


But, if I set it to `nspecchan       20` in S4 ECF, for some reason, the pipeline crashes after only doing the dynesty fit for the first channel. It simply crashes after that. For 20 channels, this is the log file - 


	Starting Stage 2 Reduction
	Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage1/
	Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage2/S2_2022-07-18_wasp39b_run2/
	Copying S2 control file

	Found 1 data file(s) ending in rateints.fits
	Starting file 1 of 1
	Editing (in place) the waverange in the input file
	Running the Spec2Pipeline


	Generating x1dints figure
	Saving Metadata

	Total time (min): 0.63

	Starting Stage 3 Reduction

	Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage2/S2_2022-07-18_wasp39b_run2/
	Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage3/S3_2022-07-18_wasp39b_run2/ap6_bg7/
	Using ap=6, bg=7
	Copying S3 control file

	Found 1 data file(s) ending in calints.fits
	WARNING: Are you using real JWST data? If so, you should edit the flag_bg() function in nirspec.py and look at Issue #193 on Github!
	Starting file 1 of 1
	  Locating source position...
	    Source position on detector is row 13.
	  Automatically getting reference files to convert units to electrons...
	  Converting from data numbers per second (DN/s) to electrons...
	  Masking NaNs in data arrays...
	  Performing background outlier rejection...
	  Performing background subtraction...
	  Creating figures for background subtraction...
	  Extracting aperture region...
	  Performing optimal spectral extraction...
	  Creating figures for optimal spectral extraction
	Stage 3 MAD = 7528 ppm
	Generating figure
	Saving Metadata

	Total time (min): 1.15

	Starting Stage 4: Generate Light Curves

	Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage3/S3_2022-07-18_wasp39b_run2/ap6_bg7/
	Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage4/S4_2022-07-18_wasp39b_run2/ap6_bg7/
	Copying S4 control file
	Loading S3 save file:
	/home/keshav/Data/JWST-Sim/NIRSpec/Stage3/S3_2022-07-18_wasp39b_run2/ap6_bg7/S3_wasp39b_ap6_bg7_SpecData.h5
	Stage 4 MAD = 6822.64 ppm
	Generating light curves
	  Bandpass 0 = 1.000 - 1.200
	    MAD = 10232 ppm
	  Bandpass 1 = 1.200 - 1.400
	    MAD = 7291 ppm
	  Bandpass 2 = 1.400 - 1.600
	    MAD = 3439 ppm
	  Bandpass 3 = 1.600 - 1.800
	    MAD = 2920 ppm
	  Bandpass 4 = 1.800 - 2.000
	    MAD = 3035 ppm
	  Bandpass 5 = 2.000 - 2.200
	    MAD = 2216 ppm
	  Bandpass 6 = 2.200 - 2.400
	    MAD = 2077 ppm
	  Bandpass 7 = 2.400 - 2.600
	    MAD = 1931 ppm
	  Bandpass 8 = 2.600 - 2.800
	    MAD = 2249 ppm
	  Bandpass 9 = 2.800 - 3.000
	    MAD = 2682 ppm
	  Bandpass 10 = 3.000 - 3.200
	    MAD = 2423 ppm
	  Bandpass 11 = 3.200 - 3.400
	    MAD = 1742 ppm
	  Bandpass 12 = 3.400 - 3.600
	    MAD = 2111 ppm
	  Bandpass 13 = 3.600 - 3.800
	    MAD = 2157 ppm
	  Bandpass 14 = 3.800 - 4.000
	    MAD = 2075 ppm
	  Bandpass 15 = 4.000 - 4.200
	    MAD = 1772 ppm
	  Bandpass 16 = 4.200 - 4.400
	    MAD = 2283 ppm
	  Bandpass 17 = 4.400 - 4.600
	    MAD = 1735 ppm
	  Bandpass 18 = 4.600 - 4.800
	    MAD = 3114 ppm
	  Bandpass 19 = 4.800 - 5.000
	    MAD = 7806 ppm
	Saving results...

	Total time (min): 0.24
	Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage4/S4_2022-07-18_wasp39b_run2/ap6_bg7/
	Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage5/S5_2022-07-18_wasp39b_run2/ap6_bg7/
	Copying S5 control file
	Copying S5 parameter control file

	Starting Channel 1 of 20

	=========================
	Starting dynesty fit.
	Starting lnprob: -8542.314163469147
	Running dynesty...

	Summary
	=======
	nlive: 256
	niter: 13029
	ncall: 376756
	eff(%):  3.526
	logz: -839.653 +/-  0.520

	Number of posterior samples is 13285
	Ending lnprob: -814.9260441333812
	Reduced Chi-squared: 88.54048556410201

	DYNESTY RESULTS:
	rp: 0.12506727940058424 (+5.47112355420154e-12, -1.9520055016819526e-10)
	per: 4.055261753410473 (+7.815970093361102e-14, -5.160316618457728e-13)
	t0: 57394.52587790211 (+0.0, -4.001776687800884e-10)
	inc: 87.48894735892476 (+1.927408277424547e-08, -2.8208546609675977e-10)
	a: 9.922295471175127 (+7.383675715288973e-08, -1.5515944085109368e-10)
	u1: 0.4170616031134358 (+1.783401204491497e-10, -1.4294560368721676e-08)
	u2: 0.6416090898963338 (+3.077174071108857e-10, -2.096554241326487e-08)
	c0: 1.0108791087118765 (+1.8937074131031295e-11, -8.200862211538151e-11)
	c1: 0.007497886279663579 (+4.89738158013231e-10, -7.663011197811542e-11)
	scatter_ppm: 1320.9536151601387 (+0.0, -0.0)

**Comment by taylorbell57** [comment]
Hmm, so I think the issue is likely to be with your `scatter_ppm` prior - the reason I expect this is that your fitted scatter_ppm for the 20 channel fit is only 1320 ppm, while I would expect something closer to 3200 ppm (given your MAD value from Stage 4). First, I recommend using `scatter_mult` instead of `scatter_ppm` now as the issue with `scatter_mult` should have been fixed. If you then set a Normal prior with a mean of something like 2 and a standard deviation of something like 2, then hopefully you'll get something that works regardless of the number of channels you used in Stage 4. If and only if you can't get `scatter_mult` to work, then I'd try increasing the mean and standard deviation of your prior on `scatter_ppm` for your 20 channel fits.

**Comment by jovian-explorer** [comment]
I am not sure if it is supposed to be this way, but in S5 EPF, I have to put this in manually - `t0    57394.52    'free'    57394.5    57394.55    U` (as you suggested in issue #326 ) everytime I update my Eureka! installation. 
Also, just wanted to know why the above error arises (probably in only my installation) even when I am using the tiny dataset, and latest ECF/EPF files, without any changes?

**Comment by jovian-explorer** [comment]
Although my code is running perfectly, I am leaving this issue open for the time being, as I am unsure if this error, or the question in my previous comment imply a bug, or simply another issue with whatever I keep on doing wrong.

**Comment by taylorbell57** [comment]
I'm not sure I understand your question about `t0` - that value is the linear ephemeris of the planet, and should be set to a value relevant to the observations you're looking at.

I'm not sure I understand your second question either - can you clarify what you mean?

**Comment by jovian-explorer** [comment]
See, what happened was, that when I had faced this issue previously, you had suggested that I make the above change in my S5 EPF. But, whenever I update my EPF file, I have to edit that file, and manually put this line (`t0 57394.52 'free' 57394.5 57394.55 U `) each time. 

As for my second question, what I mean is that why does this exact same issue arises again and again, if I am running the same FITS file, just with updated Eureka! version. And now that the code is working prefectly, was it something that was unique I had to change in my files, or was it something that is general knowledge for people working with this code?

The t0 value is from the S5 parameter file (EPF)

**Comment by jovian-explorer** [comment]
Yeah I understand that and in no way meant to disrespect any of you. I was just asking that last question as I am probably the newest and youngest ones (in terms of time spent on Eureka!) using this code. I understand that it may be getting hectic dealing with the number of issues I keep raising, and I am truly sorry, and thankful to you guys who keep on helping me out, even when most of it is probably fairly simple. Although, to be honest, I'll probably raising many more issues so please bear with me.

**Comment by taylorbell57** [comment]
Also, if you're going to look at the real JWST observations soon, please make sure you frequently check for updates as we're making near-daily edits at this point to fix known bugs with those files

**Comment by jovian-explorer** [comment]
Okay, will do. I update my installation on my system once every three days so far. Keeping in mind the updates that have and will be coming, I think I'll start updating it once daily from now on.
