### ISSUE TITLE
[Bug]: Minor issue: add exotic-ld data download to quick start documentation

### ISSUE THREAD

**Issue by MartianColonist** [kevin218/Eureka#407]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Light curve fitting (Stages 4-6)

### What happened?

Following the quick start guide, Eureka! fails at Stage 4 due to missing exotic-ld 3D stellar grid data.

A quick fix would be to add an instruction to download these data (https://zenodo.org/record/6344946#.YtWpcNLMKEB) and modify 'exotic_ld_direc' in 'S4_wasp39b.ecf' to point to the folder.

I also had to do two more steps to get Stages 5 and 6 to work:

1. In 'exotic_ld_direc/Sensitivity_files', I renamed 'JWST_NIRSpec_prism_throughput.csv' -> 'JWST_NIRSpec_Prism_throughput.csv'.
2. In 'S5_fit_par_wasp39b.epf', I changed 'limb_dark' from 'kipping2013' -> 'quadratic'.

Then everything ran perfectly. Thanks for the *great* code!

### Error traceback output

Starting Stage 4: Generate Light Curves

Input directory: /home/ryanmacdonald/code/Eureka/DataAnalysis/JWST/MyFirstEureka/Stage3/S3_2022-07-18_wasp39b_run1/ap6_bg7/
Output directory: /home/ryanmacdonald/code/Eureka/DataAnalysis/JWST/MyFirstEureka/Stage4/S4_2022-07-18_wasp39b_run1/ap6_bg7/
Copying S4 control file
Loading S3 save file:
/home/ryanmacdonald/code/Eureka/DataAnalysis/JWST/MyFirstEureka/Stage3/S3_2022-07-18_wasp39b_run1/ap6_bg7/S3_wasp39b_ap6_bg7_SpecData.h5
Finished loading parameters from /home/ryanmacdonald/code/Eureka/DataAnalysis/JWST/MyFirstEureka/Stage3/S3_2022-07-18_wasp39b_run1/ap6_bg7/S3_wasp39b_ap6_bg7_SpecData.h5
Stage 4 MAD = 5684.28 ppm
Generating light curves
  Bandpass 0 = 1.500 - 3.000
    MAD = 1531 ppm
  Bandpass 1 = 3.000 - 4.500
    MAD = 1323 ppm
Generating white-light light curve
  White-light Bandpass = 1.500 - 4.500
    MAD = 1322 ppm
Generating limb-darkening coefficients...
Traceback (most recent call last):
  File "/home/ryanmacdonald/anaconda3/envs/eureka/lib/python3.9/site-packages/exotic_ld/ld_computation.py", line 195, in _match_3d_stellar_model
    sav = readsav(os.path.join(stellar_data_path, load_file))
  File "/home/ryanmacdonald/anaconda3/envs/eureka/lib/python3.9/site-packages/scipy/io/_idl.py", line 738, in readsav
    f = open(file_name, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/User/exotic-ld_data/3DGrid/mmu_t60g40m00v05.flx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryanmacdonald/code/Eureka/demos/WASP-39b_DC/run_eureka.py", line 30, in <module>
    s4_spec, s4_lc, s4_meta = s4.genlc(eventlabel, ecf_path=ecf_path,
  File "/home/ryanmacdonald/code/Eureka/src/eureka/S4_generate_lightcurves/s4_genLC.py", line 415, in genlc
    generate_LD.exotic_ld(meta, spec)
  File "/home/ryanmacdonald/code/Eureka/src/eureka/S4_generate_lightcurves/generate_LD.py", line 50, in exotic_ld
    sld = StellarLimbDarkening(meta.metallicity, meta.teff, meta.logg,
  File "/home/ryanmacdonald/anaconda3/envs/eureka/lib/python3.9/site-packages/exotic_ld/ld_computation.py", line 74, in __init__
    self._match_3d_stellar_model()
  File "/home/ryanmacdonald/anaconda3/envs/eureka/lib/python3.9/site-packages/exotic_ld/ld_computation.py", line 197, in _match_3d_stellar_model
    raise FileNotFoundError(
FileNotFoundError: File mmu_t60g40m00v05.flx, corresponding to M_H=0.0, Teff=6000, and logg=4.0 does not exist in the stellar models. 
 Please try a different combination of stellar parameters.

### What operating system are you using?

Ubuntu 20.04

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
alabaster                 0.7.12                   pypi_0    pypi
asdf                      2.12.0                   pypi_0    pypi
asdf-astropy              0.2.1                    pypi_0    pypi
asdf-coordinates-schemas  0.1.0                    pypi_0    pypi
asdf-standard             1.0.2                    pypi_0    pypi
asdf-transform-schemas    0.2.2                    pypi_0    pypi
asdf-wcs-schemas          0.1.1                    pypi_0    pypi
asteval                   0.9.27                   pypi_0    pypi
astraeus                  0.2                      pypi_0    pypi
astropy                   5.1                      pypi_0    pypi
astropy-healpix           0.6                      pypi_0    pypi
astroquery                0.4.6                    pypi_0    pypi
astroscrappy              1.1.0                    pypi_0    pypi
asttokens                 2.0.5                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
babel                     2.10.3                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
batman-package            2.4.9                    pypi_0    pypi
bayesicfitting            3.0.1                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.3.5                    pypi_0    pypi
ca-certificates           2022.4.26            h06a4308_0  
ccdproc                   2.3.1                    pypi_0    pypi
celerite                  0.4.2                    pypi_0    pypi
certifi                   2022.6.15        py39h06a4308_0  
cffi                      1.15.1                   pypi_0    pypi
cftime                    1.6.1                    pypi_0    pypi
charset-normalizer        2.1.0                    pypi_0    pypi
cloudpickle               2.1.0                    pypi_0    pypi
corner                    2.2.1                    pypi_0    pypi
crds                      11.16.5                  pypi_0    pypi
cryptography              37.0.4                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.30                  pypi_0    pypi
dask                      2022.6.0                 pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
docutils                  0.18.1                   pypi_0    pypi
drizzle                   1.13.4                   pypi_0    pypi
dynesty                   1.2.3                    pypi_0    pypi
emcee                     3.1.2                    pypi_0    pypi
eureka                    0.3                       dev_0    <develop>
executing                 0.8.3                    pypi_0    pypi
exotic-ld                 2.0.0                    pypi_0    pypi
filelock                  3.7.1                    pypi_0    pypi
fonttools                 4.34.4                   pypi_0    pypi
fsspec                    2022.5.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
george                    0.4.0                    pypi_0    pypi
gwcs                      0.18.1                   pypi_0    pypi
h5netcdf                  1.0.1                    pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imageio                   2.19.5                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        4.12.0                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
ipython                   8.4.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jeepney                   0.8.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jsonschema                4.7.2                    pypi_0    pypi
jwst                      1.6.0                    pypi_0    pypi
keyring                   23.7.0                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
lmfit                     1.0.3                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3  
netcdf4                   1.6.0                    pypi_0    pypi
networkx                  2.8.4                    pypi_0    pypi
numpy                     1.23.1                   pypi_0    pypi
numpydoc                  1.4.0                    pypi_0    pypi
openssl                   1.1.1q               h7f8727e_0  
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.3                    pypi_0    pypi
parsley                   1.3                      pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.2.0                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
photutils                 1.5.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pip                       22.1.2           py39h06a4308_0  
pluggy                    1.0.0                    pypi_0    pypi
poppy                     1.0.3                    pypi_0    pypi
prompt-toolkit            3.0.30                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyerfa                    2.0.0.1                  pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    7.1.2                    pypi_0    pypi
python                    3.9.7                h12debd9_1  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pyvo                      1.3                      pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
reproject                 0.8                      pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.8.1                    pypi_0    pypi
secretstorage             3.3.2                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                61.2.0           py39h06a4308_0  
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
spherical-geometry        1.2.22                   pypi_0    pypi
sphinx                    5.0.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.38.5               hc218d9a_0  
stack-data                0.3.0                    pypi_0    pypi
stcal                     1.0.0                    pypi_0    pypi
stdatamodels              0.4.3                    pypi_0    pypi
stpipe                    0.4.1                    pypi_0    pypi
stsci-image               2.3.5                    pypi_0    pypi
stsci-imagestats          1.6.3                    pypi_0    pypi
stsci-stimage             0.2.5                    pypi_0    pypi
svo-filters               0.4.3                    pypi_0    pypi
tifffile                  2022.5.4                 pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.3.0                    pypi_0    pypi
tweakwcs                  0.7.4                    pypi_0    pypi
typing-extensions         4.3.0                    pypi_0    pypi
tzdata                    2022a                hda174b7_0  
uncertainties             3.1.7                    pypi_0    pypi
urllib3                   1.26.10                  pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
wiimatch                  0.2.1                    pypi_0    pypi
xarray                    2022.3.0                 pypi_0    pypi
xz                        5.2.5                h7f8727e_1  
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h7f8727e_2  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Ah yes, thanks for a reminder to add this - I knew it was missing, but had forgotten. Also note that you might want to change your limb darkening priors to either be fixed (if you want to use the exotic-ld values) or update the priors to span -1 to 1 or something like that (since quadratic limb darkening values can go negative) if you are just wanting to use the exotic-ld values as a starting point
