### ISSUE TITLE
[Enhancement]: 2D Lightcurve Minor Ticks

### ISSUE THREAD

**Issue by jbrande** [kevin218/Eureka#412]
### Instrument

Light curve fitting (Stages 4-6)

### What is your suggestion?

It would be nice if we had minor ticks on the wavelength axis for the 2D lightcurve plots. It would make excluding bad parts of the wings of the spectrum slightly easier.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Relatedly, I like having tick marks on all axes for even easier to read plots. I have the ticks on the top and right side point inward to look clean. I have code written for SPCA that I could likely copy-paste.
