### ISSUE TITLE
[Enhancement]: Describe how to do array of bg_hw/spec_hw on the readthedocs

### ISSUE THREAD

**Issue by meganmansfield** [kevin218/Eureka#413]
### Instrument

Other (any stage)

### What is your suggestion?

I noticed the readthedocs page doesn't explain how to set up an array of bg_hw and spec_hw values. It would be super useful to just add like one line explaining this!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
I documented this in a recent PR, so am now closing the issue
