### ISSUE TITLE
Mistake in the QuickStart docs?

### ISSUE THREAD

**Issue by catrionamurray** [kevin218/Eureka#422]
### Instrument

Other (any stage)

### What happened?

Part of JOSS review (https://github.com/openjournals/joss-reviews/issues/4503). I believe there's a small mistake in the Quickstart docs: 
https://eurekadocs.readthedocs.io/en/latest/quickstart.html

Where we set the `nlive` parameter: 

> As a compromise, let’s use 256 live points instead to get a fairly nice corner plot but also speed up the fit, so set the following in S5_fit_par_wasp39b.epf:

I think this file should be "S5_wasp39b.ecf", not the .epf file?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Ah good catch, and quick fix to make
