### ISSUE TITLE
Missing Science References in JOSS Paper

### ISSUE THREAD

**Issue by catrionamurray** [kevin218/Eureka#423]
### What happened?

In the JOSS paper (https://github.com/openjournals/joss-reviews/issues/4503) there are missing science references to JWST (and HST) and a lack of context. It would also be nice to have a very brief (1-2 line) introduction to JWST and its science for those who are unfamiliar given that this is an interdisciplinary journal.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by catrionamurray** [comment]
The `jwst` pipeline is also mentioned before it is referenced in the Stage Outline step, I would add the reference at its first mention.

**Comment by taylorbell57** [comment]
My edits just now should have resolved your above requests, so I'm marking this as closed for now, but please reopen if you feel there is anything missing still
