### ISSUE TITLE
Installation via environment file: ResolvePackageNotFound: - exotic-ld

### ISSUE THREAD

**Issue by mhooton** [kevin218/Eureka#427]
### Instrument

Other (any stage)

### What happened?

I'm attempting to install eureka using the environment.yml file, as my Macbook has an M1 chip. I get the following error, regarding the `exotic-ld` package. 

### Error traceback output

matthewhooton$ conda env create --file environment.yml --force
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - exotic-ld

### What operating system are you using?

Mac OS 12.5 Monterey

### What version of Python are you running?

Python 3.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Ah sorry, you'll need to use the latest version of the code that is on the main branch for that to work since we've yet to make a new release number. So if you checkout the main branch instead of v0.3 it should work

**Comment by mhooton** [comment]
Great, that worked
