### ISSUE TITLE
"Extension ('WAVELENGTH', 1) not found."

### ISSUE THREAD

**Issue by kcrasmus** [kevin218/Eureka#430]
### Instrument

NIRSpec (Stages 1-3)

### What happened?

I am running 

s3_spec, s3_meta = s3.reduce(eventlabel, ecf_path=ecf_path,
                                 s2_meta=s2_meta)

at which point it fails to find the "Wavelength" extension. S2 is executing normally, and I did go in and fix the issue the code suggested I fix with the bgerr for issue 193. 

I've included the full output for clarity.

### Error traceback output

[S3_error.txt](https://github.com/kevin218/Eureka/files/9204191/S3_error.txt)

### What operating system are you using?

Mac OSX

### What version of Python are you running?

3.9

### What Python packages do you have installed?

(eureka) rasmussen@Kaitlins-MacBook-Pro demos % conda list
# packages in environment at /Users/rasmussen/opt/anaconda3/envs/eureka:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appnope                   0.1.2           py39hca03da5_1001    anaconda
asdf                      2.12.0                   pypi_0    pypi
asdf-astropy              0.2.1                    pypi_0    pypi
asdf-coordinates-schemas  0.1.0                    pypi_0    pypi
asdf-standard             1.0.2                    pypi_0    pypi
asdf-transform-schemas    0.2.2                    pypi_0    pypi
asdf-wcs-schemas          0.1.1                    pypi_0    pypi
asteval                   0.9.27                   pypi_0    pypi
astraeus                  0.2                      pypi_0    pypi
astropy                   5.1                      pypi_0    pypi
astropy-healpix           0.6                      pypi_0    pypi
astroquery                0.4.6                    pypi_0    pypi
astroscrappy              1.1.0                    pypi_0    pypi
asttokens                 2.0.5              pyhd3eb1b0_0    anaconda
attrs                     21.4.0                   pypi_0    pypi
babel                     2.10.3                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0    anaconda
bayesicfitting            3.0.1                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
blas                      1.0                    openblas  
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.3.5                    pypi_0    pypi
brotli                    1.0.7                hc377ac9_0  
c-ares                    1.18.1               h1a28f6b_0  
ca-certificates           2022.07.19           hca03da5_0  
ccdproc                   2.3.1                    pypi_0    pypi
celerite                  0.4.2                    pypi_0    pypi
certifi                   2022.5.18.1              pypi_0    pypi
cftime                    1.6.1                    pypi_0    pypi
charset-normalizer        2.1.0                    pypi_0    pypi
cloudpickle               2.1.0                    pypi_0    pypi
corner                    2.2.1                    pypi_0    pypi
crds                      11.16.6                  pypi_0    pypi
cycler                    0.11.0             pyhd3eb1b0_0  
cython                    0.29.30                  pypi_0    pypi
dask                      2022.7.1                 pypi_0    pypi
debugpy                   1.5.1            py39hc377ac9_0    anaconda
decorator                 5.1.1              pyhd3eb1b0_0    anaconda
docutils                  0.19                     pypi_0    pypi
drizzle                   1.13.4                   pypi_0    pypi
dynesty                   1.2.3                    pypi_0    pypi
emcee                     3.1.2                    pypi_0    pypi
entrypoints               0.4              py39hca03da5_0    anaconda
eureka                    0.4.dev0+g03256a1.d20220726          pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0    anaconda
exotic-ld                 2.0.0                    pypi_0    pypi
expat                     2.4.4                hc377ac9_0  
filelock                  3.7.1                    pypi_0    pypi
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               h1192e45_0  
fsspec                    2022.5.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
george                    0.4.0                    pypi_0    pypi
giflib                    5.2.1                h1a28f6b_0  
gwcs                      0.18.1                   pypi_0    pypi
h5netcdf                  1.0.1                    pypi_0    pypi
h5py                      3.6.0            py39h7fe8675_0  
hdf5                      1.12.1               h160e8cb_2  
html5lib                  1.1                      pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imageio                   2.20.0                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        4.12.0                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
ipykernel                 6.9.1            py39hca03da5_0    anaconda
ipython                   8.2.0            py39hca03da5_0    anaconda
jedi                      0.18.1           py39hca03da5_1    anaconda
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jpeg                      9e                   h1a28f6b_0  
jsonschema                4.7.2                    pypi_0    pypi
jupyter_client            7.2.2            py39hca03da5_0    anaconda
jupyter_core              4.9.2            py39hca03da5_0    anaconda
jwst                      1.6.2                    pypi_0    pypi
keyring                   23.7.0                   pypi_0    pypi
kiwisolver                1.4.2            py39hc377ac9_0  
krb5                      1.19.2               h3b8d789_0  
lcms2                     2.12                 hba8e193_0  
libcurl                   7.82.0               hc6d1d07_0  
libcxx                    12.0.0               hf6beb65_1  
libedit                   3.1.20210910         h1a28f6b_0  
libev                     4.33                 h1a28f6b_1  
libffi                    3.4.2                hc377ac9_4  
libgfortran               5.0.0           11_2_0_he6877d6_26  
libgfortran5              11.2.0              he6877d6_26  
libiconv                  1.16                 h1a28f6b_2  
libnghttp2                1.46.0               h95c9599_0  
libopenblas               0.3.20               hea475bc_0  
libpng                    1.6.37               hb8d0fd4_0  
libsodium                 1.0.18               h1a28f6b_0    anaconda
libssh2                   1.10.0               hf27765b_0  
libtiff                   4.2.0                h01837e1_1  
libwebp                   1.2.2                h68602c7_0  
libwebp-base              1.2.2                h1a28f6b_0  
llvm-openmp               12.0.0               haf9daa7_1  
lmfit                     1.0.3                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
lz4-c                     1.9.3                hc377ac9_0  
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.1            py39hca03da5_1  
matplotlib-base           3.5.1            py39hc377ac9_1  
matplotlib-inline         0.1.2              pyhd3eb1b0_2    anaconda
munkres                   1.1.4                      py_0  
ncurses                   6.3                  h1a28f6b_3  
nest-asyncio              1.5.5            py39hca03da5_0    anaconda
netcdf4                   1.6.0                    pypi_0    pypi
networkx                  2.8.5                    pypi_0    pypi
numpy                     1.22.4                   pypi_0    pypi
numpy-base                1.22.3           py39h974a1f5_0  
numpydoc                  1.4.0                    pypi_0    pypi
openssl                   1.1.1q               h1a28f6b_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.3                    pypi_0    pypi
parsley                   1.3                      pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0    anaconda
partd                     1.2.0                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3    anaconda
photutils                 1.5.0                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003    anaconda
pillow                    9.2.0            py39h4d1bdd5_1  
pip                       22.1.2           py39hca03da5_0  
pluggy                    1.0.0                    pypi_0    pypi
poppy                     1.0.3                    pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0    anaconda
psutil                    5.9.1                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2    anaconda
pure_eval                 0.2.2              pyhd3eb1b0_0    anaconda
py                        1.11.0                   pypi_0    pypi
pyerfa                    2.0.0.1                  pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0    anaconda
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    7.1.2                    pypi_0    pypi
python                    3.9.7                hc70090a_1  
python-dateutil           2.8.2              pyhd3eb1b0_0    anaconda
pytz                      2022.1                   pypi_0    pypi
pyvo                      1.3                      pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0           py39hc377ac9_2    anaconda
readline                  8.1.2                h1a28f6b_1  
reproject                 0.8                      pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.7.3            py39h2f0f56f_0  
semantic-version          2.10.0                   pypi_0    pypi
setuptools                61.2.0           py39hca03da5_0  
six                       1.16.0             pyhd3eb1b0_1    anaconda
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
spherical-geometry        1.2.22                   pypi_0    pypi
sphinx                    5.1.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.38.5               h1058600_0  
stack_data                0.2.0              pyhd3eb1b0_0    anaconda
stcal                     1.0.0                    pypi_0    pypi
stdatamodels              0.4.3                    pypi_0    pypi
stpipe                    0.4.1                    pypi_0    pypi
stsci-image               2.3.5                    pypi_0    pypi
stsci-imagestats          1.6.3                    pypi_0    pypi
stsci-stimage             0.2.5                    pypi_0    pypi
svo-filters               0.4.3                    pypi_0    pypi
tifffile                  2022.5.4                 pypi_0    pypi
tk                        8.6.12               hb8d0fd4_0  
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.1              py39h1a28f6b_0    anaconda
tqdm                      4.64.0           py39hca03da5_0  
traitlets                 5.1.1              pyhd3eb1b0_0    anaconda
tweakwcs                  0.7.4                    pypi_0    pypi
typing-extensions         4.3.0                    pypi_0    pypi
tzdata                    2022a                hda174b7_0  
uncertainties             3.1.7                    pypi_0    pypi
urllib3                   1.26.11                  pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0    anaconda
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
wiimatch                  0.3.1                    pypi_0    pypi
xarray                    2022.6.0                 pypi_0    pypi
xz                        5.2.5                h1a28f6b_1  
zeromq                    4.3.4                hc377ac9_0    anaconda
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h5a0b063_2  
zstd                      1.5.2                h8574219_0 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Can you confirm that you did not set skip_extract1d to True in Stage 2?

**Comment by kcrasmus** [comment]
hmm... I did have it set to true, but now I'm getting this error:

Traceback (most recent call last):

  File "/Users/rasmussen/Research/WORKING_Eureka/demos/run_JN_eureka.py",
line 33, in <module>

    s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py",
line 159, in calibrateJWST

    pipeline.run_eurekaS2(filename, meta, log)

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py",
line 252, in run_eurekaS2

    self(filename)

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/step.py",
line 483, in run

    self.prefetch(*args)

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/step.py",
line 600, in prefetch

    self._precache_references(args[0])

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/pipeline.py",
line 312, in _precache_references

    self._precache_references_opened(model)

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/pipeline.py",
line 335, in _precache_references_opened

    self._precache_references_impl(model_or_container)

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/pipeline.py",
line 359, in _precache_references_impl

    crds_refs =
crds_client.get_multiple_reference_paths(model.get_crds_parameters(),
fetch_types, model.crds_observatory)

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/crds_client.py",
line 55, in get_multiple_reference_paths

    refpaths = _get_refpaths(parameters, tuple(reference_file_types),
observatory)

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/crds_client.py",
line 68, in _get_refpaths

    bestrefs = crds.getreferences(

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/crds/core/heavy_client.py",
line 127, in getreferences

    best_refs_paths = api.cache_references(

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/crds/client/api.py",
line 848, in cache_references

    wanted = _get_cache_filelist_and_report_errors(bestrefs)

  File
"/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/crds/client/api.py",
line 891, in _get_cache_filelist_and_report_errors

    raise last_error

crds.core.exceptions.CrdsLookupError: Error determining best reference for
'apcorr'  =    parameter='META.EXPOSURE.TYPE' value='NRS_WATA' is not in
['NRS_AUTOWAVE', 'NRS_BRIGHTOBJ', 'NRS_FIXEDSLIT', 'NRS_IFU', 'NRS_LAMP',
'NRS_MSASPEC']


Thanks,

kaitlin

**Comment by taylorbell57** [comment]
Alright, yeah frustratingly we do need to run the extract1d step for reasons I don't fully understand. Not sure about this new S2 error, but typically things like that are driven by a bad `jwst` package version. Anymore insight @AarynnCarter?

**Comment by kcrasmus** [comment]
Hello,

    It might be my jwst install—how can I test to make sure it's up and
running? I get a zsh: no matches found: .[jwst] message when I try and do
the pip install. I have an M1 machine so I did have to go the conda route
.yml route installing.

Thanks,
kaitlin

**Comment by taylorbell57** [comment]
For zsh you need to make sure you put the quotation marks that are in the documentation (`pip install ".[jwst]"`). But I can see in your list of installed packages that you do have `jwst==1.6.2` installed. I think that's a bit newer than what's in the environment.yml file and setup.cfg file, but typically I've had similar issues when using too old a version, not too new. Maybe try doing `pip install --upgrade jwst`?

**Comment by AarynnCarter** [comment]
@taylorbell57 Do we need to run the extract1d step? I don't think I ever did for the ERS PRISM data because it takes too long...

**Comment by taylorbell57** [comment]
We definitely shouldn't need to run extract1d, but for some reason some datasets end up with no wavelength array of you don't.....

**Comment by kcrasmus** [comment]
Hey, I figured out the issue. I had two files which apparently weren't
data, which is why they had weird exposure types. Folks with this issue
should check and make sure their downloaded data is contains the extension
"NRS_FIXEDSLIT'"

Cheers,
Kaitlin

**Comment by kcrasmus** [comment]
Gotcha. Yeah, upgrading jwst didn't change the "Error determining best
reference for 'apcorr'  =    parameter='META.EXPOSURE.TYPE'
value='NRS_WATA' is not in ['NRS_AUTOWAVE', 'NRS_BRIGHTOBJ',
'NRS_FIXEDSLIT', 'NRS_IFU', 'NRS_LAMP', 'NRS_MSASPEC']" error I'm getting.

thanks,
Kaitlin

**Comment by AarynnCarter** [comment]
Hey Kaitlin,

Just coming back to this, are you still having issues or just providing an update? Now that I look closer, NRS_WATA is signalling that this is a target acquisition observation (Wide Aperture Target Acquisition), so upgrading the jwst package won't fix anything. You just need to make sure you only have science observations in the files you're using (which it looks like you already figured out...)

**Comment by kcrasmus** [comment]
Hello,

     Thanks for following up, we had Eureka installed on our local
computing cluster and it runs just fine over there. no more M1 issues.

Cheers,
Kaitlin
