### ISSUE TITLE
Stage 6 RuntimeWarning: invalid value encountered

### ISSUE THREAD

**Issue by kcrasmus** [kevin218/Eureka#452]
### Instrument

Light curve fitting (Stages 4-6)

### What happened?

I am running Eureka from S3, but when I get to Stage 6, I get this error: 

2022-08-14 15:54:41,519 - stpipe - WARNING - /mmfs1/home/kcrasmus/src/eureka/src/eureka/S6_planet_spectra/plots_s6.py:96: RuntimeWarning: invalid value encountered in sqrt
  return (r/y_scalar)**(1/expFactor)/scaleHeight - H_0

I guess this is implying that y_scalar is zero. I don't have a model yet, which may be the problem? I do not think it is scaleHeight because I have that set to 2.3 in the S5 epf. 

### Error traceback output

[slurm-5868303.txt](https://github.com/kevin218/Eureka/files/9339344/slurm-5868303.txt)
[S6_TRAPPIST-1c.txt](https://github.com/kevin218/Eureka/files/9339351/S6_TRAPPIST-1c.txt)
[S5_TRAPPIST-1c.txt](https://github.com/kevin218/Eureka/files/9339354/S5_TRAPPIST-1c.txt)

### What operating system are you using?

Linux

### What version of Python are you running?

3.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Not having a model to plot at the same time won't be an issue at all as you have correctly set `model_spectrum` to None for that case. The S5 EPF file is also not relevant for this issue - none of those settings impact Stage 6 directly. I would mention that a mean molecular weight (planet_mu in your S6 ECF) of 2.3 implies an H2 and He dominated atmosphere which is not likely to be the correct value for such a small planet.

The main issue though is likely a bug caused by you setting the planet_Rp manually but not the planet_R0 manually - I know that leaving both set to None works well, but it appears that only setting one of them might cause an issue. I'll look into this more shortly, but as a short-term fix you are likely fine setting planet_Rp to None which should avoid a crash (but do consider using a mean molecular weight more appropriate to the atmosphere you'd expect).

And note that you are able to run just Stage 6 on it's own, so you won't need to re-run everything from scratch or anything.

**Comment by kcrasmus** [comment]
also, perhaps this is a second issue, but the spectra I'm getting look like
this:

[image: fig6101_transmission.png]

thanks,
kaitlin

**Comment by taylorbell57** [comment]
I believe you're replying by email rather than on GitHub, and your attached image doesn't seem to be able to make it through that way. Can you send it on GitHub instead of email?

**Comment by kcrasmus** [comment]
gotcha. here it is:
![fig6101_transmission](https://user-images.githubusercontent.com/109691216/184989317-94e1077e-da47-49f7-9c81-cd6ccdd43489.png)

thanks,
kaitlin

**Comment by taylorbell57** [comment]
I'll also note that you should look at your outputs from Stage 5 - the lsq fitter failed to converge with the default value for lsq_maxiter. If you set lsq_maxiter to something ~10x the number of evaluations it stopped at (2001 according to the log you sent me, so try 20000) then lsq should converge.

As for the plot, I'm not sure what your concern is. If you want y error bars, you'll need to use one of the methods that gives uncertainties on fitted parameters (emcee of dynesty). If you're concerned by the near-zero transit depth, then you should look at what happened during Stage 5 (see again my comments above for lsq convergence).

**Comment by kcrasmus** [comment]
This is NIRSpec spectra, so shouldn't there be ~432 data points in the spectrum? Also, the lsq fitter failed to converge even with 30,000 iterations. Not sure what could be causing that.
[slurm-5873588.txt](https://github.com/kevin218/Eureka/files/9354909/slurm-5873588.txt)
[S5_TRAPPIST-1c.ecf.txt](https://github.com/kevin218/Eureka/files/9354910/S5_TRAPPIST-1c.ecf.txt)
[S5_TRAPPIST-1c.epf.txt](https://github.com/kevin218/Eureka/files/9354911/S5_TRAPPIST-1c.epf.txt)
[S6_TRAPPIST-1c.ecf.txt](https://github.com/kevin218/Eureka/files/9354914/S6_TRAPPIST-1c.ecf.txt)

**Comment by taylorbell57** [comment]
In your stage 4 you'll have set the number of spectral bins you want to two. You can set that to None to have unbinned spectra (very time consuming) or whatever coarser wavelength resolution you want. Not sure why lsq isn't converging - you should try troubleshooting that yourself using the plots and logs

**Comment by kcrasmus** [comment]
ah, gotcha. okay, I'll see if I can figure out the non-convergence problem and report back if I figure it out. Thanks for all your help!

**Comment by taylorbell57** [comment]
Ohh, I finally understand the issue you encountered with Stage 6 now - it was that you had gotten a point so close to zero that the primary y-axis has values below Rp/R* = 0, and when you then try to take the square-root of that to convert it to a scale height you end up with an imaginary number. I'll have to think a bit on how to handle that properly

**Comment by kcrasmus** [comment]
Hello,

     Which file is planet_Rp in? I see a planet_Rad in S6.ecf but not a
planet_Rp. If I set both planet_Rad and planet_R0 to None, I get the same
error.

Thanks,
Kaitlin
