### ISSUE TITLE
[Enhancement]: Wavelength solution for NIRCam

### ISSUE THREAD

**Issue by evamariaa** [kevin218/Eureka#455]
### Instrument

NIRCam (Stages 1-3)

### What is your suggestion?

Adding the NIRCam wavelength solution that has been used by the NIRCam team as the JWST CRDS one is not accurate at the blue end of the spectrum.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
What is the estimated timeline to get a PR ready for this? I have some NIRCam data I'd like to process with this corrected wavelength solution

**Comment by taylorbell57** [comment]
I was speaking with Everett, and he gave me a polynomial function to convert from pixel number to wavelength. If this is in agreement with what others here have, then this simple tweak to nircam.py's read function should be all that's needed until CRDS gets updated (maybe with an ECF setting to toggle between the two ways of setting wave_2d).

```
        # The old way, using the FITS data
        # wave_2d = hdulist['WAVELENGTH', 1].data

        # The new way, using the polynomial model Everett sent me
        X = np.arange(hdulist['WAVELENGTH', 1].data.shape[1])
        Xprime = (X - 1571)/1000
        wave_1d = (3.9269369110332657
                   + 0.9811653393151226*Xprime
                   + 0.001666535535484272*Xprime**2
                   - 0.002874123523765872*Xprime**3)
        wave_2d = wave_1d*np.ones((hdulist['WAVELENGTH', 1].data.shape[0], 1))
```

**Comment by kevin218** [comment]
If you generate a wavelength solution, I can compare it to what Everett gave us. I'm guessing it'll be the same.

**Comment by taylorbell57** [comment]
[nircam_wavelength_soln.csv](https://github.com/kevin218/Eureka/files/9621130/nircam_wavelength_soln.csv)

**Comment by kevin218** [comment]
Ok, assuming the pixel number listed in the first columns starts at 0 (i.e., zeros-based counting) then the numbers agree to better than 1E-9 microns.

**Comment by taylorbell57** [comment]
Great, the difference might just be in the precision to which the wavelengths are saved
