### ISSUE TITLE
[Bug]: S3 crashes when bg_deg = None

### ISSUE THREAD

**Issue by trappist1i** [kevin218/Eureka#456]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

NIRSpec (Stages 1-3)

### What happened?

The online documentation mentions that the user can set bg_deg to 'None' to do not remove the background in S3. When trying it, S3 crashes with the following error:
TypeError: '<' not supported between instances of 'NoneType' and 'int'.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Ah yes, good point - I knew that was broken a while ago but had since forgotten. I'll try to fix that shortly

**Comment by taylorbell57** [comment]
In the future, it'd be helpful if you copy-pasted the full error message traceback into your issue so I can more quickly isolate the location of the bug.
