### ISSUE TITLE
Extracting of JWST x1d data using Eureka

### ISSUE THREAD

**Issue by Aseman7** [kevin218/Eureka#481]
### Instrument

NIRSpec (Stages 1-3)

### What happened?

1- I need JWST x1d fits data for analyzing a spectrum. I extracted -x1d.fits from extract-1d in stage2 of Eureka by importing rate input in S2.ecf. 
But unfortunately, extracted x1d.fits file contains Pixel value (DS/s) versus wavelength values. Some spectral tools don't know the unit of DS/s( units of count rate), so I have to convert it to surface brightness(MJy/sr). I don't know how can I do it with the photom step(
https://jwst-pipeline.readthedocs.io/en/latest/api/jwst.photom.PhotomStep.html).

2- How can I access JWST X1d files through MAST? There are rate fits, x1dints, ratints, calints, cal, but I didn't find other formats such as x1d, s2d,... (for NIRSpec tool)
Maybe I can find x1d in form of surface brightness versus wavelength. I will appreciate it if you would guide me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
From what I can tell from your question, you're not really using Eureka! but just using it as a way to interface with the jwst pipeline. Depending on the dataset you're working on and your overall intentions, if you aren't planning on using Stages 3-6 of Eureka!, then you should likely just use the jwst pipeline itself. But tersely, for Q1, you can set `skip_photom` to be False in your Stage 2 ECF if you're using Eureka!. And for Q2, this does not seem realted to the use of Eureka!, so I recommend you use other tools like JDox to try to investigate your issue.

I'm closing this issue as it does not appear to be related to an issue with Eureka! itself, and I encourage you to look elsewhere for potential answers (e.g. JDox, the jwst pipeline's documentation, etc.). If I misunderstood your question though, please feel free to reopen this issue
