### ISSUE TITLE
[Bug]: Stage 4 ExoTiC limb darkening calculations break for white light

### ISSUE THREAD

**Issue by meganmansfield** [kevin218/Eureka#486]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Light curve fitting (Stages 4-6)

### What happened?

This bug was originally discovered by Brice-Olivier Demory and duplicated by me. The bug occurs in Stage 4 when compute_ld = True and compute_white = True. ExoTiC throws an error when trying to compute the white light limb darkening parameters because only a single scalar is being fed in for the wavelength range, instead of a two-item array. I tracked down the bug to the way generate_LD.py is setting up the wavelength_range array - when doing it for spectroscopic light curves, it's an array of two-item lists, but for a white light curve it outputs a single two-item list, hence the issue with indexing the first item giving a scalar instead of a two-item list. However, it turned out to not be an easy fix as the error kept cascading to other parts of the generate_LD code, and after a couple hours of struggle I decided to just post it here for someone who set up the limb darkening code to figure out.

### Error traceback output

...using exotic-ld package...
Using custom throughput file /Users/megan/Documents/Projects/JWST_ERS/NIRCam/W39Data/NIRCam_observed_throughput_new.csv
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [11], in <cell line: 1>()
----> 1 s4_spec, s4_lc, s4_meta = s4.genlc(eventlabel, ecf_path=ecf_path, input_meta=input_meta_S4)

File ~/Documents/Code/ERS_NIRCam/ERS_NIRCam/Eureka/src/eureka/S4_generate_lightcurves/s4_genLC.py:502, in genlc(eventlabel, ecf_path, s3_meta, input_meta)
    497 lc['exotic-ld_nonlin_4para'] = (['wavelength', 'exotic-ld_4'],
    498                                 ld_4para)
    500 if meta.compute_white:
    501     ld_lin_w, ld_quad_w, ld_3para_w, ld_4para_w = \
--> 502         generate_LD.exotic_ld(meta, spec, log, white=True)
    503     lc['exotic-ld_lin_white'] = (['wavelength', 'exotic-ld_1'],
    504                                  ld_lin_w)
    505     lc['exotic-ld_quad_white'] = (['wavelength',
    506                                    'exotic-ld_2'],
    507                                   ld_quad_w)

File ~/Documents/Code/ERS_NIRCam/ERS_NIRCam/Eureka/src/eureka/S4_generate_lightcurves/generate_LD.py:95, in exotic_ld(meta, spec, log, white)
     92 nonlin_4 = np.zeros((meta.nspecchan, 4))
     93 for i in range(meta.nspecchan):
     94     # generate limb-darkening coefficients for each bin
---> 95     lin_c1[i] = sld.compute_linear_ld_coeffs(wavelength_range[i],
     96                                              mode, custom_wavelengths,
     97                                              custom_throughput)[0]
     98     quad[i] = sld.compute_quadratic_ld_coeffs(wavelength_range[i], mode, 
     99                                               custom_wavelengths,
    100                                               custom_throughput)
    101     nonlin_3[i] = \
    102         sld.compute_3_parameter_non_linear_ld_coeffs(wavelength_range[i], 
    103                                                      mode, 
    104                                                      custom_wavelengths,
    105                                                      custom_throughput)

File ~/opt/anaconda3/envs/ers-nircam/lib/python3.9/site-packages/exotic_ld/ld_computation.py:251, in StellarLimbDarkening.compute_linear_ld_coeffs(self, wavelength_range, mode, custom_wavelengths, custom_throughput)
    212 """
    213 Compute the linear limb-darkening coefficients.
    214 
   (...)
    248 
    249 """
    250 # Compute the stellar limb-darkening.
--> 251 mu, intensity = self._limb_dark_fit(wavelength_range, mode,
    252                                     custom_wavelengths,
    253                                     custom_throughput)
    255 # Fit linear limb-darkening law.
    256 fitter = LevMarLSQFitter()

File ~/opt/anaconda3/envs/ers-nircam/lib/python3.9/site-packages/exotic_ld/ld_computation.py:448, in StellarLimbDarkening._limb_dark_fit(self, wavelength_range, mode, custom_wavelengths, custom_throughput)
    440 sen_wavelengths = self._pad_array(
    441     sen_wavelengths,
    442     [sen_wavelengths[0] - 2., sen_wavelengths[0] - 1.],
    443     [sen_wavelengths[-1] + 1., sen_wavelengths[-1] + 2.])
    444 sen_throughputs = self._pad_array(
    445     sen_throughputs, [0., 0.], [0., 0.])
    446 bin_wavelengths = self._pad_array(
    447     wavelength_range,
--> 448     [wavelength_range[0] - 2., wavelength_range[0] - 1.],
    449     [wavelength_range[-1] + 1., wavelength_range[-1] + 2.])
    451 # Interpolate throughput onto stellar model wavelengths.
    452 interpolator = interp1d(sen_wavelengths, sen_throughputs,
    453                         bounds_error=False, fill_value=0)

IndexError: invalid index to scalar variable.

### What operating system are you using?

Mac OS Ventura

### What version of Python are you running?

Python 3.9

### What Python packages do you have installed?

alabaster                 0.7.12                   pypi_0    pypi
anyio                     3.5.0            py39hecd8cb5_0  
appnope                   0.1.2           py39hecd8cb5_1001  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39hca72f7f_0  
asdf                      2.13.0                   pypi_0    pypi
asdf-astropy              0.2.2                    pypi_0    pypi
asdf-coordinates-schemas  0.1.0                    pypi_0    pypi
asdf-standard             1.0.3                    pypi_0    pypi
asdf-transform-schemas    0.3.0                    pypi_0    pypi
asdf-wcs-schemas          0.1.1                    pypi_0    pypi
asteval                   0.9.27                   pypi_0    pypi
astraeus                  0.3                      pypi_0    pypi
astropy                   5.1.1                    pypi_0    pypi
astropy-healpix           0.7                      pypi_0    pypi
astroquery                0.4.6                    pypi_0    pypi
astroscrappy              1.1.0                    pypi_0    pypi
asttokens                 2.0.5              pyhd3eb1b0_0  
attrs                     21.4.0             pyhd3eb1b0_0  
babel                     2.9.1              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
batman-package            2.4.9                    pypi_0    pypi
bayesicfitting            3.0.1                    pypi_0    pypi
beautifulsoup4            4.11.1           py39hecd8cb5_0  
bleach                    4.1.0              pyhd3eb1b0_0  
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.3.5                    pypi_0    pypi
brotlipy                  0.7.0           py39h9ed2024_1003  
ca-certificates           2022.10.11           hecd8cb5_0  
ccdproc                   2.3.1                    pypi_0    pypi
celerite                  0.4.2                    pypi_0    pypi
certifi                   2022.9.24        py39hecd8cb5_0  
cffi                      1.15.1           py39hc55c11b_0  
cftime                    1.6.2                    pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cloudpickle               2.2.0                    pypi_0    pypi
contourpy                 1.0.6                    pypi_0    pypi
corner                    2.2.1                    pypi_0    pypi
crds                      11.16.15                 pypi_0    pypi
cryptography              38.0.1           py39hf6deb26_0  
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
dask                      2022.6.0                 pypi_0    pypi
debugpy                   1.5.1            py39he9d5cce_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
docutils                  0.19                     pypi_0    pypi
drizzle                   1.13.6                   pypi_0    pypi
dynesty                   2.0.1                    pypi_0    pypi
emcee                     3.1.3                    pypi_0    pypi
entrypoints               0.4              py39hecd8cb5_0  
eureka                    0.6                      pypi_0    pypi
exceptiongroup            1.0.0                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0  
exotic-ld                 2.0.0                    pypi_0    pypi
filelock                  3.8.0                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
fsspec                    2022.10.0                pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
george                    0.4.0                    pypi_0    pypi
gettext                   0.21.0               h7535e17_0  
giflib                    5.2.1                haf1e3a3_0  
glib                      2.69.1               h8346a28_1  
gst-plugins-base          1.14.0               h4180768_2  
gstreamer                 1.14.0               h0fc69c2_2  
gwcs                      0.18.2                   pypi_0    pypi
h5netcdf                  1.0.2                    pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
icu                       58.2                 h0a44026_3  
idna                      3.4              py39hecd8cb5_0  
imageio                   2.22.3                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        4.11.3           py39hecd8cb5_0  
iniconfig                 1.1.1                    pypi_0    pypi
ipykernel                 6.15.2           py39hecd8cb5_0  
ipython                   8.4.0            py39hecd8cb5_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
jaraco-classes            3.2.3                    pypi_0    pypi
jedi                      0.18.1           py39hecd8cb5_1  
jinja2                    3.1.2            py39hecd8cb5_0  
jmespath                  1.0.1                    pypi_0    pypi
jpeg                      9e                   hca72f7f_0  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.9.1                    pypi_0    pypi
jupyter                   1.0.0            py39hecd8cb5_8  
jupyter_client            7.3.5            py39hecd8cb5_0  
jupyter_console           6.4.3              pyhd3eb1b0_0  
jupyter_core              4.11.1           py39hecd8cb5_0  
jupyter_server            1.18.1           py39hecd8cb5_0  
jupyterlab                3.4.4            py39hecd8cb5_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.15.2           py39hecd8cb5_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
jwst                      1.6.0                    pypi_0    pypi
keyring                   23.9.3                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.19.2               hcd88c3b_0  
lerc                      3.0                  he9d5cce_0  
libclang                  12.0.0          default_hbc2896b_2  
libcxx                    14.0.6               h9765a3e_0  
libdeflate                1.8                  h9ed2024_5  
libedit                   3.1.20210910         hca72f7f_0  
libffi                    3.3                  hb1e8313_2  
libiconv                  1.16                 hca72f7f_2  
libllvm12                 12.0.0               h9b2ccf5_3  
libpng                    1.6.37               ha441bb4_0  
libpq                     12.9                 h1c9f633_3  
libsodium                 1.0.18               h1de35cc_0  
libtiff                   4.4.0                h2ef1027_1  
libwebp                   1.2.4                h56c3ce4_0  
libwebp-base              1.2.4                hca72f7f_0  
libxml2                   2.9.14               hbf8cd5e_0  
libxslt                   1.1.35               h5b33f42_0  
llvm-openmp               14.0.6               h0dcd299_0  
lmfit                     1.0.3                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
lz4-c                     1.9.3                h23ab428_1  
markupsafe                2.1.1            py39hca72f7f_0  
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-inline         0.1.6            py39hecd8cb5_0  
mistune                   0.8.4           py39h9ed2024_1000  
more-itertools            9.0.0                    pypi_0    pypi
nbclassic                 0.3.5              pyhd3eb1b0_0  
nbclient                  0.5.13           py39hecd8cb5_0  
nbconvert                 6.4.4            py39hecd8cb5_0  
nbformat                  5.5.0            py39hecd8cb5_0  
ncurses                   6.3                  hca72f7f_3  
nest-asyncio              1.5.5            py39hecd8cb5_0  
netcdf4                   1.6.1                    pypi_0    pypi
networkx                  2.8.8                    pypi_0    pypi
notebook                  6.4.12           py39hecd8cb5_0  
nspr                      4.33                 he9d5cce_0  
nss                       3.74                 h47edf6a_0  
numpy                     1.23.4                   pypi_0    pypi
numpydoc                  1.5.0                    pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openssl                   1.1.1q               hca72f7f_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.5.1                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0  
parsley                   1.3                      pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.3.0                    pypi_0    pypi
pcre                      8.45                 h23ab428_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
photutils                 1.5.0                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.3.0                    pypi_0    pypi
pip                       22.2.2           py39hecd8cb5_0  
pluggy                    1.0.0                    pypi_0    pypi
ply                       3.11             py39hecd8cb5_0  
poppy                     1.0.3                    pypi_0    pypi
prometheus_client         0.14.1           py39hecd8cb5_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
prompt_toolkit            3.0.20               hd3eb1b0_0  
psutil                    5.9.0            py39hca72f7f_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyerfa                    2.0.0.1                  pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9            py39hecd8cb5_0  
pyqt                      5.15.7           py39he9d5cce_0  
pyqt5-sip                 12.11.0          py39he9d5cce_0  
pyrsistent                0.18.0           py39hca72f7f_0  
pysocks                   1.7.1            py39hecd8cb5_0  
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    7.2.0                    pypi_0    pypi
python                    3.9.7                h88f2d9e_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py39hecd8cb5_0  
pytz                      2022.1           py39hecd8cb5_0  
pyvo                      1.4                      pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     23.2.0           py39he9d5cce_0  
qt-main                   5.15.2               h719ae48_7  
qt-webengine              5.15.9               h90a370e_4  
qtconsole                 5.3.2            py39hecd8cb5_0  
qtpy                      2.2.0            py39hecd8cb5_0  
qtwebkit                  5.212                h24dc246_4  
readline                  8.2                  hca72f7f_0  
reproject                 0.9.1                    pypi_0    pypi
requests                  2.28.1           py39hecd8cb5_0  
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                65.5.0           py39hecd8cb5_0  
setuptools-scm            7.0.5                    pypi_0    pypi
sip                       6.6.2            py39he9d5cce_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.2.0            py39hecd8cb5_1  
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1      py39hecd8cb5_0  
spherical-geometry        1.2.23                   pypi_0    pypi
sphinx                    5.3.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.39.3               h707629a_0  
stack_data                0.2.0              pyhd3eb1b0_0  
stcal                     1.2.1                    pypi_0    pypi
stdatamodels              0.4.3                    pypi_0    pypi
stpipe                    0.4.2                    pypi_0    pypi
stsci-image               2.3.5                    pypi_0    pypi
stsci-imagestats          1.6.3                    pypi_0    pypi
stsci-stimage             0.2.6                    pypi_0    pypi
svo-filters               0.4.4                    pypi_0    pypi
terminado                 0.13.1           py39hecd8cb5_0  
testpath                  0.6.0            py39hecd8cb5_0  
tifffile                  2022.10.10               pypi_0    pypi
tk                        8.6.12               h5d9f67b_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.2              py39hca72f7f_0  
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.1.1              pyhd3eb1b0_0  
tweakwcs                  0.8.0                    pypi_0    pypi
typing-extensions         4.3.0            py39hecd8cb5_0  
typing_extensions         4.3.0            py39hecd8cb5_0  
tzdata                    2022f                h04d1e81_0  
uncertainties             3.1.7                    pypi_0    pypi
urllib3                   1.26.12          py39hecd8cb5_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39hecd8cb5_1  
websocket-client          0.58.0           py39hecd8cb5_4  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py39hecd8cb5_0  
wiimatch                  0.3.1                    pypi_0    pypi
xarray                    2022.10.0                pypi_0    pypi
xyzservices               2022.9.0                 pypi_0    pypi
xz                        5.2.6                hca72f7f_0  
zeromq                    4.3.4                h23ab428_0  
zipp                      3.8.0            py39hecd8cb5_0  
zlib                      1.2.13               h4dc903c_0  
zstd                      1.5.2                hcb37349_0  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
I can no longer reproduce this error, so either I or someone else must have patched this bug a while ago. Feel free to re-open this if you still get this error using the code that's currently on the main branch
