### ISSUE TITLE
[Bug]: Start vs Mid Integration Times

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#489]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

NIRISS (Stages 1-3), NIRSpec (Stages 1-3), NIRCam (Stages 1-3), MIRI (Stages 1-3)

### What happened?

As of right now, we're using the 'int_start_BJD_TDB' array in the FITS files, but this would correspond to the start times of the integrations. Wouldn't a more appropriate time array to use be the 'int_mid_BJD_TDB' array which corresponds to the middle of the integration?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebastian-zieba** [comment]
Hi Taylor,
I thought Eureka! was using "int_mid_BJD_TDB" already? Every instrument has the line `time = int_times['int_mid_BJD_TDB']` in the respective "inst" .py files:

https://github.com/kevin218/Eureka/blob/37194ef7fbe03a03054182e9d11dc57ab7fd4cb9/src/eureka/S3_data_reduction/miri.py#L152

https://github.com/kevin218/Eureka/blob/37194ef7fbe03a03054182e9d11dc57ab7fd4cb9/src/eureka/S3_data_reduction/nircam.py#L113

https://github.com/kevin218/Eureka/blob/37194ef7fbe03a03054182e9d11dc57ab7fd4cb9/src/eureka/S3_data_reduction/nirspec.py#L79

**Comment by taylorbell57** [comment]
Oops, that's funny - I was talking with someone else about these time arrays and they claimed that Eureka! was using `int_start_BJD_TDB` and when I checked the code myself I somehow misread those lines - confirmation bias I guess!
