### ISSUE TITLE
[Enhancement]: Upgrade to jwst==1.8.3

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#496]
### Instrument

NIRISS (Stages 1-3), NIRSpec (Stages 1-3), NIRCam (Stages 1-3), MIRI (Stages 1-3)

### What is your suggestion?

I've just tried using jwst==1.8.3 and found that it works just fine for MIRI data. If we can confirm it works with the other three instruments then we can upgrade this dependency

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin218** [comment]
I've tested NIRSpec and NIRCam with jwst==1.8.0 and didn't encounter any problems.
