### ISSUE TITLE
[Enhancement]: mask_trace used by bias_sub.do_correction without clear documentation

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#522]
### Instrument

NIRSpec (Stages 1-3)

### What is your suggestion?

I'm working on reproducing the ERS' PRISM data reduction, and I noticed that the S1 log wrote "Masking Curved Trace." despite the fact that I set `masktrace=False` in my S1 ECF. Looking more closely, I see that the trace gets masked during the bias correction step and uses the settings related to `masktrace` regardless of the value of `masktrace`. Generally if we set a boolean variable like that to False, one can just safely ignore all of the related parameters, and I'm sure I'm not the only one who would either not notice this behaviour (and potentially get poor results) or be confused by it (since I specifically told the code not to mask curved traces).

At a minimum this behaviour needs to be well documented, but ideally we can come up with something less confusing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin218** [comment]
Since I introduced this bug while editing S1, I've self-assigned this task.
