### ISSUE TITLE
[Enhancement]: Use single median frame for all segments

### ISSUE THREAD

**Issue by kevin218** [kevin218/Eureka#538]
### Instrument

NIRSpec (Stages 1-3), NIRCam (Stages 1-3), MIRI (Stages 1-3)

### What is your suggestion?

When processing Stage 3 data in batches, a median frame is computed for each batch.  This sometimes leads to flux offsets in the light curves between batches.  By default, the code should only use the median frame from the first batch.  Users should provide an optional argument if they want a median frame computed for each batch.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
@kevin218 I'm adding this right now. Any preferences on what we call the optional ECF parameter that overrides the new default behaviour and computes a seperate median frame for each batch?

**Comment by kevin218** [comment]
> @kevin218 I'm adding this right now. Any preferences on what we call the optional ECF parameter that overrides the new default behaviour and computes a seperate median frame for each batch?

Nothing comes to mind at the moment. Feel free to suggest something here.

**Comment by taylorbell57** [comment]
What about `meta.independent_batches` or something like that, set to `False` by default?
