### ISSUE TITLE
[Bug]: NoDataOnDetectorError

### ISSUE THREAD

**Issue by gmorello** [kevin218/Eureka#545]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

NIRSpec (Stages 1-3)

### What happened?

I am trying to reproduce the ERS NIRSpec/G395H transit data of WASP-39 b starting from the uncal.
The stage1 apparently worked well, but I get the NoDataOnDetectorError (trying as much default parameters as possible).

I looked into both uncal and rateints files, and actually cannot identify the position of the spectral trace. Perhaps there are some options that should be optimized in my stage1 ecf to obtain decent results.

### Error traceback output

2023-07-05 11:00:30,741 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - Removing slit S1600A1 from the list of open slits because the WCS bounding_box is completely outside the detector.
2023-07-05 11:00:30,742 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - Slits projected on detector NRS2: []
2023-07-05 11:00:30,742 - stpipe.EurekaSpec2Pipeline.assign_wcs - CRITICAL - No open slits fall on detector NRS2.
2023-07-05 11:00:30,742 - stpipe.EurekaSpec2Pipeline - ERROR - Assign_wcs processing was skipped.
2023-07-05 11:00:30,742 - stpipe.EurekaSpec2Pipeline - ERROR - Aborting remaining processing for this exposure.
2023-07-05 11:00:30,742 - stpipe.EurekaSpec2Pipeline - ERROR - No output product will be created.
Traceback (most recent call last):
  File "/scratch/users/gmorello/WASP39b_HR/run_eureka.py", line 24, in <module>
    s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
  File "/home/gmorello/Eureka/src/eureka/S2_calibrations/s2_calibrate.py", line 177, in calibrateJWST
    pipeline.run_eurekaS2(filename, meta, log)
  File "/home/gmorello/Eureka/src/eureka/S2_calibrations/s2_calibrate.py", line 273, in run_eurekaS2
    self(filename)
  File "/home/gmorello/.conda/envs/eureka/lib/python3.9/site-packages/stpipe/step.py", line 478, in run  
    step_result = self.process(*args)
  File "/home/gmorello/.conda/envs/eureka/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 128, in process
    raise exception
  File "/home/gmorello/.conda/envs/eureka/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 119, in process
    result = self.process_exposure_product(
  File "/home/gmorello/.conda/envs/eureka/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 235, in process_exposure_product
    raise assign_wcs_exception
  File "/home/gmorello/.conda/envs/eureka/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 219, in process_exposure_product
    calibrated = self.assign_wcs(science)
  File "/home/gmorello/.conda/envs/eureka/lib/python3.9/site-packages/stpipe/step.py", line 478, in run  
    step_result = self.process(*args)
  File "/home/gmorello/.conda/envs/eureka/lib/python3.9/site-packages/jwst/assign_wcs/assign_wcs_step.py", line 93, in process
    result = load_wcs(input_model, reference_file_names, slit_y_range)
  File "/home/gmorello/.conda/envs/eureka/lib/python3.9/site-packages/jwst/assign_wcs/assign_wcs.py", line 53, in load_wcs
    pipeline = mod.create_pipeline(input_model, reference_files, slit_y_range=nrs_slit_y_range)
  File "/home/gmorello/.conda/envs/eureka/lib/python3.9/site-packages/jwst/assign_wcs/nirspec.py", line 60, in create_pipeline
    pipeline = exp_type2transform[exp_type](input_model, reference_files, slit_y_range=slit_y_range)
  File "/home/gmorello/.conda/envs/eureka/lib/python3.9/site-packages/jwst/assign_wcs/nirspec.py", line 304, in slits_wcs
    open_slits_id = get_open_slits(input_model, reference_files, slit_y_range)
  File "/home/gmorello/.conda/envs/eureka/lib/python3.9/site-packages/jwst/assign_wcs/nirspec.py", line 429, in get_open_slits
    raise NoDataOnDetectorError(log_message)
jwst.assign_wcs.util.NoDataOnDetectorError: (64, 'No open slits fall on detector NRS2.')

### What operating system are you using?

Ubuntu 22.04

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
alabaster                 0.7.13                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asdf                      2.15.0                   pypi_0    pypi
asdf-astropy              0.4.0                    pypi_0    pypi
asdf-coordinates-schemas  0.2.0                    pypi_0    pypi
asdf-standard             1.0.3                    pypi_0    pypi
asdf-transform-schemas    0.3.0                    pypi_0    pypi
asdf-unit-schemas         0.1.0                    pypi_0    pypi
asdf-wcs-schemas          0.1.1                    pypi_0    pypi
asteval                   0.9.30                   pypi_0    pypi
astraeus                  0.3                      pypi_0    pypi
astropy                   5.3                      pypi_0    pypi
astropy-healpix           0.7                      pypi_0    pypi
astroquery                0.4.6                    pypi_0    pypi
astroscrappy              1.1.0                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
batman-package            2.4.9                    pypi_0    pypi
bayesicfitting            3.1.1                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.3.7                    pypi_0    pypi
ca-certificates           2023.05.30           h06a4308_0  
ccdproc                   2.4.1                    pypi_0    pypi
celerite                  0.4.2                    pypi_0    pypi
certifi                   2022.5.18.1              pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
cftime                    1.6.2                    pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
contourpy                 1.1.0                    pypi_0    pypi
corner                    2.2.2                    pypi_0    pypi
crds                      11.17.2                  pypi_0    pypi
cryptography              41.0.1                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.35                  pypi_0    pypi
dask                      2022.6.0                 pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
docutils                  0.20.1                   pypi_0    pypi
drizzle                   1.13.7                   pypi_0    pypi
dynesty                   2.1.2                    pypi_0    pypi
emcee                     3.1.4                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
eureka                    0.9                      pypi_0    pypi
exceptiongroup            1.1.2                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
exotic-ld                 3.0.0                    pypi_0    pypi
fasteners                 0.18                     pypi_0    pypi
filelock                  3.12.2                   pypi_0    pypi
fonttools                 4.40.0                   pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
george                    0.4.0                    pypi_0    pypi
gwcs                      0.18.3                   pypi_0    pypi
h5netcdf                  1.2.0                    pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.31.1                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipython                   8.14.0                   pypi_0    pypi
jaraco-classes            3.2.3                    pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jeepney                   0.8.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jsonschema                4.9.1                    pypi_0    pypi
jwst                      1.8.2                    pypi_0    pypi
keyring                   24.2.0                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lazy-loader               0.3                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
lmfit                     1.2.1                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
more-itertools            9.1.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
netcdf4                   1.6.4                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
numcodecs                 0.11.0                   pypi_0    pypi
numpy                     1.22.0                   pypi_0    pypi
numpydoc                  1.5.0                    pypi_0    pypi
openssl                   1.1.1u               h7f8727e_0  
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
parsley                   1.3                      pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.4.0                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
photutils                 1.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.0.0                   pypi_0    pypi
pip                       23.1.2           py39h06a4308_0  
pluggy                    1.2.0                    pypi_0    pypi
poppy                     1.1.1                    pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyerfa                    2.0.0.3                  pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyparsing                 3.1.0                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    7.4.0                    pypi_0    pypi
python                    3.9.7                h12debd9_1  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyvo                      1.4.1                    pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
reproject                 0.11.0                   pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
scikit-image              0.21.0                   pypi_0    pypi
scipy                     1.11.1                   pypi_0    pypi
secretstorage             3.3.3                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                67.8.0           py39h06a4308_0  
setuptools-scm            7.1.0                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
spherical-geometry        1.2.23                   pypi_0    pypi
sphinx                    7.0.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
stack-data                0.6.2                    pypi_0    pypi
stcal                     1.2.2                    pypi_0    pypi
stdatamodels              0.4.5                    pypi_0    pypi
stpipe                    0.5.0                    pypi_0    pypi
stsci-image               2.3.5                    pypi_0    pypi
stsci-imagestats          1.6.3                    pypi_0    pypi
stsci-stimage             0.2.6                    pypi_0    pypi
svo-filters               0.4.4                    pypi_0    pypi
tifffile                  2023.4.12                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.3.2                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
tweakwcs                  0.8.2                    pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uncertainties             3.1.7                    pypi_0    pypi
urllib3                   2.0.3                    pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.38.4           py39h06a4308_0  
wiimatch                  0.3.1                    pypi_0    pypi
xarray                    2023.6.0                 pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
zarr                      2.15.0                   pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin218** [comment]
My initial guess is that you may have downloaded the PRISM data instead of
the G395 data.

Can you double check that you have the right dataset?

**Comment by gmorello** [comment]
Oh, you are right, thanks!
However, it does not seem that I have specified the instrument in the ecf files.
If I wanted to analyse PRISM, should it be sufficient to set refpix_corr  to True?

**Comment by kevin218** [comment]
The instrument name is given in the header, so Eureka! doesn't need to ask
the user. Based on the input file, it'll choose the correct reduction
pipeline.

**Comment by gmorello** [comment]
Ok, thanks. I close this.
