### ISSUE TITLE
ERROR: FAILED BUILDING WHEEL FOR DRIZZLE

### ISSUE THREAD

**Issue by Fouz-Siddiqui** [kevin218/Eureka#550]
### What happened?

As I'm trying to install pip install jwst, everything is build/gets sucessfully done. But, fails to build wheel for drizzle.

### Error traceback output

(eureka) C:\Users\A-WASAY-PC>pip install jwst
Collecting jwst
  Using cached jwst-1.11.1-cp39-cp39-win_amd64.whl
Collecting asdf>=2.14.1 (from jwst)
  Using cached asdf-2.15.0-py3-none-any.whl (431 kB)
Collecting asdf-transform-schemas>=0.3.0 (from jwst)
  Using cached asdf_transform_schemas-0.3.0-py3-none-any.whl (195 kB)
Collecting astropy>=5.2 (from jwst)
  Using cached astropy-5.3.1-cp39-cp39-win_amd64.whl (6.9 MB)
Collecting BayesicFitting>=3.0.1 (from jwst)
  Using cached BayesicFitting-3.1.1-py3-none-any.whl (5.6 MB)
Collecting crds>=11.16.19 (from jwst)
  Using cached crds-11.17.2-py3-none-any.whl (1.2 MB)
Collecting drizzle>=1.13.7 (from jwst)
  Using cached drizzle-1.13.7.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gwcs>=0.18.3 (from jwst)
  Using cached gwcs-0.18.3-py3-none-any.whl (108 kB)
Collecting numpy>=1.20 (from jwst)
  Using cached numpy-1.25.1-cp39-cp39-win_amd64.whl (15.1 MB)
Collecting opencv-python-headless>=4.6.0.66 (from jwst)
  Using cached opencv_python_headless-4.8.0.74-cp37-abi3-win_amd64.whl (38.0 MB)
Collecting photutils>=1.4.0 (from jwst)
  Using cached photutils-1.8.0-cp39-cp39-win_amd64.whl (591 kB)
Requirement already satisfied: psutil>=5.7.2 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from jwst) (5.9.5)
Collecting poppy>=1.0.2 (from jwst)
  Using cached poppy-1.1.1-py3-none-any.whl (2.8 MB)
Collecting pyparsing>=2.2.1 (from jwst)
  Using cached pyparsing-3.1.0-py3-none-any.whl (102 kB)
Requirement already satisfied: requests>=2.22 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from jwst) (2.31.0)
Collecting scipy<1.10.0,>=1.6.0 (from jwst)
  Using cached scipy-1.9.3-cp39-cp39-win_amd64.whl (40.2 MB)
Collecting spherical-geometry>=1.2.22 (from jwst)
  Using cached spherical_geometry-1.2.23-cp39-cp39-win_amd64.whl
Collecting stcal<1.5.0,>=1.4.0 (from jwst)
  Using cached stcal-1.4.1-py3-none-any.whl (87 kB)
Collecting stdatamodels>=1.6.0 (from jwst)
  Using cached stdatamodels-1.7.0-py3-none-any.whl (303 kB)
Collecting stpipe>=0.5.0 (from jwst)
  Using cached stpipe-0.5.0-py3-none-any.whl (81 kB)
Collecting stsci.image>=2.3.5 (from jwst)
  Using cached stsci.image-2.3.5-cp39-cp39-win_amd64.whl
Collecting stsci.imagestats>=1.6.3 (from jwst)
  Using cached stsci.imagestats-1.6.3-cp39-cp39-win_amd64.whl
Collecting tweakwcs>=0.8.2 (from jwst)
  Using cached tweakwcs-0.8.2-py3-none-any.whl (83 kB)
Collecting asdf-astropy>=0.3.0 (from jwst)
  Using cached asdf_astropy-0.4.0-py3-none-any.whl (73 kB)
Collecting wiimatch>=0.2.1 (from jwst)
  Using cached wiimatch-0.3.1-py3-none-any.whl (17 kB)
Requirement already satisfied: packaging>19.0 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from jwst) (23.1)
Requirement already satisfied: importlib-metadata>=4.11.4 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from jwst) (6.7.0)
Collecting asdf-standard>=1.0.1 (from asdf>=2.14.1->jwst)
  Using cached asdf_standard-1.0.3-py3-none-any.whl (71 kB)
Collecting asdf-unit-schemas>=0.1 (from asdf>=2.14.1->jwst)
  Using cached asdf_unit_schemas-0.1.0-py3-none-any.whl (11 kB)
Collecting jmespath>=0.6.2 (from asdf>=2.14.1->jwst)
  Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting jsonschema<4.18,>=4.0.1 (from asdf>=2.14.1->jwst)
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Requirement already satisfied: pyyaml>=5.4.1 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from asdf>=2.14.1->jwst) (6.0)
Collecting semantic-version>=2.8 (from asdf>=2.14.1->jwst)
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting asdf-coordinates-schemas>=0.1 (from asdf-astropy>=0.3.0->jwst)
  Using cached asdf_coordinates_schemas-0.2.0-py3-none-any.whl (19 kB)
Collecting pyerfa>=2.0 (from astropy>=5.2->jwst)
  Using cached pyerfa-2.0.0.3-cp39-cp39-win_amd64.whl (347 kB)
Collecting matplotlib>=2.0 (from BayesicFitting>=3.0.1->jwst)
  Using cached matplotlib-3.7.2-cp39-cp39-win_amd64.whl (7.5 MB)
Collecting future (from BayesicFitting>=3.0.1->jwst)
  Using cached future-0.18.3-py3-none-any.whl
Collecting filelock (from crds>=11.16.19->jwst)
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting parsley (from crds>=11.16.19->jwst)
  Using cached Parsley-1.3-py2.py3-none-any.whl (88 kB)
Collecting asdf-wcs-schemas (from gwcs>=0.18.3->jwst)
  Using cached asdf_wcs_schemas-0.1.1-py3-none-any.whl
Requirement already satisfied: zipp>=0.5 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from importlib-metadata>=4.11.4->jwst) (3.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from requests>=2.22->jwst) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from requests>=2.22->jwst) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from requests>=2.22->jwst) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from requests>=2.22->jwst) (2023.5.7)
Collecting stsci.stimage (from tweakwcs>=0.8.2->jwst)
  Using cached stsci.stimage-0.2.6-cp39-cp39-win_amd64.whl
Requirement already satisfied: attrs>=17.4.0 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from jsonschema<4.18,>=4.0.1->asdf>=2.14.1->jwst) (23.1.0)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 (from jsonschema<4.18,>=4.0.1->asdf>=2.14.1->jwst)
  Using cached pyrsistent-0.19.3-cp39-cp39-win_amd64.whl (62 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=2.0->BayesicFitting>=3.0.1->jwst)
  Using cached contourpy-1.1.0-cp39-cp39-win_amd64.whl (429 kB)
Collecting cycler>=0.10 (from matplotlib>=2.0->BayesicFitting>=3.0.1->jwst)
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=2.0->BayesicFitting>=3.0.1->jwst)
  Using cached fonttools-4.40.0-cp39-cp39-win_amd64.whl (2.0 MB)
Collecting kiwisolver>=1.0.1 (from matplotlib>=2.0->BayesicFitting>=3.0.1->jwst)
  Using cached kiwisolver-1.4.4-cp39-cp39-win_amd64.whl (55 kB)
Collecting pillow>=6.2.0 (from matplotlib>=2.0->BayesicFitting>=3.0.1->jwst)
  Using cached Pillow-10.0.0-cp39-cp39-win_amd64.whl (2.5 MB)
Collecting pyparsing>=2.2.1 (from jwst)
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from matplotlib>=2.0->BayesicFitting>=3.0.1->jwst) (2.8.2)
Collecting importlib-resources>=3.2.0 (from matplotlib>=2.0->BayesicFitting>=3.0.1->jwst)
  Using cached importlib_resources-6.0.0-py3-none-any.whl (31 kB)
Requirement already satisfied: six>=1.5 in c:\users\a-wasay-pc\miniconda3\envs\eureka\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.0->BayesicFitting>=3.0.1->jwst) (1.16.0)
Building wheels for collected packages: drizzle
  Building wheel for drizzle (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for drizzle (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      C:\Users\A-WASAY-PC\AppData\Local\Temp\pip-build-env-e358qvhm\overlay\Lib\site-packages\setuptools\dist.py:745: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'upload-dir' will not be supported in future
              versions. Please use the underscore name 'upload_dir' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      C:\Users\A-WASAY-PC\AppData\Local\Temp\pip-build-env-e358qvhm\overlay\Lib\site-packages\setuptools\dist.py:745: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'show-response' will not be supported in future
              versions. Please use the underscore name 'show_response' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\drizzle
      copying drizzle\calc_pixmap.py -> build\lib.win-amd64-cpython-39\drizzle
      copying drizzle\doblot.py -> build\lib.win-amd64-cpython-39\drizzle
      copying drizzle\dodrizzle.py -> build\lib.win-amd64-cpython-39\drizzle
      copying drizzle\drizzle.py -> build\lib.win-amd64-cpython-39\drizzle
      copying drizzle\util.py -> build\lib.win-amd64-cpython-39\drizzle
      copying drizzle\__init__.py -> build\lib.win-amd64-cpython-39\drizzle
      creating build\lib.win-amd64-cpython-39\drizzle\tests
      copying drizzle\tests\test_cdrizzle.py -> build\lib.win-amd64-cpython-39\drizzle\tests
      copying drizzle\tests\test_drizzle.py -> build\lib.win-amd64-cpython-39\drizzle\tests
      copying drizzle\tests\test_file_io.py -> build\lib.win-amd64-cpython-39\drizzle\tests
      copying drizzle\tests\test_pixmap.py -> build\lib.win-amd64-cpython-39\drizzle\tests
      copying drizzle\tests\__init__.py -> build\lib.win-amd64-cpython-39\drizzle\tests
      running build_ext
      building 'drizzle.cdrizzle' extension
      creating build\temp.win-amd64-cpython-39
      creating build\temp.win-amd64-cpython-39\Release
      creating build\temp.win-amd64-cpython-39\Release\Users
      creating build\temp.win-amd64-cpython-39\Release\Users\A-WASAY-PC
      creating build\temp.win-amd64-cpython-39\Release\Users\A-WASAY-PC\AppData
      creating build\temp.win-amd64-cpython-39\Release\Users\A-WASAY-PC\AppData\Local
      creating build\temp.win-amd64-cpython-39\Release\Users\A-WASAY-PC\AppData\Local\Temp
      creating build\temp.win-amd64-cpython-39\Release\Users\A-WASAY-PC\AppData\Local\Temp\pip-install-5n4nrani
      creating build\temp.win-amd64-cpython-39\Release\Users\A-WASAY-PC\AppData\Local\Temp\pip-install-5n4nrani\drizzle_a1d3c77da24a4b8db1224005264ba51b
      creating build\temp.win-amd64-cpython-39\Release\Users\A-WASAY-PC\AppData\Local\Temp\pip-install-5n4nrani\drizzle_a1d3c77da24a4b8db1224005264ba51b\src
      creating build\temp.win-amd64-cpython-39\Release\Users\A-WASAY-PC\AppData\Local\Temp\pip-install-5n4nrani\drizzle_a1d3c77da24a4b8db1224005264ba51b\src\tests
      error: could not create 'build\temp.win-amd64-cpython-39\Release\Users\A-WASAY-PC\AppData\Local\Temp\pip-install-5n4nrani\drizzle_a1d3c77da24a4b8db1224005264ba51b\src\tests': The filename or extension is too long
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for drizzle
Failed to build drizzle
ERROR: Could not build wheels for drizzle, which is required to install pyproject.toml-based projects

### What operating system are you using?

Windows 11

### What version of Python are you running?

Python 3.10.10 final.0

### What Python packages do you have installed?

# packages in environment at C:\Users\A-WASAY-PC\miniconda3\envs\eureka:
#
# Name                    Version                   Build  Channel
anyio                     3.7.1                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-lru                 2.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
ca-certificates           2023.05.30           haa95532_0
certifi                   2023.5.7                 pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.1.3                    pypi_0    pypi
debugpy                   1.6.7                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
eureka                    0.15                     pypi_0    pypi
exceptiongroup            1.1.2                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.17.1                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
hst                       0.1.11                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
ipykernel                 6.24.0                   pypi_0    pypi
ipython                   8.14.0                   pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
json5                     0.9.14                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.18.0                   pypi_0    pypi
jsonschema-specifications 2023.6.1                 pypi_0    pypi
jupyter-client            8.3.0                    pypi_0    pypi
jupyter-core              5.3.1                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-lsp               2.2.0                    pypi_0    pypi
jupyter-server            2.7.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab                4.0.2                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.23.0                   pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   3.0.1                    pypi_0    pypi
nbclient                  0.8.0                    pypi_0    pypi
nbconvert                 7.6.0                    pypi_0    pypi
nbformat                  5.9.0                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
openssl                   1.1.1u               h2bbff1b_0
overrides                 7.3.1                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       23.1.2           py39haa95532_0
platformdirs              3.8.1                    pypi_0    pypi
prometheus-client         0.17.0                   pypi_0    pypi
prompt-toolkit            3.0.39                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyperclip                 1.8.2                    pypi_0    pypi
python                    3.9.7                h6244533_1
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pywinpty                  2.0.10                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.1.0                   pypi_0    pypi
referencing               0.29.1                   pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rpds-py                   0.8.8                    pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
setuptools                67.8.0           py39haa95532_0
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
stack-data                0.6.2                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.3.2                    pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.0.3                    pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.6.1                    pypi_0    pypi
wheel                     0.38.4           py39haa95532_0
zipp                      3.15.0                   pypi_0    pypi

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
As this is not an issue with Eureka!, but rather an issue with the jwst package, please instead post your issue on their GitHub page (https://github.com/spacetelescope/jwst/issues) or potentially that for drizzle
