### ISSUE TITLE
[Bug]: Not compatible with Colab

### ISSUE THREAD

**Issue by dreamjade** [kevin218/Eureka#553]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Other (any stage)

### What happened?

Colab now uses python 3.10
import eureka with raise the following error:
ContextualVersionConflict: (certifi 2023.5.7 (/usr/local/lib/python3.10/dist-packages), Requirement.parse('certifi==2022.5.18.1'), {'jwst'})

### What operating system are you using?

Colab

### What version of Python are you running?

Python 3.10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Strange, it worked just fine on Monday with python 3.10 on Colab. Let me check

**Comment by taylorbell57** [comment]
Running:
```
# Change numpy version (required for theano)
!pip install numpy==1.21.6
# Install Eureka! (for now a dev branch, but in the future a stable branch)
!pip install eureka[jwst]@git+https://github.com/kevin218/Eureka.git@dev/tjb
```

and then clicking Runtime->Restart runtime

and then running:
```
import eureka
```

works just fine for me on Google Colab. Can you confirm that you followed those exact steps?
