### ISSUE TITLE
[Enhancement]: Quickstart for HST WFC3/G141 S3-S6 stages

### ISSUE THREAD

**Issue by andreok** [kevin218/Eureka#562]
### Instrument

Other (any stage)

### What is your suggestion?

Hello,
I would like to ask if you have a quickstart guide also for HST WFC3/G141 S3-S6 stages with the HD209458 demo data, besides the guide for JWST NIRSpec S2-S6 stages and WASP-39b?
Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jbrande** [comment]
I've been working on the HST side of things a bit recently, I can get something for this in the next week or so.
