### ISSUE TITLE
[Enhancement]: add uncertainty to Allan deviation plots

### ISSUE THREAD

**Issue by lkreidberg** [kevin218/Eureka#590]
### Instrument

Light curve fitting (Stages 4-6)

### What is your suggestion?

For Allan deviation plots, we should incorporate two changes from[ Cubillos et al 2017 ](https://arxiv.org/pdf/1610.01336.pdf) 

- uncertainty in the estimated rms (Appendix C)
- to predict the rms, use Equation 8 of Cubillos et al (see their Fig 1 for a good example)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Yes, thanks so much for adding this issue @lkreidberg! I have all the code already written in my spitzer SPCA package and should hopefully be able to port that over quite easily
