### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by 3-kaku** [kevin218/Eureka#596]
### What happened?

The first time I tried to execute this code, I got the following error message.

I thought maybe the PATH wasn't going through, so I messed around with it, but now I'm not sure. What should I do?

### Error traceback output

File "C:\Users\toshi\Desktop\jwst\eureka\test_data\JWST\JWST\run_eureka.py", line 2, in <module>
    import eureka.lib.plots
ModuleNotFoundError: No module named 'eureka.lib'

### What operating system are you using?

Windows 10

### What version of Python are you running?

Python 3.10

### What Python packages do you have installed?

# Name                    Version                   Build  Channel
anyio                     4.2.0                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
babel                     2.14.0                   pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
blas                      1.0                         mkl
bleach                    6.1.0                    pypi_0    pypi
bottleneck                1.3.5            py39h080aedc_0
ca-certificates           2023.08.22           haa95532_0
certifi                   2023.11.17               pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.2.0                    pypi_0    pypi
debugpy                   1.8.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
eureka                    0.15                     pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
fastjsonschema            2.19.0                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
idna                      3.6                      pypi_0    pypi
importlib-metadata        7.0.0                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46320
ipykernel                 6.27.1                   pypi_0    pypi
ipython                   8.18.1                   pypi_0    pypi
ipywidgets                8.1.1                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
json5                     0.9.14                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.20.0                   pypi_0    pypi
jsonschema-specifications 2023.11.2                pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.6.0                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.5.0                    pypi_0    pypi
jupyter-events            0.9.0                    pypi_0    pypi
jupyter-lsp               2.2.1                    pypi_0    pypi
jupyter-server            2.12.1                   pypi_0    pypi
jupyter-server-terminals  0.5.0                    pypi_0    pypi
jupyterlab                4.0.9                    pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.25.2                   pypi_0    pypi
jupyterlab-widgets        3.0.9                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0            py39h2bbff1b_1
mkl_fft                   1.3.8            py39h2bbff1b_0
mkl_random                1.2.4            py39h59b6b97_0
nbclient                  0.9.0                    pypi_0    pypi
nbconvert                 7.12.0                   pypi_0    pypi
nbformat                  5.9.2                    pypi_0    pypi
nest-asyncio              1.5.8                    pypi_0    pypi
notebook                  7.0.6                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numexpr                   2.8.7            py39h2cd9be0_0
numpy                     1.26.2           py39h055cbcc_0
numpy-base                1.26.2           py39h65a83cf_0
openssl                   1.1.1w               h2bbff1b_0
overrides                 7.4.0                    pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    2.1.4            py39h4ed8f06_0
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pip                       23.3.1           py39haa95532_0
platformdirs              4.1.0                    pypi_0    pypi
prometheus-client         0.19.0                   pypi_0    pypi
prompt-toolkit            3.0.43                   pypi_0    pypi
psutil                    5.9.7                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
python                    3.9.7                h6244533_1
python-dateutil           2.8.2              pyhd3eb1b0_0
python-json-logger        2.0.7                    pypi_0    pypi
python-tzdata             2023.3             pyhd3eb1b0_0
pytz                      2023.3.post1     py39haa95532_0
pywin32                   306                      pypi_0    pypi
pywinpty                  2.0.12                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.2                   pypi_0    pypi
qtconsole                 5.5.1                    pypi_0    pypi
qtpy                      2.4.1                    pypi_0    pypi
referencing               0.32.0                   pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rpds-py                   0.15.2                   pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
setuptools                68.2.2           py39haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
stack-data                0.6.3                    pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0
terminado                 0.18.0                   pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.4                      pypi_0    pypi
traitlets                 5.14.0                   pypi_0    pypi
types-python-dateutil     2.8.19.14                pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.1.0                    pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.12                   pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.7.0                    pypi_0    pypi
wheel                     0.41.2           py39haa95532_0
widgetsnbextension        4.0.9                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
It seems to me that you may have done `pip install eureka` and gotten some other package that someone has made with the same name as our package (we haven't hosted our project on pip yet). Please follow very carefully the installation instructions on our readthedocs page, and let me know whether or not that resolves your issue

**Comment by 3-kaku** [comment]
Thanks for pointing that out. I followed it and when I tried to install it, I got the following error

(omitted)......
```
Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
```
...(omitted)...
```
raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/home/runner/work/drizzle/drizzle/src/cdrizzleapi.c' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I don't seem to be able to install drizzle on Windows, but I wonder if that is the cause of this error.

**Comment by taylorbell57** [comment]
Ah, so I think the only way you'll be able to install on a Windows computer are by using the Windows Subsystem for Linux (you can read tutorials on how to set that up online) or by dual booting Linux on your machine (sometimes simpler than WSL, sometimes more complicated; again, there's many tutorials online). I've done both in the past, and have both currently working on my personal laptop. Sadly many packages don't natively support Windows
