### ISSUE TITLE
NIRCam Stage 3 AttributeError: cannot set attribute 'medflux' on a 'Dataset' object.

### ISSUE THREAD

**Issue by Erikmeier18** [kevin218/Eureka#610]
### Instrument

NIRCam (Stages 1-3)

### What happened?

Stage 3 fails after starting the second .calints file. I'm processing NIRCam F444W observations made of 22 uncal segments. Stage 1 and 2 seem alright. Stage 3 works for the first file, but after starting with the second file I get an error. Couldn't figure out where the issue is. 

### Error traceback output

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/miniconda3/envs/eureka/lib/python3.9/site-packages/xarray/core/common.py:306, in AttrAccessMixin.__setattr__(self, name, value)
    305 try:
--> 306     object.__setattr__(self, name, value)
    307 except AttributeError as e:
    308     # Don't accidentally shadow custom AttributeErrors, e.g.
    309     # DataArray.dims.setter

AttributeError: 'Dataset' object has no attribute 'medflux'

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
Cell In[23], line 1
----> 1 s3_spec, s3_meta = s3.reduce(eventlabel, ecf_path=ecf_path, s2_meta=s2_meta)

File ~/miniconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py:467, in reduce(eventlabel, ecf_path, s2_meta, input_meta)
    464     saved_ref_median_frame = data.medflux
    465 else:
    466     # Load the original median frame
--> 467     data.medflux = saved_ref_median_frame
    469 # correct spectral curvature
    470 if not hasattr(meta, 'curvature'):
    471     # By default, don't correct curvature

File ~/miniconda3/envs/eureka/lib/python3.9/site-packages/xarray/core/common.py:312, in AttrAccessMixin.__setattr__(self, name, value)
    310 if str(e) != f"{type(self).__name__!r} object has no attribute {name!r}":
    311     raise
--> 312 raise AttributeError(
    313     f"cannot set attribute {name!r} on a {type(self).__name__!r} object. Use __setitem__ style"
    314     "assignment (e.g., `ds['name'] = ...`) instead of assigning variables."
    315 ) from e

AttributeError: cannot set attribute 'medflux' on a 'Dataset' object. Use __setitem__ styleassignment (e.g., `ds['name'] = ...`) instead of assigning variables.

### What operating system are you using?

Mac OS Sonoma 14.1.1

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

# Name                    Version                   Build  Channel
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
anyio                     4.1.0              pyhd8ed1ab_0    conda-forge
aom                       3.7.1                h463b476_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39h0f82c59_4    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
arviz                     0.16.1             pyhd8ed1ab_1    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asdf                      3.0.1              pyhd8ed1ab_0    conda-forge
asdf-astropy              0.5.0              pyhd8ed1ab_0    conda-forge
asdf-coordinates-schemas  0.2.0              pyhd8ed1ab_1    conda-forge
asdf-standard             1.0.3              pyhd8ed1ab_0    conda-forge
asdf-transform-schemas    0.4.0              pyhd8ed1ab_0    conda-forge
asdf-unit-schemas         0.1.0              pyhd8ed1ab_0    conda-forge
asdf-wcs-schemas          0.1.1              pyhd8ed1ab_0    conda-forge
asteval                   0.9.31             pyhd8ed1ab_0    conda-forge
astraeus                  0.3                      pypi_0    pypi
astropy                   6.0.0            py39h373d45f_0    conda-forge
astropy-healpix           0.7              py39h4d8bf0d_2    conda-forge
astropy-iers-data         0.2023.12.4.0.30.20    pyhd8ed1ab_0    conda-forge
astroscrappy              1.1.0            py39h4d8bf0d_2    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
aws-c-auth                0.7.7                h886c30d_1    conda-forge
aws-c-cal                 0.6.9                hea61927_1    conda-forge
aws-c-common              0.9.8                h93a5062_0    conda-forge
aws-c-compression         0.2.17               hea61927_6    conda-forge
aws-c-event-stream        0.3.2                h0574dc0_7    conda-forge
aws-c-http                0.7.14               h90b1786_2    conda-forge
aws-c-io                  0.13.36              he1b4ce3_0    conda-forge
aws-c-mqtt                0.9.10               h8d54690_1    conda-forge
aws-c-s3                  0.4.1                ha5b923c_0    conda-forge
aws-c-sdkutils            0.1.12               hea61927_5    conda-forge
aws-checksums             0.1.17               hea61927_5    conda-forge
aws-crt-cpp               0.24.7               hba4ac3b_6    conda-forge
aws-sdk-cpp               1.11.182             h31542fa_7    conda-forge
babel                     2.13.1             pyhd8ed1ab_0    conda-forge
batman-package            2.4.9            py39h4d8bf0d_1    conda-forge
bayesicfitting            3.2.0                    pypi_0    pypi
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.5               hc338f07_0    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
bottleneck                1.3.7            py39hf4a74a7_1    conda-forge
brotli                    1.1.0                hb547adb_1    conda-forge
brotli-bin                1.1.0                hb547adb_1    conda-forge
brotli-python             1.1.0            py39hb198ff7_1    conda-forge
brunsli                   0.1                  h9f76cd9_0    conda-forge
bzip2                     1.0.8                h93a5062_5    conda-forge
c-ares                    1.23.0               h93a5062_0    conda-forge
c-blosc2                  2.11.3               h8eb3132_0    conda-forge
ca-certificates           2023.11.17           hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.18.0               hd1e100b_0    conda-forge
ccdproc                   2.4.1              pyhd8ed1ab_0    conda-forge
celerite                  0.4.2            py39h425d09f_4    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py39he153c15_0    conda-forge
cfitsio                   4.3.0                hca87796_0    conda-forge
cftime                    1.6.3                    pypi_0    pypi
charls                    2.4.2                h13dd4ca_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0            py39he9de807_0    conda-forge
corner                    2.2.2              pyhd8ed1ab_0    conda-forge
coverage                  7.3.2            py39h0f82c59_0    conda-forge
crds                      11.17.13                 pypi_0    pypi
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.2           py39h0f82c59_1    conda-forge
dask                      2023.12.0          pyhd8ed1ab_0    conda-forge
dask-core                 2023.12.0          pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                hb547adb_0    conda-forge
debugpy                   1.8.0            py39hb198ff7_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distributed               2023.12.0          pyhd8ed1ab_0    conda-forge
docutils                  0.20.1           py39h2804cbe_3    conda-forge
drizzle                   1.14.4                   pypi_0    pypi
dynesty                   2.1.2              pyhd8ed1ab_0    conda-forge
emcee                     3.1.4              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
eureka                    0.11.dev22+g1cec564f          pypi_0    pypi
exceptiongroup            1.2.0              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
exotic-ld                 3.0.0                    pypi_0    pypi
expat                     2.5.0                hb7217d7_1    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
filelock                  3.13.1                   pypi_0    pypi
flake8                    6.1.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.46.0           py39h17cfd9d_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
freexl                    2.0.0                hfbad9fb_0    conda-forge
fsspec                    2023.12.1          pyhca7485f_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
george                    0.4.0            py39hf8cecc8_6    conda-forge
geos                      3.12.1               h965bd2d_0    conda-forge
geotiff                   1.7.1               h71398c0_14    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
gflags                    2.2.2             hc88da5d_1004    conda-forge
giflib                    5.2.1                h1a8c8d9_3    conda-forge
glog                      0.6.0                h6da1cb0_0    conda-forge
gwcs                      0.20.0             pyhd8ed1ab_0    conda-forge
h5netcdf                  1.3.0              pyhd8ed1ab_0    conda-forge
h5py                      3.10.0          nompi_py39haa70198_100    conda-forge
hdf4                      4.2.15               h2ee6834_7    conda-forge
hdf5                      1.14.2          nompi_h3aba7b3_100    conda-forge
icu                       73.2                 hc8870d7_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
image-registration        0.2.8.dev10+g6cc4c81          pypi_0    pypi
imagecodecs               2023.9.18        py39ha02826a_2    conda-forge
imageio                   2.31.5             pyh8c1a49c_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.0              pyha770c72_0    conda-forge
importlib-resources       6.1.1              pyhd8ed1ab_0    conda-forge
importlib_metadata        7.0.0                hd8ed1ab_0    conda-forge
importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.26.0             pyh3cd1d5f_0    conda-forge
ipython                   8.18.1             pyh707e725_3    conda-forge
ipywidgets                8.1.1              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json-c                    0.17                 h40ed0f5_0    conda-forge
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonpointer               2.4              py39h2804cbe_3    conda-forge
jsonschema                4.20.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.11.2          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.20.0             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0             pyhd8ed1ab_10    conda-forge
jupyter-lsp               2.2.1              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.0              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.5.0            py39h2804cbe_0    conda-forge
jupyter_events            0.9.0              pyhd8ed1ab_0    conda-forge
jupyter_server            2.12.1             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.9              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.2             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.9              pyhd8ed1ab_0    conda-forge
jwst                      1.11.4                   pypi_0    pypi
jxrlib                    1.1                  h27ca646_2    conda-forge
kealib                    1.5.2                h47b5e36_1    conda-forge
kiwisolver                1.4.5            py39hbd775c9_1    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
lazy_loader               0.3                pyhd8ed1ab_0    conda-forge
lcms2                     2.16                 ha0e7c42_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20230802.1      cxx17_h13dd4ca_0    conda-forge
libaec                    1.1.2                h13dd4ca_1    conda-forge
libarchive                3.7.2                h82b9b87_0    conda-forge
libarrow                  14.0.1           h63c4d5d_4_cpu    conda-forge
libarrow-acero            14.0.1           had9dd58_4_cpu    conda-forge
libarrow-dataset          14.0.1           had9dd58_4_cpu    conda-forge
libarrow-flight           14.0.1           h1011bfc_4_cpu    conda-forge
libarrow-flight-sql       14.0.1           h660fe36_4_cpu    conda-forge
libarrow-gandiva          14.0.1           h2b96968_4_cpu    conda-forge
libarrow-substrait        14.0.1           h594d712_4_cpu    conda-forge
libavif16                 1.0.3                h4cb461b_0    conda-forge
libblas                   3.9.0           20_osxarm64_openblas    conda-forge
libboost-headers          1.83.0               hce30654_0    conda-forge
libbrotlicommon           1.1.0                hb547adb_1    conda-forge
libbrotlidec              1.1.0                hb547adb_1    conda-forge
libbrotlienc              1.1.0                hb547adb_1    conda-forge
libcblas                  3.9.0           20_osxarm64_openblas    conda-forge
libcrc32c                 1.1.2                hbdafb3b_0    conda-forge
libcurl                   8.4.0                h2d989ff_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.19                 hb547adb_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libevent                  2.1.12               h2757513_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgdal                   3.7.3                h27415a3_7    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_1    conda-forge
libgfortran5              13.2.0               hf226fd6_1    conda-forge
libglib                   2.78.2               hb438215_0    conda-forge
libgoogle-cloud           2.12.0               hfb399a7_4    conda-forge
libgrpc                   1.59.3               hbcf6334_0    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
libkml                    1.3.0             h1eb4d9f_1018    conda-forge
liblapack                 3.9.0           20_osxarm64_openblas    conda-forge
libllvm15                 15.0.7               h504e6bf_3    conda-forge
libnetcdf                 4.9.2           nompi_hb2fb864_112    conda-forge
libnghttp2                1.58.0               ha4dd798_0    conda-forge
libopenblas               0.3.25          openmp_h6c19121_0    conda-forge
libparquet                14.0.1           heaab74a_4_cpu    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libpq                     16.1                 hd435d45_0    conda-forge
libprotobuf               4.24.4               hc9861d8_0    conda-forge
libre2-11                 2023.06.02           h1753957_0    conda-forge
librttopo                 1.1.0               hc8f776e_15    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libspatialite             5.1.0                h66af7d6_2    conda-forge
libsqlite                 3.44.2               h091b4b1_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libthrift                 0.19.0               h026a170_1    conda-forge
libtiff                   4.6.0                ha8a6c65_2    conda-forge
libutf8proc               2.8.0                h1a8c8d9_0    conda-forge
libwebp-base              1.3.2                hb547adb_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libxml2                   2.11.6               h0d0cfa8_0    conda-forge
libzip                    1.10.1               ha0bc3c6_3    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
libzopfli                 1.0.3                h9f76cd9_0    conda-forge
llvm-openmp               17.0.6               hcd81f8e_0    conda-forge
lmfit                     1.2.2              pyhd8ed1ab_1    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.2            py39h0d94542_1    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
lzo                       2.10              h642e427_1000    conda-forge
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3            py39h0f82c59_1    conda-forge
matplotlib                3.8.2            py39hdf13c20_0    conda-forge
matplotlib-base           3.8.2            py39h1a09f3e_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
mdit-py-plugins           0.4.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
minizip                   4.0.3                hd5cad61_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.7            py39he9de807_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
myst-parser               2.0.0                    pypi_0    pypi
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert                 7.12.0             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.12.0             pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.12.0             pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
nbsphinx                  0.9.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h463b476_2    conda-forge
nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
netcdf4                   1.6.5                    pypi_0    pypi
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
notebook                  7.0.6              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
nspr                      4.35                 hb7217d7_0    conda-forge
nss                       3.95                 h6cf673f_0    conda-forge
numcodecs                 0.12.1           py39h4ce5507_0    conda-forge
numpy                     1.23.0           py39h7df2422_0    conda-forge
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
opencv-python-headless    4.8.1.78                 pypi_0    pypi
openjpeg                  2.5.0                h4c1507b_3    conda-forge
openssl                   3.1.4                h0d3ecfb_0    conda-forge
orc                       1.9.2                h7c018df_0    conda-forge
overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.3            py39hf8cecc8_0    conda-forge
pandoc                    3.1.3                hce30654_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parsley                   1.3                      pypi_0    pypi
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.4.1              pyhd8ed1ab_0    conda-forge
pcre2                     10.42                h26f9a81_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
photutils                 1.10.0           py39h373d45f_1    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.1.0           py39h755f0b7_0    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.42.2               h13dd4ca_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
poppler                   23.11.0              hcdd998b_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
poppy                     1.1.1                    pypi_0    pypi
postgresql                16.1                 hc6ab77f_0    conda-forge
proj                      9.3.0                h52fb9d0_2    conda-forge
prometheus_client         0.19.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.41             pyha770c72_0    conda-forge
prompt_toolkit            3.0.41               hd8ed1ab_0    conda-forge
psutil                    5.9.5            py39h0f82c59_1    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   14.0.1          py39h5c469ea_4_cpu    conda-forge
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
pycodestyle               2.11.1             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyerfa                    2.0.1.1          py39h373d45f_0    conda-forge
pyflakes                  3.1.0              pyhd8ed1ab_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyobjc-core               10.0             py39h4d1a642_0    conda-forge
pyobjc-framework-cocoa    10.0             py39h4d1a642_1    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    7.4.3              pyhd8ed1ab_0    conda-forge
pytest-cov                4.1.0              pyhd8ed1ab_0    conda-forge
pytest-doctestplus        1.0.0              pyhd8ed1ab_0    conda-forge
python                    3.9.7           hc0da0df_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.19.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1            py39hf4a74a7_1    conda-forge
pyyaml                    6.0.1            py39h0f82c59_1    conda-forge
pyzmq                     25.1.2           py39he1e2164_0    conda-forge
qtconsole-base            5.5.1              pyha770c72_0    conda-forge
qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
rasterio                  1.3.9            py39hf910321_0    conda-forge
rav1e                     0.6.6                h69fbcac_2    conda-forge
re2                       2023.06.02           h6135d0a_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.31.1             pyhd8ed1ab_0    conda-forge
reproject                 0.13.0           py39h373d45f_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.13.2           py39h8fec3ad_0    conda-forge
scikit-image              0.22.0           py39hf8cecc8_2    conda-forge
scikit-learn              1.3.2            py39h172c841_2    conda-forge
scipy                     1.9.3                    pypi_0    pypi
semantic_version          2.10.0             pyhd8ed1ab_0    conda-forge
send2trash                1.8.2              pyhd1c38e8_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
setuptools-scm            8.0.4              pyhd8ed1ab_0    conda-forge
shapely                   2.0.2            py39ha70ab96_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h17c5cce_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
spherical-geometry        1.3.1                    pypi_0    pypi
sphinx                    7.2.6              pyhd8ed1ab_0    conda-forge
sphinx-automodapi         0.16.0             pyh6ff6d48_0    conda-forge
sphinx-rtd-theme          2.0.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.7              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.5              pyhd8ed1ab_0    conda-forge
sphinxcontrib-htmlhelp    2.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jquery      4.1                      pypi_0    pypi
sphinxcontrib-jsmath      1.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-qthelp      1.0.6              pyhd8ed1ab_0    conda-forge
sphinxcontrib-serializinghtml 1.1.9              pyhd8ed1ab_0    conda-forge
sqlite                    3.44.2               hf2abe2d_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
stcal                     1.4.4                    pypi_0    pypi
stdatamodels              1.7.2                    pypi_0    pypi
stpipe                    0.5.1                    pypi_0    pypi
stsci-image               2.3.5                    pypi_0    pypi
stsci-imagestats          1.8.0                    pypi_0    pypi
stsci-stimage             0.2.6                    pypi_0    pypi
svo-filters               0.4.4                    pypi_0    pypi
svt-av1                   1.7.0                hb765f3a_0    conda-forge
tblib                     2.0.0              pyhd8ed1ab_0    conda-forge
terminado                 0.18.0             pyh31c8845_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tifffile                  2023.9.26          pyhd8ed1ab_0    conda-forge
tiledb                    2.16.3               he15c4da_3    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.3.3            py39h0f82c59_1    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.0             pyhd8ed1ab_0    conda-forge
tweakwcs                  0.8.5                    pypi_0    pypi
types-python-dateutil     2.8.19.14          pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzcode                    2023c                h1a8c8d9_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
uncertainties             3.1.7              pyhd8ed1ab_0    conda-forge
unicodedata2              15.1.0           py39h0f82c59_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
uriparser                 0.9.7                hb7217d7_1    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.12             pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.7.0              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.9              pyhd8ed1ab_0    conda-forge
wiimatch                  0.3.2                    pypi_0    pypi
xarray                    2023.11.0          pyhd8ed1ab_0    conda-forge
xarray-einstats           0.6.0              pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.4                hd886eac_3    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zarr                      2.16.1             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.5                h965bd2d_0    conda-forge
zfp                       1.0.0                h82938aa_4    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zlib-ng                   2.0.7                h1a8c8d9_0    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin218** [comment]
This issue was just resolved in #600.  Please pull the latest dev version of Eureka! and you should have no problems.
