### ISSUE TITLE
Update contributors on the docs Copyright page

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#633]
My former intern Isaac Edelman who contributed significant changes/improvements to the Stage 3 photometry code was wondering if he could be added to the Copyright page at https://eurekadocs.readthedocs.io/en/latest/copyright.html which made me realize we haven't updated that page since May 20, 2022 when we added Yoni Brande.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin218** [comment]
Yes! Is that something I need to do?

**Comment by taylorbell57** [comment]
Any of us can update it with a PR, we just need to decide who all we want to add
