### ISSUE TITLE
Question regarding NIRISS 

### ISSUE THREAD

**Issue by LauraSalmonsen** [kevin218/Eureka#634]
### Instrument

NIRISS (Stages 1-3)

### What happened?

I'm looking to run Eureka! on some NIRISS data for stage 1 and 2. Following the Quickstart guide, I'm having trouble understanding which demo files to use for NIRISS - it seems that there is no appropriate file for stage 2. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Hey there, at present Eureka! does not explicitly support NIRISS for Stages 1-2 and has no support for NIRISS in Stage 3, but we did get some funding from STScI to add NIRISS support which will likely happen this summer. That said, Eureka!'s Stages 1-2 are largely just wrappers for the `jwst` pipeline's Stages 1-2, so I expect Eureka!'s Stages 1-2 should probably work fine for NIRISS files, but you do so at your own risk and I currently don't have the expertise to help troubleshoot things. I'll point out that Adina Feinstein has experience with NIRISS and has developed [nirHiss](https://github.com/afeinstein20/nirhiss) which you could look into if you need to analyse some NIRISS data before we're able to add NIRISS support. Michael Radica has also developed [exoTEDRF](https://github.com/radicamc/supreme-spoon) (formerly called supreme-SPOON) which might also support your needs in the interim.

As for which files to use if you want to try Eureka!'s Stages 1-2, the 2022-DataShowcase folder on Box can be found by clicking the [STScI Box site](https://stsci.app.box.com/s/tj1jnivn9ekiyhecl5up7mkg8xrd1htl/folder/154382715453) on the Quickstart tutorial and contains a NIRISS folder. Inside there, there is an Uncalibrated folder which contains the `_uncal.fits` files you can run Stage 1 on, and inside the Stage 1 folder there are `_rampfitstep.fits` files which I think should be the same as `_rateints.fits` files (the final extension can depend on how the files were made).

I'm going to close this issue now, but know that we do intend to add NIRISS support soon and are hopeful that you'll give our implementation a try once it is ready!
