### ISSUE TITLE
[Bug]: Setting CorrectDrift to False causes wfc.py in Stage 4 to crash

### ISSUE THREAD

**Issue by astroRez** [kevin218/Eureka#639]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Other (any stage)

### What happened?

Because lc.driftmask isn't created when correctDrift is set to False, an error is raised stating lc.driftmask doesnt exist. 
To resolve this, please change line 82 in wfc3.py of Stage 4 from:

`lc.driftmask['time'] = time`

to 

```
if meta.correctDrift: 
    lc.driftmask['time'] = time
```
    

Which seems to resolve the issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
@kevin218, I see you already made a commit that resolves this in some branch (I can't tell which) - did you want to make a PR with that commit?

**Comment by kevin218** [comment]
It was merged with #641. We can close this issue.
