### ISSUE TITLE
[Enhancement]: Add phase curve amplitude and offset calculations to Stage 6

### ISSUE THREAD

**Issue by kevin218** [kevin218/Eureka#655]
### Instrument

Light curve fitting (Stages 4-6)

### What is your suggestion?

The current settings (e.g., `pc_offset` and `pc_amp`) calculate the phase curve offset and amplitude of the individual orders, not the combined phase curve.  We should add functionality for computing the actual offset, amplitude, and A_obs.  We should also clarify some of the language/parameters names so as to avoid confusion in ReadTheDocs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
@kevin218, were you wanting to address this before v1.0? Not sure if this was what you were thinking of with the `Fit phase curve, generate amplitude and offsets (S4-S6)` testing component

**Comment by kevin218** [comment]
@taylorbell57 Thanks for reminding me.  I'll look into it asap to see if there's an easy implementation.

**Comment by taylorbell57** [comment]
One option could be to call them `order1_offset`, `order1_amp`, `order2_offset`, and `order2_amp` for the current S6 outputs that are already supported, and then use `pc_offset` and `pc_amp` for the S6 outputs that you want?
