### ISSUE TITLE
Stage 4 Cross-Correlation Fails for MIRI

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#66]
The Stage 4 cross-correlation step (used to correct for drift/jitter in the 1D spectra) fails on every frame when run on the MIRI simulated data. While the MIRI data are blackbody simulations (compared to the NIRCam simulated data which have spectral features), I think there should still be plenty of curvature and features in the 1-D spectrum for the cross-correlation step to work. Because the step is run inside a try-catch statement, I don't yet understand why it is failing, but the output cross-correlation strength plot looks like an exponential decay, so it seems like it wants to shift the spectrum unreasonably to the left. I have tried setting `sub_mean` to True and False, but neither option works. The code does work for NIRCam data (haven't been able to test on NIRSpec yet), so the issue seems to be MIRI specific for some reason.

If others want to try and tackle this, please feel free - otherwise I'll try to get to this in a day or few.

**Comment by taylorbell57** [comment]
The MIRI spectra are quite featureless and have a strong variation in flux with wavelength. As a result, the cross-correlation just wants to shift the spectra as far to the left as it can since the star is brighter at shorter wavelengths. I've yet to work out if/how we can still do cross-correlation with these mock observations.

![Fig4500-0-CC_Spec](https://user-images.githubusercontent.com/24514122/139504948-33675ac9-cfd7-4f57-9637-238c44634397.png)

**Comment by taylorbell57** [comment]
For reference, the NIRCam simulated observations are much more feature dense, so the cross-correlation step works well enough for them with the exception of a slight bias which could have a similar origin to the bias from the MIRI data.

![Fig4500-0-CC_Spec](https://user-images.githubusercontent.com/24514122/139505843-a8b0797f-296e-4b7d-bf8e-438dcec63069.png)
Figure 1. Extracted NIRCam spectra

![Fig4101-Drift](https://user-images.githubusercontent.com/24514122/139505888-3ed093dd-0c42-4614-ab52-e94505eb0ce7.png)
Figure 2. Fitted spectral drifts from NIRCam spectra showing a slight bias

**Comment by taylorbell57** [comment]
The only thing I've come up with that at least partially works here is subtracting a boxcar filtered version of the spectrum which removes most of the continuum variations but mostly leaves the spectral lines. This was done using the following:
```
from astropy.convolution import convolve, Box1DKernel
def highpassfilt(signal, highpassWidth):
    g = Box1DKernel(highpassWidth)
    return convolve(signal, g, boundary='extend')
ref_spec -= highpassfilt(ref_spec, highpassWidth)
```
where `highpassWidth` is several spectral elements (3-30 as a ballpark). Note that this is done instead of subtracting the mean of `ref_spec`.

There is a fair bit of scatter in the determined drift though. With the current method, the standard deviation in the determined drift for NIRCam simulated observations (which doesn't have any real spectral drift/scatter) is 0.0048 pixels. For my slightly tweaked method, I get standard deviations of 0.0076 pixels (highpassWidth=3), 0.0160 pixels (highpassWidth=5), 0.0732 pixels (highpassWidth=10), 0.0825 pixels (highpassWidth=20), and 0.1823 pixels (highpassWidth=30). This may be driven by the fact that the cross-correlation values look nothing at all like a Gaussian, so trying to fit them with a Gaussian is likely only adding scatter - the same is true, however, for the current cross-correlation method. For both methods, I tried using `np.roll` to introduce a 1 pixel shift in some of the spectra, and both methods were able to approximately recover that value. While the current method has a slight bias (-0.0401 pixels), my method shows no statistically significant biases for the NIRCam simulations (for 3-30 pixel boxcars), but there is a significant bias in for boxcars 10 pixels wide or larger for the MIRI simulations.

I've also found a cross-correlation method in PyAstronomy (pyasl.crosscorrRV) which at least in principle seems to work. If I first subtract the spectra's continua with the `highpassfilt()` function, then there appears to be minimal bias or scatter in the retrieved drift/jitter for the NIRCam data I tested it on. Specifically, I get 0 pix scatter with a -9.9e-15 bias for highpassWidth = 10 and no oversampling on the reference spectrum. For 3x oversampling on the reference spectrum (using `kind="quadratic"`), I get 0.0025 pix scatter and -0.0022 pix bias and for 10x oversampling (using `kind="quadratic"`), I get 0 scatter with a -9.9e-15 bias. I was successfully able to recover integer shifts in the spectrum (made using np.roll), but I haven't got a interpolater working yet to test if the method can recover fractional pixel shifts. For future reference, I've included below the code I wrote based on the example on the [PyAstronomy documentation page](https://pyastronomy.readthedocs.io/en/latest/pyaslDoc/aslDoc/crosscorr.html).

```
from PyAstronomy import pyasl
from scipy.interpolate import interp1d
from tqdm import tqdm
import numpy as np
import matplotlib.pyplot as plt

# wave_1d and optspec are output from S3 and need to be loaded before running the following. Must also define the highpassfilt as written above

induce_jitter = False
highpassWidth = 10
interp_scale = 3
if interp_scale==1:
    wave_high = wave_1d
    tf_high = optspec[-1]
else:
    wave_high = np.arange(wave_1d[0], wave_1d[-1], (wave_1d[1]-wave_1d[0])/interp_scale)
    fn = interp1d(wave_1d, optspec[-1], kind='quadratic')
    tf_high = fn(wave_high)

for n in tqdm(range(meta.n_int)):
    tf = np.copy(tf_high)
    tw = np.copy(wave_high)
    tf /= np.max(tf)

    # Create data, which are not that well sampled
    dw = np.copy(wave_1d)
    df = np.copy(optspec[n])
    df /= np.max(df)
    
    if n%400==0 and induce_jitter:
        # Introdude a shift in the spectra on occasion to see if we can recover it. Hacky but works okayish
        df = np.roll(df, 1)

    df -= highpassfilt(df, highpassWidth)
    tf -= highpassfilt(tf, highpassWidth*interp_scale)

    vpix = (dw[1]-dw[0])/dw[0]*astropy.constants.c.value/1e3
    vmax = vpix*5
    dv = vpix/50

    # Carry out the cross-correlation.
    rv, cc = pyasl.crosscorrRV(dw, df, tw, tf, -vmax, vmax, dv, skipedge=50)

    # Find the index of maximum cross-correlation function
    maxind = np.argmax(cc)
    
    # Fit a Gaussian to the cross-correlation outputs
    params, err = g.fitgaussian(cc/cc.max(), rv, guess=[vmax/5., rv[maxind], 1])

    #meta.drift1d[n] = rv[maxind]/vpix*4/3
    meta.drift1d[n] = params[1]/vpix*4/3
    
    if n%200==0:
        # Plot the occasional cross-correlation result to make sure things look reasonable
        plt.plot(rv, cc, 'bp-')
        plt.plot(rv[maxind], cc[maxind], 'ro')
        model  = g.gaussian(rv, params[0], params[1], params[2]*cc.max())
        plt.plot(rv, model)
        plt.show()
```

Given that the modelled observations have no drift/jitter, anything we do with this step is only going to add bias or noise though, so I think I will stop looking into this question for now and return to this issue once we have simulations with drift/jitter or we get some real data. For now, I recommend all future S4 runs set `correctDrift` equal to `False`.

**Comment by kevin218** [comment]
I like the idea of applying a high-pass filter, before calling the cross correlation (CC) routine. When it comes time to reducing real data where we don't know the answer, it may be that we'll want to apply several options and see which one produces the smoothest drift and the smallest jitter.

I see this as a nice task for S4... to implement a suite of CC options, iterate through them with different settings, compare drift/jitter values, and select the best option.

**Comment by taylorbell57** [comment]
Okay, well I'll implement what I have so far then since it's functional and a viable option at least, and then we can add other methods as we think of them and test them later on real data
