### ISSUE TITLE
How reliable is MIRI flux calibration?

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#664]
@taylorbell57 , thank you so much! I wonder, can we please impose on you to ask a scientific question about this? Would you treat a photometrically calibrated Stage 3 output as a good estimate of the intrinsic absolutely calibrated flux of the star, which could be used to convert eclipse depths into planetary fluxes? Or would you do some other magic, like using a really large extraction aperture, applying an aperture correction, and/or worrying more about non-linearity?

_Originally posted by @zkbt in https://github.com/kevin218/Eureka/issues/662#issuecomment-2181389514_

**Comment by taylorbell57** [comment]
So this is a bit of a complicated question to answer. I've opened a new issue to discuss this so that it's easier for people to find in the future when searching through old GitHub issues.

The short answer is that I (personally) don't currently have a high level of trust in MIRI/LRS flux-calibrated spectra from TSO data. I have put a fair bit of time into trying flux calibration on several GTO TSO observations as well as the MIRI/LRS flux calibration observations of HD 37962, HD 106252, HD 167060. While I've gotten spectra that can be qualitatively compared to stellar models as a sanity check (in one case, it made it clear that we needed to use a different stellar model), I've yet to get something I'd consider publication ready or directly usable for converting eclipse depths into planetary fluxes.

**Here goes the long answer:**

Below I've attached a figure showing the captured flux as a function of aperture radius which was computed using the aperture correction reference file from PMAP 1188. As is often the case with absolute calibration, you need to trade off between having a large enough source aperture that your aperture correction value doesn't introduce significant error while also not including too much background which increases your uncertainty and may bias you if you've over- or under-subtracted the background flux.
![MIRI_ApertureCorrections_PMAPjwst1188](https://github.com/kevin218/Eureka/assets/24514122/b2d6b9f0-5745-4fc5-852f-f51134a5f448)

In my "best" calibrated spectra to date, I used the 9-pixel radius aperture marked in the above image (since the aperture correction was then near 100% and wasn't steeply changing with radius), and then I applied the aperture correction. However, as you can see from the next image, there are still two issues with these calibrated spectra. First, there's a very obvious issue in the "shadowed region" from 10.6-11.8 microns, and then there is still an issue with uncertainty in the overall baseline with the three calibrator stars being off from their models by 4-8%.
![MIRI_Calibrators_BOSZ_PMAPjwst1188](https://github.com/kevin218/Eureka/assets/24514122/443374b2-5753-417e-bd1c-0fc766ac993c)

Since the impact of the "shadowed region" is so consistent between the three different calibrator stars (as is some of the high-frequency noise in the spectrum), I tried taking the median of the three to make a spectroscopic scale factor that should hopefully be able to be applied to different targets. The resulting stellar spectra for the calibrator stars is shown below.
![MIRI_Calibrators_BOSZ_CustomCalibration_PMAPjwst1188](https://github.com/kevin218/Eureka/assets/24514122/dbb428cc-6042-450f-a96b-1be3a11a8d92)

As you can see, those calibrated spectra now look like they pretty closely match their stellar models, but there is still a ±2% offset. I then repeated this process on a handful of GTO MIRI/LRS observations, and I tried to keep as many of the Stage 1-3 parameters the same between the reduction of the science observations and the calibration observations. However, with the science targets I don't get near as nice an agreement with stellar models. I've attached below my attempt with WASP-39b. I've also attached a more typical example of WASP-80, where there is a kind of `v` shape to the ratio between the stellar model and the observed spectrum with a ~4% peak-to-trough amplitude of the `v` shape.
![WASP39b_ModelRatio_PMAPjwst1188](https://github.com/kevin218/Eureka/assets/24514122/8c8a8628-7eb0-4ae8-81c2-b484f748fa16)
![WASP80b_ModelRatio_PMAPjwst1188](https://github.com/kevin218/Eureka/assets/24514122/d4574ccc-0f58-4c64-b887-e898550f6fa6)

Laura Flagg was previously told by the JWST help desk that the systematic uncertainties on LRS flux calibrated spectra are on the order of ~10% (which is also stated in [Flagg+2024](https://ui.adsabs.harvard.edu/abs/2024arXiv240602305F/abstract)). Based on these attempts of mine, I'd say that (after applying all the procedures I described above) it seems possible to get the average error below 10% but the maximum deviation may still exceed 10% (in the case of WASP-39b, unless that excess at long wavelengths is caused by a debris disk as hypothesized in Flagg+2024). However, one of our GTO targets is off from its predictive model by an average of ~20% and still shows the `v` shape in the ratio of the spectra (with the same ~4% amplitude); if real, that ~20% flux offset could imply a ~10% error in the stellar radius, but I don't know that I'm confident enough in the robustness of these calibrated spectra to claim that.

I don't yet know for sure what is causing the pretty consistent `v`-shaped ratio, but I suspect it may have something to do with over-subtraction of the background flux caused by the "[cruciform artifact](https://jwst-docs.stsci.edu/depreciated-jdox-articles/miri-instrument-features-and-caveats#MIRIInstrumentFeaturesandCaveats-cruciformCruciformartifact)". It's possible the calibrator stars had an adequately different background level and/or different SNR that causes this difference between the science and calibrator objects. But this is as far as I've been able to push MIRI/LRS flux calibration, and I likely won't be able to push this much further without substantial further effort and potentially STScI support.

Since this is a bit "off topic" and pushing beyond what STScI should be reasonably possible with the current state of the reference files, I'm going to close this issue so it doesn't clutter our to-do list, but feel free to comment/respond below (these closed issues never get deleted), and if/when we get more support from STScI then we can certainly reopen this issue or open a new one.

**Comment by zkbt** [comment]
OMG, thank you @taylorbell57! I figured you had already thought about this question a lot, and you didn't disappoint! I so deeply value the really thorough and cautious response! 

It sounds like our immediate takeaway is that we'll likely proceed with the model that's more directly tied to the bolometric luminosity of the star. However, we'll also do a little more digging to see whether the differences we're seeing between observations and model spectra are consistent with the picture you outlined above. 

Thank you!!

**Comment by Pat-Wachiraphan** [comment]
Hi @taylorbell57, Thank you so much; it really helps! We are still planning to obtain as good a flux-calibrated flux as we can. You mentioned "aperture correction." I'm curious if there is a way to implement this in Eureka since it doesn't seem too obvious to me!

Thank you again!

**Comment by taylorbell57** [comment]
@Pat-Wachiraphan, I'll consider this but likely won't add this very soon since I still don't really trust the flux-calibration and have several other higher-priority tasks, but in the meantime that reference file can be found at https://jwst-crds.stsci.edu/browse/jwst_miri_apcorr_0012.fits and is also described in more detail at https://jwst-pipeline.readthedocs.io/en/latest/jwst/references_general/apcorr_reffile.html
