### ISSUE TITLE
[Enhancement]: bg_disp (now called bg_row_by_row), bg_dir, and isrotate all seem to control the same thing

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#675]
This seems problematic. I'll need to look into this

_Originally posted by @kevin218 in https://github.com/kevin218/Eureka/pull/632#discussion_r1660427023_

**Comment by taylorbell57** [comment]
@kevin218, this may be worth addressing before v1.0 since it could result in some meaningful changes to ECF parameters

**Comment by kevin218** [comment]
@taylorbell57 After a few tests, I've managed to simplify the code so that `bg_dir` and `isrotate` do not need to be specified in `s3_meta.py`.
