### ISSUE TITLE
Question regarding slit_y_low  and slit_y_high in stage 2 with data from NIRSpec G395H of  WASP-39

### ISSUE THREAD

**Issue by Paulinappl** [kevin218/Eureka#690]
### Instrument

NIRISS (Stages 1-3)

### What happened?

I understand that my ecf files should be like the demo ecf files of the version I'm using, I'm currently using v0.10 and in the demo file of stage 2 slit_y_low  and slit_y_high are set like this:

slit_y_low              -1      # Use None to rely on the default parameters
slit_y_high             50     # Use None to rely on the default parameters

But my y axis in the fits files I'm using from MAST goes from y = 0 to y = 32, and using DS9 I saw that the spectral trace falls between y =  6 and y = 27, my guess would be to set slit_y_low   to 6 and slit_y_high to 27, but since I've been recommended to follow the demo files, I'm unsure on what to set those two values.

### Error traceback output

none.

### What operating system are you using?

Ubuntu 18.04.6 LTS

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

I don' t think it's needed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin218** [comment]
Follow the demo file. Do not adjust these two parameters.

**Comment by Paulinappl** [comment]
Ok, thank you :)
