### ISSUE TITLE
Question regarding ywindow in stage 3 ecf file.

### ISSUE THREAD

**Issue by Paulinappl** [kevin218/Eureka#691]
### Instrument

NIRSpec (Stages 1-3)

### What happened?

In issue #685  that I posted Taylor Bell suggested to leave xwindow as [5,1950] , I currently have ywindow as [0,32] , but since I saw on DS9 that the spectral trace is within y=6 and y=27, approximately, should I set ywindow  to those values?, or [0,32]  which is the whole y axis for the MAST fits file of WASP-39b that I downloaded, or  [2,28]  the value on the demo file of my version for ywindow?

### Error traceback output

none

### What operating system are you using?

Ubuntu 18.04.6 LTS

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

not relevant.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
When in doubt, it is typically best to leave the y-window as large as you can (to get a more reliable background flux estimate, and in the case of NIRSpec G395H data to avoid removing rows which contain some of the spectral trace). You can always experiment to see what works best, but in all my NIRSpec G395H observations I've set `ywindow` to `[0,32]`.

**Comment by Paulinappl** [comment]
Got it, thank you :)
