### ISSUE TITLE
Should exotic-ld be used for LD coefficients in stage 4 with NIRSpec? 

### ISSUE THREAD

**Issue by Paulinappl** [kevin218/Eureka#692]
### Instrument

Light curve fitting (Stages 4-6)

### What happened?

To me the reasonable thing would be to calculate limb darkening coefficients during stage 4, in order to "fix" the limb darkening effect in the data, but in the demo of v0.10 LD is set like:

`compute_ld      False`

So my question is: Should I leave it like that?, or should I use exotic-ld?

I also have this question because in the user considerations for stage 4 in this video: https://www.youtube.com/watch?v=McsmpcHcOdk&t=1634s it's reccomended to use exotic-ld.

 

### Error traceback output

none

### What operating system are you using?

Ubuntu 18.04.6 LTS

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

not needed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
This is really up to you.

If you precompute the ExoTiC-LD modelled limb-darkening coefficients in Stage 4, in Stage 5 you can then fix the limb-darkening coefficients to that chosen model or impose a Gaussian prior centered on that model. But limb-darkening models are not perfect, and different people have different mindsets as to what is the "best" approach to fitting/fixing limb-darkening coefficients. You can always precompute the ExoTiC-LD model coefficients, but we didn't want to force everyone to do that, and you'll have to update the stellar parameters and make at least a semi-informed choice as to which stellar model you want ExoTiC-LD to use.

My personal approach is typically to freely fit the two parameters of the kipping2013 parameterization in Stage 5, and then see how those fitted coefficients compare to the many different model predictions ExoTiC-LD offers (there are many different stellar models listed [here](https://exotic-ld.readthedocs.io/en/latest/views/supported_stellar_grids.html)). If there is a good match between my fitted coefficients and one of the predictions (or at least "good enough" to my tastes), then I typically fix my limb-darkening coefficients to the predictions from that model.

This is getting into the "art" of data fitting though, and experimentation is definitely recommended to see what works best for you and your data.

**Comment by Paulinappl** [comment]
Great advice Taylor, thank you so much.
