### ISSUE TITLE
[Enhancement]: Label colors of data points in Stage 3 xdrift and ydrift plots.

### ISSUE THREAD

**Issue by astroRez** [kevin218/Eureka#709]
### Instrument

Other (any stage)

### What is your suggestion?

Can you please label if the markers shown in the Stage 3 xdrift and ydrift plots (for HST observations) are for the forward or reverse scan directions?

Here's an example:

```
def plot_drift_2D(data, meta):
    '''Plot the fitted 2D drift. (Fig 3106)

    Parameters
    ----------
    data : Xarray Dataset
        The Dataset object.
    meta : eureka.lib.readECF.MetaClass
        The metadata object.
    '''
    plt.figure(3106, figsize=(8, 6))
    plt.clf()
    plt.subplot(211)
    for p in [0, 1]:
        iscans = np.where(data.scandir.values == p)[0]
        if len(iscans) > 0:
            label = "Direction 0 (Forward)" if p == 0 else "Direction 1 (Reverse)"
            plt.plot(iscans, data.centroid_y[iscans], '.', label=label)
    plt.ylabel(f'Drift Along y ({data.centroid_y.units})')
    plt.legend()
    
    plt.subplot(212)
    for p in [0, 1]:
        iscans = np.where(data.scandir.values == p)[0]
        if len(iscans) > 0:
            label = "Direction 0 (Forward)" if p == 0 else "Direction 1 (Reverse)"
            plt.plot(iscans, data.centroid_x[iscans], '.', label=label)
    plt.ylabel(f'Drift Along x ({data.centroid_x.units})')
    plt.xlabel('Integration Number')
    plt.legend()
    
    plt.tight_layout()
    # fname = f'figs{os.sep}fig3106_Drift2D{plots.figure_filetype}'
    # plt.savefig(meta.outputdir+fname, dpi=300)
    if not meta.hide_plots:
        plt.pause(0.2)
```

Used like so:
`plot_drift_2D(s3_spec, s3_meta)`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Is there a particular scan direction that must always be called "forward" vs "reverse", and/or do round-trip scans always do "forward" and then "reverse"? It'd be relatively trivial to just always call scan direction 0 "forward" and 1 "reverse", but if that isn't always the case then we'll need some trickier code to determine the scan direction

**Comment by jbrande** [comment]
The default scan direction is "forward", and "reverse" scans are only used in round-trip scanning observations (Page 8 in [this document](https://www.stsci.edu/files/live/sites/www/files/home/hst/instrumentation/wfc3/documentation/instrument-science-reports-isrs/_documents/2012/WFC3-2012-08.pdf)). We can probably safely assume direction 0 is "forward" unless something very weird has happened.
