### ISSUE TITLE
  Cannot import name 'LogglyConnection" rom Connection

### ISSUE THREAD

**Issue by mithun1996-png** [kevin218/Eureka#713]
### Instrument

NIRCam (Stages 1-3)

### What happened?

 when i am in stage 1 then this errror basically show 

### Error traceback output

Traceback (most recent call last):
  File "/media/seps3/abb231cd-8a52-48df-a46a-5caa396b751c/data_anlysis_01/MyFirstEureka/Input_file/JWST/run_eureka.py", line 2, in <module>
    import eureka.lib.plots
  File "/home/seps3/miniconda3/envs/eureka/lib/python3.10/site-packages/eureka/__init__.py", line 19, in <module>
    from connection import LogglyConnection
ImportError: cannot import name 'LogglyConnection' from 'connection' (/home/seps3/miniconda3/envs/eureka/lib/python3.10/site-packages/connection/__init__.py)

### What operating system are you using?

Ubuntu

### What version of Python are you running?

python 3.10.14

### What Python packages do you have installed?

# packages in environment at /home/seps3/miniconda3/envs/eureka:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
brotli                    1.0.9                h5eee18b_8  
brotli-bin                1.0.9                h5eee18b_8  
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.9.24            h06a4308_0  
certifi                   2024.8.30                pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
connection                2021.7.20                pypi_0    pypi
contourpy                 1.2.0           py310hdb19cb5_0  
cycler                    0.11.0             pyhd3eb1b0_0  
eureka                    0.15                     pypi_0    pypi
fonttools                 4.51.0          py310h5eee18b_0  
freetype                  2.12.1               h4a9f257_0  
idna                      3.10                     pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306  
jpeg                      9e                   h5eee18b_3  
kiwisolver                1.4.4           py310h6a678d5_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.40                 h12ee557_0  
lerc                      3.0                  h295c915_0  
libbrotlicommon           1.0.9                h5eee18b_8  
libbrotlidec              1.0.9                h5eee18b_8  
libbrotlienc              1.0.9                h5eee18b_8  
libdeflate                1.17                 h5eee18b_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.5.1                h6a678d5_0  
libuuid                   1.41.5               h5eee18b_0  
libwebp-base              1.3.2                h5eee18b_1  
lz4-c                     1.9.4                h6a678d5_1  
matplotlib-base           3.9.2           py310hbfdbfaf_0  
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0           py310h5eee18b_1  
mkl_fft                   1.3.10          py310h5eee18b_0  
mkl_random                1.2.7           py310h1128e8f_0  
ncurses                   6.4                  h6a678d5_0  
numpy                     1.22.0                   pypi_0    pypi
openjpeg                  2.5.2                he7f1fd0_0  
openssl                   3.0.15               h5eee18b_0  
packaging                 24.1            py310h06a4308_0  
pillow                    10.4.0          py310h5eee18b_0  
pip                       24.2            py310h06a4308_0  
pybind11-abi              4                    hd3eb1b0_1  
pyerfa                    2.0.1.4         py310h5eee18b_0  
pyparsing                 3.1.2           py310h06a4308_0  
python                    3.10.14              h955ad1f_1  
python-dateutil           2.9.0post0      py310h06a4308_2  
pyyaml                    6.0.2           py310h5eee18b_0  
readline                  8.2                  h5eee18b_0  
requests                  2.32.3                   pypi_0    pypi
setuptools                75.1.0          py310h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.45.3               h5eee18b_0  
tbb                       2021.8.0             hdb19cb5_0  
tk                        8.6.14               h39e8969_0  
tzdata                    2024b                h04d1e81_0  
unicodedata2              15.1.0          py310h5eee18b_0  
urllib3                   2.2.3                    pypi_0    pypi
wheel                     0.44.0          py310h06a4308_0  
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.13               h5eee18b_1  
zstd                      1.5.6                hc292b87_0  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jbrande** [comment]
It looks like you went to PyPI and installed something that isn't this JWST data reduction package. We're not published on PyPI and can't be installed by name with pip - trying to do that will give you [this unrelated package](https://pypi.org/project/eureka/).

You should try to reinstall Eureka! using the installation instructions in our documentation, [which can be found here](https://eurekadocs.readthedocs.io/en/latest/installation.html).
