### ISSUE TITLE
Clarification on Drift Values Along X and Y Axes in Stage 3 Output Files (Fig 3106)

### ISSUE THREAD

**Issue by Aseman7** [kevin218/Eureka#717]
### Instrument

NIRSpec (Stages 1-3)

### What happened?

In the Eureka! Quickstart, between the Stage 3 output data files, I would like to clarify where I can find the drift values along the x-axis and y-axis. I mean the data in the y-axis in the plot of Fig. 3106.

S3_wasp39b_ap6_bg7_SpecData.h5: This file includes keys like centroid_y, centroid_sy, x, and y, but I am unsure where to find the drift values along the axes.

Could you please point me to the relevant datasets or provide guidance on how to compute the drift values for both axes (x and y)?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
As noted in the figure caption of Fig 3106 on our [Eureka! Outputs page](https://eurekadocs.readthedocs.io/en/latest/outputs.html#id7) on readthedocs, this figure is only made for Hubble/WFC3 observations (and not JWST observations which I presume you are working on). Figures 3104 and 3105 can be made for JWST observations and show the drift/jitter in the spatial direction; the values from these plots are stored in the `centroid_y` and `centroid_sy` variables of the `SpecData.h5` files from Stages 3 and 4 and the `LCData.h5` file from Stage 4. In Stage 4, [Figure 4103](https://eurekadocs.readthedocs.io/en/latest/outputs.html#id18) can be made if you set `recordDrift` to `True` - this figure shows the drift/jitter in the spectral direction based on a cross-correlation computation, and the data plotted in the figure is stored in the `centroid_x` variable of the `LCData.h5` file output by Stage 4. In my experience, the drift/jitter in the spectral direction is normally very small and insignificant, and the cross-correlation computation only really works when there are clear stellar features in the bandpass which means the computation doesn't really work for MIRI/LRS observations. Meanwhile, drift/jitter in the `centroid_y` and `centroid_sy` parameters is also normally quite small but is more frequently useful in removing some correlated noise in the observations
