### ISSUE TITLE
Access parameters through .ecf files

### ISSUE THREAD

**Issue by meganmansfield** [kevin218/Eureka#74]

**Comment by meganmansfield** [comment]
Hey all, just creating this issue so I have a place to leave some notes on my progress (hopefully it's in the right place!). So in the s5_megan branch I now have the code set up to take in both physical light curve parameters (in the file s5_fit_par.ecf) and run parameters for the fit (in the file s5.ecf). Incorporating these parameters involved some arbitrary decisions about what counts as "verbose" and stuff like that, but the code is running for me now! Not all of the parameters in s5.ecf are incorporated, because I wasn't sure if some of them are holdovers from the HST pipeline that may not end up included here.
These are the parameters that are incorporated now: toffset, run_verbose, run_output, run_show_plot, run_mcmc, run_nested, run_lsq, all of the mcmc parameters, and all of the dynesty parameters.
These are the ones that aren't incorporated yet: fix_ld, ld_file (if we want to add a fixed limb darkening ability), run_plot_raw_data, run_fit_white, run_divide_white, save_allan_plot, run_clipsigma, run_clipiters, run_files
Also, I was having an issue with reading in the parameter run_myfuncs where if there was more than one function it was reading it as a list input. For now I've just got it reading in a single function, but if someone knows how to fix this so that it can read a list of functions properly that would be great!

One more unrelated comment: the least squares fit is running fine now, but when I try and run either emcee or dynesty from the run_s5.py script it's throwing an error for the composite model. "TypeError: 'CompositeModel' object is not subscriptable"
Is this an error anyone has seen before?

**Comment by taylorbell57** [comment]
Hey Megan, I haven't yet looked through any of your edits yet, but I was thinking it might be best to have a single input that specifies which optimization routine you want (e.g. fit_method='mcmc') rather than having boolean flags for each of them (e.g. run_mcmc, run_nested, run_lsq), since I imagine we'd only want to run one of the optimization routines.

**Comment by meganmansfield** [comment]
Yeah, that's a good idea! Although if you want to run more than one you'd have to enter them as a list, and then you might run into the same problem I had with run_myfuncs where it was reading the input list as multiple items instead of just one. But once I figure that out it should work fine.

**Comment by taylorbell57** [comment]
Can you explain more what behaviour you were hoping/expecting for the run_myfuncs input? From what I can tell, the read_ecf function is behaving the way it should. My guess is you will need to run a for loop containing an `exec` call to import the functions passed in through the ecf or something like that, but if you explain more what you want to happen I can try and provide more useful feedback

**Comment by meganmansfield** [comment]
Yeah, so the idea was that it would be a list containing the functions you'd like to fit to the data. So as it stands now it just has 'transit', but you could put in something like ['transit','constant','model_ramp'] and it would fit for the transit plus a constant plus an exponential ramp. The issue I think is in the way readECF is set up to read parameters files right now. So for the fit parameters like a/rs, you can input a set of values like 5,free,3,7 and the parameters set-up interprets that as "value, free/fixed, lower limit, higher limit". When I read in the list of functions, I think it's breaking that list apart and trying to interpret it as "value=transit, free/fixed=constant, lower limit=model_ramp,..." So I think we just need to code in a way to keep it from breaking up lists like that. Does that make sense?

**Comment by taylorbell57** [comment]
Ahh okay, I see what you mean - I think changing your inputs in the .ecf file to be a list within a list might work (i.e. `[['transit', 'constant','model_ramp']]`). I'm not totally confident, but it is one thing we can try. The other would be to remove the string characters from the inputs (i.e. `[transit, constant, model_ramp]`.

**Comment by meganmansfield** [comment]
Oh hey, removing the quotes seems to have worked! Thanks!

**Comment by meganmansfield** [comment]
Here's the full traceback for the CompositeModel error:

TypeError                                 Traceback (most recent call last)
~/Documents/Code/Eureka/Eureka/demos/S5/run_S5.py in <module>
     18 
     19 reload(s5)
---> 20 ev5 = s5.fitJWST(eventlabel, workdir, speclc_dir, fit_par, run_par, meta=meta)

~/Documents/Code/Eureka/Eureka/eureka/S5_lightcurve_fitting/s5_fit.py in fitJWST(eventlabel, workdir, speclc_dir, fit_par, run_par_file, meta)
     66             wasp43b_lc.fit(model, fitter='lsq', **run_par.dict)
     67         elif run_par.run_mcmc.value:
---> 68             wasp43b_lc.fit(model, fitter='emcee', **run_par.dict)
     69         elif run_par.run_nested.value:
     70             wasp43b_lc.fit(model, fitter='dynesty', **run_par.dict)

~/Documents/Code/Eureka/Eureka/eureka/S5_lightcurve_fitting/lightcurve.py in fit(self, model, fitter, **kwargs)
    132 
    133             # Run the fit
--> 134             fit_model = f.emceefitter(self, model, **kwargs)
    135 
    136         elif fitter == 'dynesty':

~/Documents/Code/Eureka/Eureka/eureka/S5_lightcurve_fitting/fitters.py in emceefitter(lc, model, **kwargs)
    206     print(lsq_sol)
    207 
--> 208     lc.unc *= np.sqrt(lsq_sol[1])
    209 
    210     all_params = [i for j in [model.components[n].parameters.dict.items()

TypeError: 'CompositeModel' object is not subscriptable

**Comment by taylorbell57** [comment]
Out of curiousity, how many components does your model have (aka is it just transit or does it have other things too)? Does it work if you have more than one function or break either way

**Comment by meganmansfield** [comment]
The model just had one component, but I'm having a hard time getting any other model components to work properly right now...I'll try and get it working to the point where I can test that.

**Comment by meganmansfield** [comment]
Just adding to say I fixed this error! It was something I created fixing a different error, haha.
