### ISSUE TITLE
Add row-by-row background subtraction for NIRCam

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#76]
NIRCam's detector is read out row-by-row instead of column-by-column (at least by default, although this can be switched at the detriment of bright star performance). As a result, NIRCam's 1/f noise is expressed along each row instead of along columns, so performing row-by-row background subtraction will better remove 1/f noise in NIRCam data than columnb-by-column. Worse yet, NIRCam has four amplifiers along the dispersion direction which can each have their own constant offset (and maybe even 1/f noise characteristics - I sure hope not though), so it may even be necessary to perform row-by-row background subtraction per amplifier. It will be important for us to look into how we can perform row-by-row background subtraction for NIRCam observations without self-subtracting the spectra - I can ask the NIRCam TSO team to see if they have any tricks they'd be willing to share, or we can try to come up with our own fully-independent solution and see which works better.

**Comment by afeinstein20** [comment]
I think this could be handled using the 2D background modeling & subtraction I'm using now with NIRISS. It seems to remove the 1/f noise in the column direction fairly well. I imagine with some tweaking it can solve this issue too.

**Comment by taylorbell57** [comment]
@afeinstein20 the main issue is that there is very little of a row that is not exposed to starlight which makes constraining a row-by-row extraction challenging. My understanding is that there are also other important effects like odd/even biases and different offsets for each of the four amplifiers

**Comment by taylorbell57** [comment]
This was resolved by #524
