### ISSUE TITLE
jwst package version for MIRISim data

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#77]
`jwst` version 1.1.0 was previously required by the MIRISim version used to create the simulations provided by the ERS simulated data team, but current MIRISim version 2.4.1 is compatible with the `jwst` pipeline version 1.3.3. This will potentially be important for the March 2022 data challenge which will include new simulations which will most likely make use of the newest MIRISim version. Updating `jwst` to a newer version will have non-negligible impacts on other instruments and code in stages 1 and 2 though, so this will need to be a carefully planned transition when the time comes.

**Comment by AarynnCarter** [comment]
I've just spotted that the latest jwst version is 1.4.0, as of a few days ago. But it seems that MIRISim is still at 2.4.1, so I'm not sure about compatibility. 

With the data challenge in March (as you mention), I'm wondering if we are in a position right now to decide what version of jwst we want to make the code (particularly Stage 1) compatible with?

**Comment by kevin218** [comment]
I suggest emailing Pierre-Olivier Lagage to find out what versions of MIRISim and jwst they plan on using.

**Comment by AarynnCarter** [comment]
Okay, I'll do that now.

**Comment by AarynnCarter** [comment]
Okay, so the situation is that most of the people involved with MIRISim are also on the commissioning team and whilst they are aware of the new jwst package, they don't have any specific plans / roadmap to update anything as of yet. It is currently compatible with version 1.3.3.

Given that we are getting new MIRI simulated data, should we make sure everything runs on 1.3.3?

**Comment by taylorbell57** [comment]
Sure, I think now is probably a good time to migrate to `jwst` v1.3.3. I can make new MIRI simulations with the newer MIRISIM pipeline for in-house testing as well to make sure we're prepared for MIRI data

**Comment by taylorbell57** [comment]
FYI, the current version of MIRISIM uses `jwst` v1.3.2 - not sure how that differs from v1.3.3 and whether it would be compatible with that minor version change

**Comment by taylorbell57** [comment]
Alright, I just checked the old MIRISIM simulations and some new ones I made myself (using the same MIRISIM version as the ERS challenge will use) with `jwst` v1.3.3 and `photutils`>=1.1.0,<1.2 and had no issues running S2->S5. I can check NIRCam and NIRSpec now if @AarynnCarter or others have not already done so

**Comment by AarynnCarter** [comment]
Hey @taylorbell57, that's great news! I'd hold off on NIRSpec briefly as I just got the new injected dataset from David so I think it would be worthwhile to test things with that on my end for a bit. NIRSpec did reduce with the 1.3.3 version I used to develop Stage 1, so I'm not expecting too many differences.
