### ISSUE TITLE
Array Mismatch in NIRSpec data 

### ISSUE THREAD

**Issue by gianninapr** [kevin218/Eureka#86]
This issue pertains the NIRSpec data from the tiny NIRSpec files uploaded by @AarynnCarter in BOX

I'm still unsure about the nature of the issue and whether it is a Eureka error or a data error, but after a conversation with @taylorbell57 and his experience with a similar issue, I'm officially opening this issue for other people to take a look at it.

**THE ERROR**
----------------------

![Screenshot from 2022-01-05 17-47-31](https://user-images.githubusercontent.com/39547400/148300817-39bd14dc-3aec-4c33-b1e5-c7a935f6364c.png)

**THE ISSUE**
------------------------

The error occurs affter running Eureka's S2 wrapper on the JWST pipeline and then trying to use the resulting file on Eureka's Stage 3, the error appears during the S3 run. It seems that an array mismatch happens between the subdata and subgain arrays (the trimmed data and gain arrays). After further tracking the issue, it seems the subgain array only has 2 dimensions (x,y) but the subdata array contains 3 (n,x,y) of which n stands for a single iteration. Eureka is not doing anything to trim that third dimension and therefore the arrays have a mismatch. Yet, even after zeroing in on a single iteration and trimming the subdata array to, say, [0, : , : ] there is still a mismatch in the x dimension between the subdata and subgain arrays that I was unsure how to trace since I am not too familiar with the actual nature of the files themselves. Hence this issue being opened.

**THE FILES USED FOR THIS PARTICULAR RUN**
----------------------------------------------------------------------

- Data Simulation Working Group/NIRSpec/Tiny/jwdata0010010_11010_0001_NRS1_TINY_uncal.fits (**used to run Eureka's S2 on it**)
- Data Simulation Working Group/NIRSpec/Ancillary Files

**HANDWRITTEN NOTES ON THE ISSUE**
-----------------------------------------------------------------------

[IN-DEPTH NOTES ON ISSUE](https://github.com/kevin218/Eureka/files/7818212/Research.Notes.pdf)

**Comment by AarynnCarter** [comment]
I can take a look at this over the next few weeks, hopefully it's nothing too serious and just me doing something wrong when I made the files. 

@gianninapr Thanks for making the effort to detail everything and provide your hand-written notes! I'll let you know if I have any questions :)

**Comment by AarynnCarter** [comment]
@gianninapr Did you run Stage 2 directly on the _uncal.fits file? Or did you process it through Stage 1 / the JWST pipeline first? If it's the former, I expect that might be why we are having issues with array mismatches, as the _uncal.fits file has each individual ramp image, whereas the _rateints.fits file (output from Stage 1) has a single image for each integration. 

Obviously Stage 1 isn't up and running yet, so if it is the above then once we get some clarity on JWST package versions I can test all of this again when I try to merge the Stage 1 updates with the main branch.

**Comment by gianninapr** [comment]
@AarynnCarter Hi! Sorry, I just checked and I copied the wrong filename into the issue here, but I did use the rateints file to run Stage 2 as you describe, not the uncal file. @jbrande is running it on his own with the same file to see if the error is replicated. I'll update the issue description when I'm on my computer!

**Comment by AarynnCarter** [comment]
@gianninapr No worries! Probably something more involved then.

Since I messaged, David Sing and I have started up making new NIRSpec data for the upcoming March meeting. As a result, I’m probably going to hold off looking at this until I have the new dataset ready. They may well have exactly the same issue (I’m betting they will), but I don’t want to commit too much time if it’s an issue unique to this dataset. 

@jbrande Thanks for taking a look on your end! 

We’re hoping to have things ready in the next week or so, at which point I’ll also produce a new tiny dataset for testing!

**Comment by AarynnCarter** [comment]
@jbrande Sounds good, I'll reach out at some point next week when I have things more organised!

**Comment by AarynnCarter** [comment]
Okay I'm not getting this issue with the new tiny NIRSpec dataset, and s3 is running to completion (albeit the results still aren't great yet). 

@gianninapr Could you grab the new dataset and run Stage 2 and 3 again to see if this error still persists? I've attached the .ecf files I used below. Also, if you happen to see the same error as #108, let me know!

Data: https://app.box.com/folder/154382715453?s=tj1jnivn9ekiyhecl5up7mkg8xrd1htl
ECF's: [why_does_github_hate_ecfs.zip](https://github.com/kevin218/Eureka/files/8007036/why_does_github_hate_ecfs.zip)

**Comment by jbrande** [comment]
@AarynnCarter I think I'm actually in charge of this now, I'll take a look.

**Comment by AarynnCarter** [comment]
Great, thanks!

**Comment by gianninapr** [comment]
yes @AarynnCarter sorry about that! Because I have a master thesis to present this semester I passed the baton to Yoni on this respect. I'll still be around if you have anything you want me to take a look at but I'm probably best reached through the Slack since Github notifications are sent to one of my secondary emails and it may get lost!

**Comment by taylorbell57** [comment]
Is this still an issue that we need to worry about, or can we close this issue now?

**Comment by jbrande** [comment]
Yeah, we fixed this a while ago.
