### ISSUE TITLE
S2 repeatedly called when running S2 and S3 sequentially

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#92]
I just switched to using my new Macbook Pro to run Eureka and I have encountered a very strange issue. Stage 2 runs well to completion, and then when Stage 3 is called it runs as expected until `multiprocessing.Pool` is called [here](https://github.com/kevin218/Eureka/blob/0607143a1883b7438856fbd1e54660925e991235/eureka/S3_data_reduction/background.py#L56) at which point Stage 2 starts running again in as many threads as was provided in the Stage 3 `ncpu` ecf parameter... I've not encountered this before on Ubuntu and I don't think anything has changed with these relevant files since I last successfully ran S2->S4. I'm not sure how this could possibly be happening, but I'll look into it more later.

After Stage 3 starts and I get the "  Performing background subtraction" print statement, I get `ncpu` copies of this error message:

> 2022-01-19 15:49:22,337 - stpipe - WARNING - /Users/tjbell1/miniconda3/envs/ers/lib/python3.9/site-packages/photutils/detection/findstars.py:33: AstropyDeprecationWarning: _StarFinderKernel was moved to the photutils.detection._utils module. Please update your import statement.
  warnings.warn(f'{name} was moved to the {deprecated[name]} module. '

followed by `ncpu` copies of this error message:

> WARNING (only important for Stage 5): The $EXOCTK_DATA environment variable is not set.  Please set the value of this variable to point to the location of the exoctk_data download folder.  Users may retreive this folder by clicking the "ExoCTK Data Download" button on the ExoCTK website, or by using the exoctk.utils.download_exoctk_data() function.

which then is followed by "Starting Stage 2 Reduction" which should definitely not happen in Stage 3. Things then get chaotic as `ncpu` threads all start running Stage 2 and simultaneously logging text to the terminal.

For reference, I have attached a file ([eureka_environment.txt](https://github.com/kevin218/Eureka/files/7901413/eureka_environment.txt)) which exactly reproduces my conda environment on Macbooks. Relatedly, the current requirements.txt file was not sufficient to create a new environment on MacOS, so that's something we'll need to solve as well.

**Comment by taylorbell57** [comment]
I tried running Stage 3 alone on previously output Stage 2 files, and the program still breaks for me but now instead of many processes restarting Stage 2 they all instead restart at Stage 3. It seems that each of the children spawned by `multiprocessing.Pool` start from the beginning of the entire run_eureka.py command for some reason

**Comment by taylorbell57** [comment]
@kevin218, @AarynnCarter, or @meganmansfield, if any of you are using conda environments on an apple computer and have run Eureka! Stage 3 successfully, can you send me the output file (spec-file.txt) created by the following command so that I can see if my issues are related to package versions? I don't understand how things can work fine on Ubuntu but not on MacOS unless I am experiencing some very non-intuitive package issues.

Command (run within the conda environment you use for Eureka!):
`conda list --explicit > spec-file.txt`

**Comment by taylorbell57** [comment]
Hmmm, I seem to have found a way to overcome the issue by inserting the following line before the S2-5 calls in run_eureka.py (and indenting the S2-5 calls)
`if __name__ == '__main__':`

I don't know why I only encounter this on my Mac especially if anyone else has been using a Mac and run S3 successfully before, but at least this avoids the issue for me at this time

**Comment by meganmansfield** [comment]
Hey, I've been running it on a Mac but not within a specific conda environment - will that command still work? If so, I'll send you the output file if you're still having issues with that.

**Comment by taylorbell57** [comment]
Well if you've just been running it in a mega conda environment with tonnes of other packages then you'll have a lot of other packages that'll make it hard for me to figure out what differences are the relevant ones. Might still be able to make it work, but if anyone else has a cleaner conda environment then that'll be easier
