### ISSUE TITLE
Poor NIRSpec Performance

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#99]
Hi all, with my new computer I have much more RAM and am now able to process the NIRSpec data. My first attempt at doing so turned out very poorly (see attached image below). I will note that this was reduced with `jwst` v1.3.3, but I don't think that is likely to be the source of any issues. I've included the ecf files used in Stage 2 and 3 for reference (in a zip file to pacify GitHub). If @AarynnCarter or others have gotten better results with NIRSpec and can suggest better ecf settings, that would be much appreciated.

![fig3101-2D_LC](https://user-images.githubusercontent.com/24514122/151602116-2132cc00-cbbc-4bc7-b792-f68023786b76.png)

[NIRSpec ECFs.zip](https://github.com/kevin218/Eureka/files/7961003/NIRSpec.ECFs.zip)

**Comment by AarynnCarter** [comment]
Hey Taylor, I think @kevin218 got pretty much the same result as this at some point in the past. I'm in the process right now of finalising a new NIRSpec dataset / tiny version and don't want to spend too much (if any) time looking at the old dataset as there are a few changes since then. Once I have that done (I'm hoping today / Monday next week), I'll do a quick run through Eureka to see whether the same bug crops up again and let you know. 

One thing I am confident of is that the data isn't *this* bad, and it's some pipeline step that's going wrong / not interacting with the data in the way we expect it to.

**Comment by taylorbell57** [comment]
Very much understand that - thanks for looking into this when you get the chance! One thing to note is that I started from the Stage 1 outputs, and given your comment on the ERS Slack I suspect these observations also do not have a transit injected into them at this stage? Good to keep in mind, but the data should indeed look far cleaner than this

**Comment by taylorbell57** [comment]
Oh right, these plots look almost the exact same as in Issue #35

**Comment by AarynnCarter** [comment]
Yeah if you started from the uncal.fits file, there won't be any transit injected.

**Comment by taylorbell57** [comment]
Ahh, I started from the _rateints.fits file, so there is actually a transit injected. Kevin's guess on Issue #35 was right that our threshold constraints were too tight - increasing p3thresh, p5thresh, and p7thresh to 10, 20, 20 instead of 5, 10, 10 significantly improves the outputs of Stage 3 (see attached image where a transit is actually visible). I'm not sure what is driving the rest of the awfulness, but it's possible we need even looser thresholds

![fig3101-2D_LC](https://user-images.githubusercontent.com/24514122/151632526-44f8cdb3-e1f0-4892-8f0b-a20d5957be5c.png)

**Comment by taylorbell57** [comment]
Alright, I was able to get at least fairly reasonable outputs with threshold sigmas of 5, 10, 40 now. It is the p7thresh value that was really the issue. I tried using smooth and poly profiles as well, and both gave what appeared to be all NaN values.

![fig3101-2D_LC](https://user-images.githubusercontent.com/24514122/151640970-4a476a57-78a3-4a06-a4cf-0ab6fc0b2978.png)

The outputs of Stage 4 look horrible because the occasional drops in flux down to zero do not get clipped at any point. We'll probably want to add at least a mild sigma clipping in Stage 4 to remove the extreme outliers.

![Fig4300-nirspec_fs-1D_LC](https://user-images.githubusercontent.com/24514122/151641078-78e192b1-6ab1-4bf1-92cf-69c388396574.png)

**Comment by kevin218** [comment]
Not surprised about poly, but smooth should have performed well enough. One more issue to look into, I suppose.

Glad the looser threshold values are working out, but that's also an indication of a poorly constructed weighting profile. Not sure if this is due to the fact we're using CV3 data or if there's something wrong with our NIRSpec reduction.

**Comment by AarynnCarter** [comment]
Are people happy to say we're no longer in the "poor" performance regime for the NIRSpec data reduction? I've attached the MAD plot I made just before the Baltimore data challenge and it's a nice improvement over the predecessors. @cpiaulet @erinmmay @evamariaa, did you do better than mine / would you agree that we can close this? 

![fig3101-2D_LC](https://user-images.githubusercontent.com/23636747/160503012-b4e692c4-6742-45d0-8aa1-9b5dbf4e8e71.png)

**Comment by evamariaa** [comment]
Mine looks similar (see plot below) so I agree that this issue can be closed.
![NIRSpec_MAD_plot](https://user-images.githubusercontent.com/45820405/160614577-812bd157-d1e4-43d2-a3fd-1161dc0fa0fa.png)

**Comment by cpiaulet** [comment]
Sure! I think there is still a bunch to investigate though (will open another issue on this) as to the sensitivity of the quality of the extracted light curves to the S3 ecf parameters.

**Comment by taylorbell57** [comment]
I think this issue can be close now as well. The one thing I'm surprised about is how different the MAD values are between Caroline and Aarynn's plots as I would have said Aarynn's reduction looks far better than Caroline's but the MAD values disagree. That's not really the same issue though

**Comment by kevin218** [comment]
The difference in MAD values has to due with having different wavelength ranges. A lot of the extra noise in this case is coming in from >5 microns. This is why the S4 calculation of MAD is limited to the specified wavelength range. It allows for an apples-to-apples comparison.
